/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2010-3-8: 20h:54m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_types.h"
#include "ats_basics.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/array.cats"
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/slseg.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologue from statically loaded files */
/* external codes at top */
/* type definitions */
/* external typedefs */
/* external dynamic constructor declarations */
/* external dynamic constant declarations */
extern
ats_int_type atspre_add_int_int (ats_int_type, ats_int_type) ;
extern
ats_int_type atspre_mul_int_int (ats_int_type, ats_int_type) ;
extern
ats_bool_type atspre_lt_int_int (ats_int_type, ats_int_type) ;
extern
ats_bool_type atspre_lte_int_int (ats_int_type, ats_int_type) ;
extern
ats_int_type atspre_iadd (ats_int_type, ats_int_type) ;
extern
ats_void_type atspre_printf_exn (ats_ptr_type, ...) ;
extern
ats_int_type ATS_2d0_2e2_2e0_2doc_2EXAMPLE_2KernighanRitchie_2Chapter01_2power_2edats__power (ats_int_type, ats_int_type) ;

/* external dynamic terminating constant declarations */
#ifdef _ATS_TERMINATION_CHECK
#endif /* _ATS_TERMINATION_CHECK */

/* sum constructor declarations */
/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
/* internal function declarations */
static
ats_int_type loop_2 (ats_int_type env0, ats_int_type env1, ats_int_type arg0, ats_int_type arg1) ;
static
ats_clo_ptr_type loop_2_closure_make (ats_int_type env0, ats_int_type env1) ;
static
ats_int_type loop_2_clofun (ats_clo_ptr_type cloptr, ats_int_type arg0, ats_int_type arg1) ;

/* static temporary variable declarations */
/* external value variable declarations */

/* function implementations */

/*
// /home/fac2/hwxi/research/ATS/IMPLEMENT/Geizella/Anairiats/svn/ats-lang/doc/EXAMPLE/KernighanRitchie/Chapter01/power.dats: 508(line=34, offs=16) -- 647(line=39, offs=4)
*/
ats_void_type
mainats () {
/* local vardec */
ATSlocal_void (tmp0) ;
ATSlocal (ats_int_type, tmp1) ;
ATSlocal (ats_bool_type, tmp2) ;
ATSlocal (ats_int_type, tmp3) ;
ATSlocal_void (tmp4) ;
ATSlocal (ats_int_type, tmp5) ;
ATSlocal (ats_int_type, tmp6) ;

__ats_lab_mainats:
/* ats_int_type tmp1 ; */
/* loop initialization */
tmp1 = 0 ;
ats_loop_beg_mac(__ats_lab_0)
tmp2 = atspre_lt_int_int (tmp1, 10) ;
if (!tmp2) break ;
tmp5 = ATS_2d0_2e2_2e0_2doc_2EXAMPLE_2KernighanRitchie_2Chapter01_2power_2edats__power (2, tmp1) ;
tmp6 = ATS_2d0_2e2_2e0_2doc_2EXAMPLE_2KernighanRitchie_2Chapter01_2power_2edats__power (-3, tmp1) ;
/* tmp4 = */ atspre_printf_exn ((ats_ptr_type)"%d %d %d\n", tmp1, tmp5, tmp6) ;
/* post update before continue */
__ats_lab_2:
tmp3 = atspre_iadd (tmp1, 1) ;
tmp1 = tmp3 ;
ats_loop_end_mac(__ats_lab_0, __ats_lab_1)
return /* (tmp0) */ ;
} /* end of [mainats] */

/*
// /home/fac2/hwxi/research/ATS/IMPLEMENT/Geizella/Anairiats/svn/ats-lang/doc/EXAMPLE/KernighanRitchie/Chapter01/power.dats: 776(line=45, offs=7) -- 860(line=46, offs=47)
*/
ats_int_type
loop_2 (ats_int_type env0, ats_int_type env1, ats_int_type arg0, ats_int_type arg1) {
/* local vardec */
ATSlocal (ats_int_type, tmp8) ;
ATSlocal (ats_bool_type, tmp9) ;
ATSlocal (ats_int_type, tmp10) ;
ATSlocal (ats_int_type, tmp11) ;

__ats_lab_loop_2:
tmp9 = atspre_lte_int_int (arg0, env1) ;
if (tmp9) {
tmp10 = atspre_add_int_int (arg0, 1) ;
tmp11 = atspre_mul_int_int (arg1, env0) ;
arg0 = tmp10 ;
arg1 = tmp11 ;
goto __ats_lab_loop_2 ; // tail call
} else {
tmp8 = arg1 ;
} /* end of [if] */
return (tmp8) ;
} /* end of [loop_2] */

typedef struct {
ats_fun_ptr_type closure_fun ;
ats_int_type closure_env_0 ;
ats_int_type closure_env_1 ;
} loop_2_closure_type ;

ats_int_type
loop_2_clofun (ats_clo_ptr_type cloptr, ats_int_type arg0, ats_int_type arg1) {
return loop_2 (((loop_2_closure_type*)cloptr)->closure_env_0, ((loop_2_closure_type*)cloptr)->closure_env_1, arg0, arg1) ;
} /* end of function */

static inline
ats_void_type
loop_2_closure_init (loop_2_closure_type *p_clo, ats_int_type env0, ats_int_type env1) {
p_clo->closure_fun = (ats_fun_ptr_type)&loop_2_clofun ;
p_clo->closure_env_0 = env0 ;
p_clo->closure_env_1 = env1 ;
return ;
} /* end of function */

ats_clo_ptr_type
loop_2_closure_make (ats_int_type env0, ats_int_type env1) {
loop_2_closure_type *p_clo = ATS_MALLOC(sizeof(loop_2_closure_type)) ;
loop_2_closure_init (p_clo, env0, env1) ;
return (ats_clo_ptr_type)p_clo ;
} /* end of function */

/*
// /home/fac2/hwxi/research/ATS/IMPLEMENT/Geizella/Anairiats/svn/ats-lang/doc/EXAMPLE/KernighanRitchie/Chapter01/power.dats: 703(line=43, offs=17) -- 862(line=47, offs=2)
*/
ats_int_type
ATS_2d0_2e2_2e0_2doc_2EXAMPLE_2KernighanRitchie_2Chapter01_2power_2edats__power (ats_int_type arg0, ats_int_type arg1) {
/* local vardec */
ATSlocal (ats_int_type, tmp7) ;

__ats_lab_ATS_2d0_2e2_2e0_2doc_2EXAMPLE_2KernighanRitchie_2Chapter01_2power_2edats__power:
tmp7 = loop_2 (arg0, arg1, 1, 1) ;
return (tmp7) ;
} /* end of [ATS_2d0_2e2_2e0_2doc_2EXAMPLE_2KernighanRitchie_2Chapter01_2power_2edats__power] */

/* static load function */

static int ATS_2d0_2e2_2e0_2doc_2EXAMPLE_2KernighanRitchie_2Chapter01_2power_2edats__staload_flag = 0 ;

ats_void_type
ATS_2d0_2e2_2e0_2doc_2EXAMPLE_2KernighanRitchie_2Chapter01_2power_2edats__staload () {
if (ATS_2d0_2e2_2e0_2doc_2EXAMPLE_2KernighanRitchie_2Chapter01_2power_2edats__staload_flag) return ;
ATS_2d0_2e2_2e0_2doc_2EXAMPLE_2KernighanRitchie_2Chapter01_2power_2edats__staload_flag = 1 ;
return ;
} /* staload function */
/* dynamic load function */

// (external) dynload flag declaration
// extern
// int ATS_2d0_2e2_2e0_2doc_2EXAMPLE_2KernighanRitchie_2Chapter01_2power_2edats__dynload_flag ;

ats_void_type
ATS_2d0_2e2_2e0_2doc_2EXAMPLE_2KernighanRitchie_2Chapter01_2power_2edats__dynload () {
// ATS_2d0_2e2_2e0_2doc_2EXAMPLE_2KernighanRitchie_2Chapter01_2power_2edats__dynload_flag = 1 ;
ATS_2d0_2e2_2e0_2doc_2EXAMPLE_2KernighanRitchie_2Chapter01_2power_2edats__staload () ;
#ifdef _ATS_TERMINATION_CHECK
#endif /* _ATS_TERMINATION_CHECK */

/* marking static variables for GC */

/* marking external values for GC */

/* code for dynamic loading */
return ;
} /* end of [dynload function] */

int main (int argc, char *argv[]) {
ATS_GC_INIT() ;
mainats_prelude() ;
ATS_2d0_2e2_2e0_2doc_2EXAMPLE_2KernighanRitchie_2Chapter01_2power_2edats__dynload() ;
mainats((ats_int_type)argc, (ats_ptr_type)argv) ;
return (0) ;
} /* end of main */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [power_dats.c] */
