/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2010-3-8: 20h:54m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_types.h"
#include "ats_basics.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/array.cats"
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/slseg.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologue from statically loaded files */

#include "libc/CATS/stdio.cats"


#include "libc/sys/CATS/types.cats"

/* external codes at top */
/* type definitions */
/* external typedefs */
/* external dynamic constructor declarations */
/* external dynamic constant declarations */
extern
ats_char_type atspre_char_of_int (ats_int_type) ;
extern
ats_bool_type atspre_eq_char_char (ats_char_type, ats_char_type) ;
extern
ats_int_type atspre_add_int_int (ats_int_type, ats_int_type) ;
extern
ats_bool_type atspre_eq_int_int (ats_int_type, ats_int_type) ;
extern
ats_bool_type atspre_neq_int_int (ats_int_type, ats_int_type) ;
extern
ats_void_type atspre_printf_exn (ats_ptr_type, ...) ;
extern
ats_int_type atslib_getchar () ;

/* external dynamic terminating constant declarations */
#ifdef _ATS_TERMINATION_CHECK
#endif /* _ATS_TERMINATION_CHECK */

/* sum constructor declarations */
/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
/* internal function declarations */
static
ats_void_type loop_1 (ats_ref_type arg0, ats_ref_type arg1, ats_ref_type arg2, ats_ref_type arg3) ;

/* static temporary variable declarations */
/* external value variable declarations */

/* function implementations */

/*
// /home/fac2/hwxi/research/ATS/IMPLEMENT/Geizella/Anairiats/svn/ats-lang/doc/EXAMPLE/KernighanRitchie/Chapter01/wc.dats: 695(line=38, offs=7) -- 1238(line=57, offs=6)
*/
ats_void_type
loop_1 (ats_ref_type arg0, ats_ref_type arg1, ats_ref_type arg2, ats_ref_type arg3) {
/* local vardec */
ATSlocal_void (tmp1) ;
ATSlocal (ats_int_type, tmp2) ;
ATSlocal (ats_bool_type, tmp3) ;
ATSlocal (ats_int_type, tmp4) ;
ATSlocal (ats_char_type, tmp5) ;
ATSlocal (ats_bool_type, tmp7) ;
ATSlocal (ats_int_type, tmp8) ;
ATSlocal (ats_bool_type, tmp10) ;
ATSlocal (ats_int_type, tmp11) ;

__ats_lab_loop_1:
tmp2 = atslib_getchar () ;
tmp3 = atspre_neq_int_int (tmp2, EOF) ;
if (tmp3) {
tmp4 = atspre_add_int_int (*((ats_int_type*)arg2), 1) ;
*((ats_int_type*)arg2) = tmp4 ;
tmp5 = atspre_char_of_int (tmp2) ;
tmp7 = atspre_eq_char_char (tmp5, '\n') ;
if (tmp7) {
tmp8 = atspre_add_int_int (*((ats_int_type*)arg0), 1) ;
*((ats_int_type*)arg0) = tmp8 ;
} else {
/* empty */
} /* end of [if] */
do {
/* branch: __ats_lab_0 */
__ats_lab_0_0:
if (tmp5 != ' ') { goto __ats_lab_1_0 ; }
__ats_lab_0_1:
*((ats_int_type*)arg3) = 1 ;
break ;

/* branch: __ats_lab_1 */
__ats_lab_1_0:
if (tmp5 != '\n') { goto __ats_lab_2_0 ; }
__ats_lab_1_1:
*((ats_int_type*)arg3) = 1 ;
break ;

/* branch: __ats_lab_2 */
__ats_lab_2_0:
if (tmp5 != '\t') { goto __ats_lab_3_0 ; }
__ats_lab_2_1:
*((ats_int_type*)arg3) = 1 ;
break ;

/* branch: __ats_lab_3 */
__ats_lab_3_0:
__ats_lab_3_1:
tmp10 = atspre_eq_int_int (*((ats_int_type*)arg3), 1) ;
if (tmp10) {
*((ats_int_type*)arg3) = 0 ;
tmp11 = atspre_add_int_int (*((ats_int_type*)arg1), 1) ;
*((ats_int_type*)arg1) = tmp11 ;
} else {
/* empty */
} /* end of [if] */
break ;
} while (0) ;
arg0 = arg0 ;
arg1 = arg1 ;
arg2 = arg2 ;
arg3 = arg3 ;
goto __ats_lab_loop_1 ; // tail call
} else {
/* empty */
} /* end of [if] */
return /* (tmp1) */ ;
} /* end of [loop_1] */

/*
// /home/fac2/hwxi/research/ATS/IMPLEMENT/Geizella/Anairiats/svn/ats-lang/doc/EXAMPLE/KernighanRitchie/Chapter01/wc.dats: 680(line=37, offs=16) -- 1408(line=62, offs=4)
*/
ats_void_type
mainats () {
/* local vardec */
ATSlocal_void (tmp0) ;
ATSlocal (ats_int_type, tmp12) ;
ATSlocal (ats_int_type, tmp13) ;
ATSlocal (ats_int_type, tmp14) ;
ATSlocal (ats_int_type, tmp15) ;
ATSlocal_void (tmp16) ;

__ats_lab_mainats:
/* ats_int_type tmp12 ; */
tmp12 = 0 ;
/* ats_int_type tmp13 ; */
tmp13 = 0 ;
/* ats_int_type tmp14 ; */
tmp14 = 0 ;
/* ats_int_type tmp15 ; */
tmp15 = 1 ;
/* tmp16 = */ loop_1 ((&tmp12), (&tmp13), (&tmp14), (&tmp15)) ;
/* tmp0 = */ atspre_printf_exn ((ats_ptr_type)"%d %d %d\n", tmp12, tmp13, tmp14) ;
return /* (tmp0) */ ;
} /* end of [mainats] */

/* static load function */

extern
ats_void_type ATS_2d0_2e2_2e0_2libc_2SATS_2stdio_2esats__staload (void) ;
static int ATS_2d0_2e2_2e0_2doc_2EXAMPLE_2KernighanRitchie_2Chapter01_2wc_2edats__staload_flag = 0 ;

ats_void_type
ATS_2d0_2e2_2e0_2doc_2EXAMPLE_2KernighanRitchie_2Chapter01_2wc_2edats__staload () {
if (ATS_2d0_2e2_2e0_2doc_2EXAMPLE_2KernighanRitchie_2Chapter01_2wc_2edats__staload_flag) return ;
ATS_2d0_2e2_2e0_2doc_2EXAMPLE_2KernighanRitchie_2Chapter01_2wc_2edats__staload_flag = 1 ;
ATS_2d0_2e2_2e0_2libc_2SATS_2stdio_2esats__staload () ;
return ;
} /* staload function */
/* dynamic load function */

// (external) dynload flag declaration
// extern
// int ATS_2d0_2e2_2e0_2doc_2EXAMPLE_2KernighanRitchie_2Chapter01_2wc_2edats__dynload_flag ;

ats_void_type
ATS_2d0_2e2_2e0_2doc_2EXAMPLE_2KernighanRitchie_2Chapter01_2wc_2edats__dynload () {
// ATS_2d0_2e2_2e0_2doc_2EXAMPLE_2KernighanRitchie_2Chapter01_2wc_2edats__dynload_flag = 1 ;
ATS_2d0_2e2_2e0_2doc_2EXAMPLE_2KernighanRitchie_2Chapter01_2wc_2edats__staload () ;
#ifdef _ATS_TERMINATION_CHECK
#endif /* _ATS_TERMINATION_CHECK */

/* marking static variables for GC */

/* marking external values for GC */

/* code for dynamic loading */
return ;
} /* end of [dynload function] */

int main (int argc, char *argv[]) {
ATS_GC_INIT() ;
mainats_prelude() ;
ATS_2d0_2e2_2e0_2doc_2EXAMPLE_2KernighanRitchie_2Chapter01_2wc_2edats__dynload() ;
mainats((ats_int_type)argc, (ats_ptr_type)argv) ;
return (0) ;
} /* end of main */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [wc_dats.c] */
