/*
 *
 * This C code is generated by ATS/Geizella
 * The compilation time is: 2012-5-27: 21:23
 *
 */

#define _ATS_GEIZELLA 1

#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"

/* include some .cats files */

#include "prelude/CATS/array.cats"
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/string.cats"

/* external codes at top */

/* type definitions */

typedef struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_0 ;

typedef struct {
ats_ptr_type atslab_0 ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_1 ;

typedef struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_2 ;

typedef struct {
ats_ptr_type atslab_c0lau_loc ;
ats_ptr_type atslab_c0lau_pat ;
ats_int_type atslab_c0lau_seq ;
ats_int_type atslab_c0lau_neg ;
ats_ptr_type atslab_c0lau_body ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_rec_3 ;

typedef struct {
ats_ptr_type atslab_v0aldec_loc ;
ats_ptr_type atslab_v0aldec_pat ;
ats_ptr_type atslab_v0aldec_def ;
ats_ptr_type atslab_v0aldec_ann ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_rec_4 ;

typedef struct {
ats_ptr_type atslab_f0undec_loc ;
ats_ptr_type atslab_f0undec_sym ;
ats_ptr_type atslab_f0undec_sym_loc ;
ats_ptr_type atslab_f0undec_arg ;
ats_ptr_type atslab_f0undec_eff ;
ats_ptr_type atslab_f0undec_res ;
ats_ptr_type atslab_f0undec_def ;
ats_ptr_type atslab_f0undec_ann ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_rec_5 ;

typedef struct {
ats_ptr_type atslab_v0ardec_loc ;
ats_int_type atslab_v0ardec_knd ;
ats_ptr_type atslab_v0ardec_sym ;
ats_ptr_type atslab_v0ardec_sym_loc ;
ats_ptr_type atslab_v0ardec_typ ;
ats_ptr_type atslab_v0ardec_wth ;
ats_ptr_type atslab_v0ardec_ini ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_rec_6 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_7 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_8 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
ats_ptr_type atslab_3 ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_9 ;

typedef struct {
ats_ptr_type atslab_d0exp_loc ;
ats_ptr_type atslab_d0exp_node ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_rec_10 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
ats_ptr_type atslab_3 ;
ats_ptr_type atslab_4 ;
ats_ptr_type atslab_5 ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_11 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_12 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
ats_ptr_type atslab_3 ;
ats_ptr_type atslab_4 ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_13 ;

typedef struct {
int tag ;
ats_int_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_14 ;

typedef struct {
int tag ;
ats_int_type atslab_0 ;
ats_ptr_type atslab_1 ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_15 ;

typedef struct {
ats_ptr_type atslab_d0ec_loc ;
ats_ptr_type atslab_d0ec_node ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_rec_16 ;

typedef struct {
ats_ptr_type atslab_i0mpdec_loc ;
ats_ptr_type atslab_i0mpdec_qid ;
ats_ptr_type atslab_i0mpdec_arg ;
ats_ptr_type atslab_i0mpdec_res ;
ats_ptr_type atslab_i0mpdec_def ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_rec_17 ;

typedef struct {
ats_ptr_type atslab_guad0ec_loc ;
ats_ptr_type atslab_guad0ec_node ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_rec_18 ;

/* external dynamic constructor declarations */

ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fprelude_2fGEIZELLA_2fbasics_sta_2esats__None) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fprelude_2fGEIZELLA_2fbasics_sta_2esats__Some) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fprelude_2fGEIZELLA_2fbasics_sta_2esats__list_vt_cons) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fprelude_2fGEIZELLA_2fbasics_sta_2esats__list_vt_nil) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__D0Eann) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__D0Eapp) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__D0Earrinit) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__D0Earrsize) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__D0Earrsub) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__D0Ecaseof) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__D0Eexist) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__D0Efix) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__D0Efoldat) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__D0Efor) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__D0Efreeat) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__D0Eif) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__D0Elam) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__D0Elet) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__D0Elist) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__D0Elist2) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__D0Elst) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__D0Emacsyn) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__D0Eraise) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__D0Erec) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__D0Esel_ind) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__D0Eseq) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__D0Esif) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__D0Estruct) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__D0Etrywith) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__D0Etup) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__D0Etup2) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__D0Eviewat) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__D0Ewhere) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__D0Ewhile) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__LABD0EXPLSTnil) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__LABD0EXPLSTcons) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__D0Cinclude) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__D0Cvaldecs) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__D0Cvaldecs_rec) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__D0Cfundecs) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__D0Cvardecs) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__D0Cimpdec) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__D0Cstaload) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__D0Clocal) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__D0Cguadec) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__GD0Cone) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__GD0Ctwo) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__GD0Ccons) ;

/* external dynamic constant declarations */

extern ats_void_type atspre_fprint_newline(ats_ref_type) ;
extern ats_void_type atspre_fprint_char(ats_ref_type, ats_char_type) ;
extern ats_bool_type atspre_test_file_exists(ats_ptr_type) ;
extern ats_void_type atspre_fprintf_exn(ats_ref_type, ats_ptr_type, ...) ;
extern ats_bool_type atspre_eq_size_size(ats_size_type, ats_size_type) ;
extern ats_size_type atspre_add_size1_int1(ats_size_type, ats_int_type) ;
extern ats_bool_type atspre_gte_ssize1_int1(ats_ssize_type, ats_int_type) ;
extern ats_ptr_type atspre_castfn_ptr(ats_ptr_type) ;
extern ats_void_type atspre_fprint_string(ats_ref_type, ats_ptr_type) ;
extern ats_char_type atspre_string_get_char_at(ats_ptr_type, ats_size_type) ;
extern ats_bool_type atspre_string_isnot_at_end(ats_ptr_type, ats_size_type) ;
extern ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_list_2esats__list_foreach_fun(ats_ptr_type, ats_ptr_type) ;
extern ats_ptr_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_list_2esats__list_vt_reverse(ats_ptr_type) ;
extern ats_ptr_type atspre_ref_make_elt_tsz(ats_ref_type, ats_size_type) ;
extern ats_ptr_type atspre_ref_get_view_ptr(ats_ptr_type) ;
extern ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__depgen_d0eclst(ats_ptr_type) ;
extern ats_ssize_type atspre_string_index_of_char_from_right(ats_ptr_type, ats_char_type) ;
extern ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__depgen_d0ec(ats_ptr_type) ;
extern ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__depgen_d0exp(ats_ptr_type) ;

/* internal function declarations */

static ats_ptr_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_reference_2esats__ref_make_elt__ats_ptr_type (ats_ptr_type arg0) ;

static ats_ptr_type the_deplst_get_1 () ;

static ats_void_type the_deplst_push_2 (ats_ptr_type arg0) ;

static ats_void_type fprint_target_3 (ats_ref_type arg0, ats_ptr_type arg1) ;

static ats_void_type pr_4 (ats_ref_type arg0, ats_ptr_type arg1, ats_size_type arg2, ats_size_type arg3) ;

static ats_void_type loop_6 (ats_ref_type arg0, ats_ptr_type arg1) ;

static ats_void_type depgen_d0explst_7 (ats_ptr_type arg0) ;

static ats_void_type depgen_d0explstlst_8 (ats_ptr_type arg0) ;

static ats_void_type depgen_d0expopt_9 (ats_ptr_type arg0) ;

static ats_void_type depgen_labd0explst_10 (ats_ptr_type arg0) ;

static ats_void_type depgen_c0lau_11 (ats_ptr_type arg0) ;

static ats_void_type depgen_c0laulst_12 (ats_ptr_type arg0) ;

static ats_void_type depgen_v0aldec_13 (ats_ptr_type arg0) ;

static ats_void_type depgen_f0undec_14 (ats_ptr_type arg0) ;

static ats_void_type depgen_v0ardec_15 (ats_ptr_type arg0) ;

static ats_void_type depgen_guad0ec_node_16 (ats_ptr_type arg0) ;

/* sum constructor declarations */

/* exception constructor declarations */

ATSglobal(ats_exn_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_lexing_2esats__LexingErrorException) ;

/* global dynamic constant declarations */

/* static temporary variable declarations */

ATSstatic(ats_ptr_type, tmp0) ;
ATSstatic(ats_ptr_type, tmp3) ;

/* function implementations */

ats_ptr_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_reference_2esats__ref_make_elt__ats_ptr_type (ats_ptr_type arg0) {
ATSlocal(ats_ptr_type, tmp1) ;
ATSlocal(ats_ptr_type, tmp2) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_reference_2esats__ref_make_elt__ats_ptr_type:
tmp2 = arg0 ;
tmp1 = atspre_ref_make_elt_tsz ((&tmp2), sizeof(ats_ptr_type)) ;
return tmp1 ;
} /* fun */

ats_ptr_type
the_deplst_get_1 () {
ATSlocal(ats_ptr_type, tmp4) ;
ATSlocal(ats_ptr_type, tmp5) ;
ATSlocal(ats_ptr_type, tmp6) ;
ATSlocal(ats_ptr_type, tmp7) ;
ATSlocal(ats_ptr_type, tmp8) ;
__ats_lab_the_deplst_get_1:
tmp5 = atspre_ref_get_view_ptr (tmp0) ;
tmp6 = (tmp5) ;
tmp7 = *((ats_ptr_type*)tmp6) ;
tmp8 = (ats_sum_ptr_type)0 ;

*((ats_ptr_type*)tmp6) = tmp8 ;
tmp4 = tmp7 ;
return tmp4 ;
} /* fun */

ats_void_type
the_deplst_push_2 (ats_ptr_type arg0) {
ATSlocal_void(tmp9) ;
ATSlocal(ats_ptr_type, tmp10) ;
ATSlocal(ats_ptr_type, tmp11) ;
ATSlocal(ats_ptr_type, tmp12) ;
ATSlocal(ats_ptr_type, tmp13) ;
__ats_lab_the_deplst_push_2:
tmp10 = atspre_ref_get_view_ptr (tmp0) ;
tmp11 = (tmp10) ;
tmp13 = *((ats_ptr_type*)tmp11) ;
tmp12 = ATS_MALLOC(sizeof(_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_0)) ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_0*)tmp12)->atslab_0 = arg0 ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_0*)tmp12)->atslab_1 = tmp13 ;

*((ats_ptr_type*)tmp11) = tmp12 ;
return ;
} /* fun */

ats_void_type
fprint_target_3 (ats_ref_type arg0, ats_ptr_type arg1) {
ATSlocal_void(tmp14) ;
ATSlocal(ats_ptr_type, tmp15) ;
ATSlocal(ats_ssize_type, tmp16) ;
ATSlocal(ats_bool_type, tmp18) ;
ATSlocal_void(tmp32) ;
__ats_lab_fprint_target_3:
tmp15 = atspre_castfn_ptr (arg1) ;
tmp16 = atspre_string_index_of_char_from_right (tmp15, '.') ;
do {
__ats_lab_0:
tmp18 = atspre_gte_ssize1_int1 (tmp16, 0) ;
if (!tmp18) { goto __ats_lab_1 ; }
/* tmp32 = */ pr_4 (arg0, tmp15, ats_castfn_mac(ats_size_type, tmp16), 0) ;
/* tmp14 = */ atspre_fprint_string (arg0, ".o") ;
break ;

__ats_lab_1:
/* tmp14 = */ atspre_fprint_string (arg0, tmp15) ;
break ;

} while (0) ;
return ;
} /* fun */

ats_void_type
pr_4 (ats_ref_type arg0, ats_ptr_type arg1, ats_size_type arg2, ats_size_type arg3) {
ATSlocal_void(tmp19) ;
ATSlocal(ats_bool_type, tmp20) ;
ATSlocal(ats_char_type, tmp22) ;
ATSlocal(ats_bool_type, tmp23) ;
ATSlocal_void(tmp26) ;
ATSlocal(ats_ref_type, tmp27) ;
ATSlocal(ats_ptr_type, tmp28) ;
ATSlocal(ats_size_type, tmp29) ;
ATSlocal(ats_size_type, tmp30) ;
__ats_lab_pr_4:
tmp20 = atspre_string_isnot_at_end (arg1, arg3) ;
if (tmp20) {
tmp23 = atspre_eq_size_size (arg3, arg2) ;
if (tmp23) {
tmp22 = '_' ;
} else {
tmp22 = atspre_string_get_char_at (arg1, arg3) ;
} /* if */
/* tmp26 = */ atspre_fprint_char (arg0, tmp22) ;
tmp27 = arg0 ;
tmp28 = arg1 ;
tmp29 = arg2 ;
tmp30 = atspre_add_size1_int1 (arg3, 1) ;
arg0 = tmp27 ;
arg1 = tmp28 ;
arg2 = tmp29 ;
arg3 = tmp30 ;
goto __ats_lab_pr_4 ;
} else {
} /* if */
return ;
} /* fun */

ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__fprint_depgen (ats_ref_type arg0, ats_ptr_type arg1) {
ATSlocal_void(tmp34) ;
ATSlocal(ats_ptr_type, tmp35) ;
ATSlocal(ats_ptr_type, tmp36) ;
ATSlocal_void(tmp37) ;
ATSlocal_void(tmp38) ;
ATSlocal_void(tmp39) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__fprint_depgen:
tmp35 = the_deplst_get_1 () ;
tmp36 = _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_list_2esats__list_vt_reverse (tmp35) ;
/* tmp37 = */ fprint_target_3 (arg0, arg1) ;
/* tmp38 = */ atspre_fprint_string (arg0, " :") ;
/* tmp39 = */ loop_6 (arg0, tmp36) ;
/* tmp34 = */ atspre_fprint_newline (arg0) ;
return ;
} /* fun */

ats_void_type
loop_6 (ats_ref_type arg0, ats_ptr_type arg1) {
ATSlocal_void(tmp40) ;
ATSlocal(ats_ptr_type, tmp42) ;
ATSlocal(ats_ptr_type, tmp43) ;
ATSlocal_void(tmp44) ;
ATSlocal(ats_ref_type, tmp45) ;
ATSlocal(ats_ptr_type, tmp46) ;
__ats_lab_loop_6:
do {
__ats_lab_2:
if (arg1 == (ats_sum_ptr_type)0) { goto __ats_lab_3 ; }
tmp42 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_0*)arg1)->atslab_0 ;
tmp43 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_0*)arg1)->atslab_1 ;
ATS_FREE(arg1) ;
/* tmp44 = */ atspre_fprintf_exn (arg0, " %s", tmp42) ;
tmp45 = arg0 ;
tmp46 = tmp43 ;
arg0 = tmp45 ;
arg1 = tmp46 ;
goto __ats_lab_loop_6 ;
break ;

__ats_lab_3:
break ;

} while (0) ;
return ;
} /* fun */

ats_void_type
depgen_d0explst_7 (ats_ptr_type arg0) {
ATSlocal_void(tmp48) ;
__ats_lab_depgen_d0explst_7:
/* tmp48 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_list_2esats__list_foreach_fun (arg0, (&_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__depgen_d0exp)) ;
return ;
} /* fun */

ats_void_type
depgen_d0explstlst_8 (ats_ptr_type arg0) {
ATSlocal_void(tmp49) ;
__ats_lab_depgen_d0explstlst_8:
/* tmp49 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_list_2esats__list_foreach_fun (arg0, &depgen_d0explst_7) ;
return ;
} /* fun */

ats_void_type
depgen_d0expopt_9 (ats_ptr_type arg0) {
ATSlocal_void(tmp50) ;
ATSlocal(ats_ptr_type, tmp52) ;
__ats_lab_depgen_d0expopt_9:
do {
__ats_lab_4:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_5 ; }
tmp52 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_1*)arg0)->atslab_0 ;
/* tmp50 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__depgen_d0exp (tmp52) ;
break ;

__ats_lab_5:
break ;

} while (0) ;
return ;
} /* fun */

ats_void_type
depgen_labd0explst_10 (ats_ptr_type arg0) {
ATSlocal_void(tmp54) ;
ATSlocal(ats_ptr_type, tmp57) ;
ATSlocal(ats_ptr_type, tmp58) ;
ATSlocal_void(tmp59) ;
ATSlocal(ats_ptr_type, tmp60) ;
__ats_lab_depgen_labd0explst_10:
do {
__ats_lab_6:
if (arg0 != (ats_sum_ptr_type)0) { goto __ats_lab_7 ; }
break ;

__ats_lab_7:
tmp57 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_2*)arg0)->atslab_1 ;
tmp58 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_2*)arg0)->atslab_2 ;
/* tmp59 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__depgen_d0exp (tmp57) ;
tmp60 = tmp58 ;
arg0 = tmp60 ;
goto __ats_lab_depgen_labd0explst_10 ;
break ;

} while (0) ;
return ;
} /* fun */

ats_void_type
depgen_c0lau_11 (ats_ptr_type arg0) {
ATSlocal_void(tmp61) ;
ATSlocal(ats_ptr_type, tmp62) ;
__ats_lab_depgen_c0lau_11:
tmp62 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_rec_3*)arg0)->atslab_c0lau_body ;
/* tmp61 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__depgen_d0exp (tmp62) ;
return ;
} /* fun */

ats_void_type
depgen_c0laulst_12 (ats_ptr_type arg0) {
ATSlocal_void(tmp63) ;
__ats_lab_depgen_c0laulst_12:
/* tmp63 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_list_2esats__list_foreach_fun (arg0, &depgen_c0lau_11) ;
return ;
} /* fun */

ats_void_type
depgen_v0aldec_13 (ats_ptr_type arg0) {
ATSlocal_void(tmp64) ;
ATSlocal(ats_ptr_type, tmp65) ;
__ats_lab_depgen_v0aldec_13:
tmp65 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_rec_4*)arg0)->atslab_v0aldec_def ;
/* tmp64 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__depgen_d0exp (tmp65) ;
return ;
} /* fun */

ats_void_type
depgen_f0undec_14 (ats_ptr_type arg0) {
ATSlocal_void(tmp66) ;
ATSlocal(ats_ptr_type, tmp67) ;
__ats_lab_depgen_f0undec_14:
tmp67 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_rec_5*)arg0)->atslab_f0undec_def ;
/* tmp66 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__depgen_d0exp (tmp67) ;
return ;
} /* fun */

ats_void_type
depgen_v0ardec_15 (ats_ptr_type arg0) {
ATSlocal_void(tmp68) ;
ATSlocal(ats_ptr_type, tmp69) ;
__ats_lab_depgen_v0ardec_15:
tmp69 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_rec_6*)arg0)->atslab_v0ardec_ini ;
/* tmp68 = */ depgen_d0expopt_9 (tmp69) ;
return ;
} /* fun */

ats_void_type
depgen_guad0ec_node_16 (ats_ptr_type arg0) {
ATSlocal_void(tmp70) ;
ATSlocal(ats_ptr_type, tmp72) ;
ATSlocal(ats_ptr_type, tmp74) ;
ATSlocal(ats_ptr_type, tmp75) ;
ATSlocal_void(tmp76) ;
ATSlocal(ats_ptr_type, tmp78) ;
ATSlocal(ats_ptr_type, tmp79) ;
ATSlocal_void(tmp80) ;
ATSlocal(ats_ptr_type, tmp81) ;
__ats_lab_depgen_guad0ec_node_16:
do {
__ats_lab_8:
if (((ats_sum_ptr_type)arg0)->tag != 0) { goto __ats_lab_9 ; }
tmp72 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_7*)arg0)->atslab_1 ;
/* tmp70 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__depgen_d0eclst (tmp72) ;
break ;

__ats_lab_9:
if (((ats_sum_ptr_type)arg0)->tag != 1) { goto __ats_lab_10 ; }
tmp74 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_8*)arg0)->atslab_1 ;
tmp75 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_8*)arg0)->atslab_2 ;
/* tmp76 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__depgen_d0eclst (tmp74) ;
/* tmp70 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__depgen_d0eclst (tmp75) ;
break ;

__ats_lab_10:
tmp78 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_9*)arg0)->atslab_1 ;
tmp79 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_9*)arg0)->atslab_3 ;
/* tmp80 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__depgen_d0eclst (tmp78) ;
tmp81 = tmp79 ;
arg0 = tmp81 ;
goto __ats_lab_depgen_guad0ec_node_16 ;
break ;

} while (0) ;
return ;
} /* fun */

ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__depgen_d0exp (ats_ptr_type arg0) {
ATSlocal_void(tmp82) ;
ATSlocal(ats_ptr_type, tmp83) ;
ATSlocal(ats_ptr_type, tmp85) ;
ATSlocal(ats_ptr_type, tmp86) ;
ATSlocal(ats_ptr_type, tmp88) ;
ATSlocal(ats_ptr_type, tmp89) ;
ATSlocal_void(tmp90) ;
ATSlocal(ats_ptr_type, tmp91) ;
ATSlocal(ats_ptr_type, tmp93) ;
ATSlocal(ats_ptr_type, tmp94) ;
ATSlocal_void(tmp95) ;
ATSlocal(ats_ptr_type, tmp97) ;
ATSlocal(ats_ptr_type, tmp98) ;
ATSlocal(ats_ptr_type, tmp100) ;
ATSlocal(ats_ptr_type, tmp102) ;
ATSlocal(ats_ptr_type, tmp103) ;
ATSlocal_void(tmp104) ;
ATSlocal(ats_ptr_type, tmp106) ;
ATSlocal(ats_ptr_type, tmp107) ;
ATSlocal(ats_ptr_type, tmp109) ;
ATSlocal(ats_ptr_type, tmp110) ;
ATSlocal(ats_ptr_type, tmp112) ;
ATSlocal(ats_ptr_type, tmp114) ;
ATSlocal(ats_ptr_type, tmp115) ;
ATSlocal(ats_ptr_type, tmp116) ;
ATSlocal(ats_ptr_type, tmp117) ;
ATSlocal_void(tmp118) ;
ATSlocal_void(tmp119) ;
ATSlocal_void(tmp120) ;
ATSlocal(ats_ptr_type, tmp121) ;
ATSlocal(ats_ptr_type, tmp123) ;
ATSlocal(ats_ptr_type, tmp125) ;
ATSlocal(ats_ptr_type, tmp126) ;
ATSlocal(ats_ptr_type, tmp127) ;
ATSlocal_void(tmp128) ;
ATSlocal_void(tmp129) ;
ATSlocal(ats_ptr_type, tmp131) ;
ATSlocal(ats_ptr_type, tmp132) ;
ATSlocal(ats_ptr_type, tmp134) ;
ATSlocal(ats_ptr_type, tmp135) ;
ATSlocal_void(tmp136) ;
ATSlocal(ats_ptr_type, tmp137) ;
ATSlocal(ats_ptr_type, tmp139) ;
ATSlocal(ats_ptr_type, tmp141) ;
ATSlocal(ats_ptr_type, tmp142) ;
ATSlocal_void(tmp143) ;
ATSlocal(ats_ptr_type, tmp145) ;
ATSlocal(ats_ptr_type, tmp146) ;
ATSlocal(ats_ptr_type, tmp148) ;
ATSlocal(ats_ptr_type, tmp149) ;
ATSlocal(ats_ptr_type, tmp151) ;
ATSlocal(ats_ptr_type, tmp152) ;
ATSlocal(ats_ptr_type, tmp154) ;
ATSlocal(ats_ptr_type, tmp156) ;
ATSlocal(ats_ptr_type, tmp158) ;
ATSlocal(ats_ptr_type, tmp160) ;
ATSlocal(ats_ptr_type, tmp161) ;
ATSlocal_void(tmp162) ;
ATSlocal(ats_ptr_type, tmp163) ;
ATSlocal(ats_ptr_type, tmp165) ;
ATSlocal(ats_ptr_type, tmp167) ;
ATSlocal(ats_ptr_type, tmp168) ;
ATSlocal_void(tmp169) ;
ATSlocal(ats_ptr_type, tmp171) ;
ATSlocal(ats_ptr_type, tmp173) ;
ATSlocal(ats_ptr_type, tmp174) ;
ATSlocal_void(tmp175) ;
ATSlocal(ats_ptr_type, tmp178) ;
ATSlocal(ats_ptr_type, tmp179) ;
ATSlocal_void(tmp180) ;
ATSlocal(ats_ptr_type, tmp182) ;
ATSlocal(ats_ptr_type, tmp183) ;
ATSlocal_void(tmp184) ;
ATSlocal(ats_ptr_type, tmp185) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__depgen_d0exp:
tmp83 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_rec_10*)arg0)->atslab_d0exp_node ;
do {
__ats_lab_11:
if (((ats_sum_ptr_type)tmp83)->tag != 0) { goto __ats_lab_12 ; }
tmp85 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_7*)tmp83)->atslab_0 ;
tmp86 = tmp85 ;
arg0 = tmp86 ;
goto __ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__depgen_d0exp ;
break ;

__ats_lab_12:
if (((ats_sum_ptr_type)tmp83)->tag != 1) { goto __ats_lab_13 ; }
tmp88 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_7*)tmp83)->atslab_0 ;
tmp89 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_7*)tmp83)->atslab_1 ;
/* tmp90 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__depgen_d0exp (tmp88) ;
tmp91 = tmp89 ;
arg0 = tmp91 ;
goto __ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__depgen_d0exp ;
break ;

__ats_lab_13:
if (((ats_sum_ptr_type)tmp83)->tag != 2) { goto __ats_lab_14 ; }
tmp93 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_8*)tmp83)->atslab_1 ;
tmp94 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_8*)tmp83)->atslab_2 ;
/* tmp95 = */ depgen_d0expopt_9 (tmp93) ;
/* tmp82 = */ depgen_d0explst_7 (tmp94) ;
break ;

__ats_lab_14:
if (((ats_sum_ptr_type)tmp83)->tag != 3) { goto __ats_lab_15 ; }
tmp97 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_7*)tmp83)->atslab_1 ;
tmp98 = tmp97 ;
arg0 = tmp98 ;
goto __ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__depgen_d0exp ;
break ;

__ats_lab_15:
if (((ats_sum_ptr_type)tmp83)->tag != 4) { goto __ats_lab_16 ; }
tmp100 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_8*)tmp83)->atslab_2 ;
/* tmp82 = */ depgen_d0explstlst_8 (tmp100) ;
break ;

__ats_lab_16:
if (((ats_sum_ptr_type)tmp83)->tag != 5) { goto __ats_lab_17 ; }
tmp102 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_8*)tmp83)->atslab_1 ;
tmp103 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_8*)tmp83)->atslab_2 ;
/* tmp104 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__depgen_d0exp (tmp102) ;
/* tmp82 = */ depgen_c0laulst_12 (tmp103) ;
break ;

__ats_lab_17:
if (((ats_sum_ptr_type)tmp83)->tag != 14) { goto __ats_lab_18 ; }
tmp106 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_8*)tmp83)->atslab_2 ;
tmp107 = tmp106 ;
arg0 = tmp107 ;
goto __ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__depgen_d0exp ;
break ;

__ats_lab_18:
if (((ats_sum_ptr_type)tmp83)->tag != 16) { goto __ats_lab_19 ; }
tmp109 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_11*)tmp83)->atslab_5 ;
tmp110 = tmp109 ;
arg0 = tmp110 ;
goto __ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__depgen_d0exp ;
break ;

__ats_lab_19:
if (((ats_sum_ptr_type)tmp83)->tag != 19) { goto __ats_lab_20 ; }
tmp112 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_12*)tmp83)->atslab_0 ;
/* tmp82 = */ depgen_d0explst_7 (tmp112) ;
break ;

__ats_lab_20:
if (((ats_sum_ptr_type)tmp83)->tag != 20) { goto __ats_lab_21 ; }
tmp114 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_11*)tmp83)->atslab_2 ;
tmp115 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_11*)tmp83)->atslab_3 ;
tmp116 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_11*)tmp83)->atslab_4 ;
tmp117 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_11*)tmp83)->atslab_5 ;
/* tmp118 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__depgen_d0exp (tmp114) ;
/* tmp119 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__depgen_d0exp (tmp115) ;
/* tmp120 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__depgen_d0exp (tmp116) ;
tmp121 = tmp117 ;
arg0 = tmp121 ;
goto __ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__depgen_d0exp ;
break ;

__ats_lab_21:
if (((ats_sum_ptr_type)tmp83)->tag != 21) { goto __ats_lab_22 ; }
tmp123 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_12*)tmp83)->atslab_0 ;
/* tmp82 = */ depgen_d0explst_7 (tmp123) ;
break ;

__ats_lab_22:
if (((ats_sum_ptr_type)tmp83)->tag != 24) { goto __ats_lab_23 ; }
tmp125 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_9*)tmp83)->atslab_1 ;
tmp126 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_9*)tmp83)->atslab_2 ;
tmp127 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_9*)tmp83)->atslab_3 ;
/* tmp128 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__depgen_d0exp (tmp125) ;
/* tmp129 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__depgen_d0exp (tmp126) ;
/* tmp82 = */ depgen_d0expopt_9 (tmp127) ;
break ;

__ats_lab_23:
if (((ats_sum_ptr_type)tmp83)->tag != 27) { goto __ats_lab_24 ; }
tmp131 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_13*)tmp83)->atslab_4 ;
tmp132 = tmp131 ;
arg0 = tmp132 ;
goto __ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__depgen_d0exp ;
break ;

__ats_lab_24:
if (((ats_sum_ptr_type)tmp83)->tag != 28) { goto __ats_lab_25 ; }
tmp134 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_7*)tmp83)->atslab_0 ;
tmp135 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_7*)tmp83)->atslab_1 ;
/* tmp136 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__depgen_d0eclst (tmp134) ;
tmp137 = tmp135 ;
arg0 = tmp137 ;
goto __ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__depgen_d0exp ;
break ;

__ats_lab_25:
if (((ats_sum_ptr_type)tmp83)->tag != 29) { goto __ats_lab_26 ; }
tmp139 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_12*)tmp83)->atslab_0 ;
/* tmp82 = */ depgen_d0explst_7 (tmp139) ;
break ;

__ats_lab_26:
if (((ats_sum_ptr_type)tmp83)->tag != 30) { goto __ats_lab_27 ; }
tmp141 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_7*)tmp83)->atslab_0 ;
tmp142 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_7*)tmp83)->atslab_1 ;
/* tmp143 = */ depgen_d0explst_7 (tmp141) ;
/* tmp82 = */ depgen_d0explst_7 (tmp142) ;
break ;

__ats_lab_27:
if (((ats_sum_ptr_type)tmp83)->tag != 32) { goto __ats_lab_28 ; }
tmp145 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_14*)tmp83)->atslab_2 ;
tmp146 = tmp145 ;
arg0 = tmp146 ;
goto __ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__depgen_d0exp ;
break ;

__ats_lab_28:
if (((ats_sum_ptr_type)tmp83)->tag != 33) { goto __ats_lab_29 ; }
tmp148 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_7*)tmp83)->atslab_1 ;
tmp149 = tmp148 ;
arg0 = tmp149 ;
goto __ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__depgen_d0exp ;
break ;

__ats_lab_29:
if (((ats_sum_ptr_type)tmp83)->tag != 37) { goto __ats_lab_30 ; }
tmp151 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_12*)tmp83)->atslab_0 ;
tmp152 = tmp151 ;
arg0 = tmp152 ;
goto __ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__depgen_d0exp ;
break ;

__ats_lab_30:
if (((ats_sum_ptr_type)tmp83)->tag != 38) { goto __ats_lab_31 ; }
tmp154 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_15*)tmp83)->atslab_1 ;
/* tmp82 = */ depgen_labd0explst_10 (tmp154) ;
break ;

__ats_lab_31:
if (((ats_sum_ptr_type)tmp83)->tag != 41) { goto __ats_lab_32 ; }
tmp156 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_15*)tmp83)->atslab_1 ;
/* tmp82 = */ depgen_d0explstlst_8 (tmp156) ;
break ;

__ats_lab_32:
if (((ats_sum_ptr_type)tmp83)->tag != 42) { goto __ats_lab_33 ; }
tmp158 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_12*)tmp83)->atslab_0 ;
/* tmp82 = */ depgen_d0explst_7 (tmp158) ;
break ;

__ats_lab_33:
if (((ats_sum_ptr_type)tmp83)->tag != 44) { goto __ats_lab_34 ; }
tmp160 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_9*)tmp83)->atslab_2 ;
tmp161 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_9*)tmp83)->atslab_3 ;
/* tmp162 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__depgen_d0exp (tmp160) ;
tmp163 = tmp161 ;
arg0 = tmp163 ;
goto __ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__depgen_d0exp ;
break ;

__ats_lab_34:
if (((ats_sum_ptr_type)tmp83)->tag != 46) { goto __ats_lab_35 ; }
tmp165 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_12*)tmp83)->atslab_0 ;
/* tmp82 = */ depgen_labd0explst_10 (tmp165) ;
break ;

__ats_lab_35:
if (((ats_sum_ptr_type)tmp83)->tag != 49) { goto __ats_lab_36 ; }
tmp167 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_8*)tmp83)->atslab_1 ;
tmp168 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_8*)tmp83)->atslab_2 ;
/* tmp169 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__depgen_d0exp (tmp167) ;
/* tmp82 = */ depgen_c0laulst_12 (tmp168) ;
break ;

__ats_lab_36:
if (((ats_sum_ptr_type)tmp83)->tag != 50) { goto __ats_lab_37 ; }
tmp171 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_15*)tmp83)->atslab_1 ;
/* tmp82 = */ depgen_d0explst_7 (tmp171) ;
break ;

__ats_lab_37:
if (((ats_sum_ptr_type)tmp83)->tag != 51) { goto __ats_lab_38 ; }
tmp173 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_14*)tmp83)->atslab_1 ;
tmp174 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_14*)tmp83)->atslab_2 ;
/* tmp175 = */ depgen_d0explst_7 (tmp173) ;
/* tmp82 = */ depgen_d0explst_7 (tmp174) ;
break ;

__ats_lab_38:
if (tmp83 != &_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__D0Eviewat) { goto __ats_lab_39 ; }
break ;

__ats_lab_39:
if (((ats_sum_ptr_type)tmp83)->tag != 53) { goto __ats_lab_40 ; }
tmp178 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_7*)tmp83)->atslab_0 ;
tmp179 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_7*)tmp83)->atslab_1 ;
/* tmp180 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__depgen_d0exp (tmp178) ;
/* tmp82 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__depgen_d0eclst (tmp179) ;
break ;

__ats_lab_40:
if (((ats_sum_ptr_type)tmp83)->tag != 54) { goto __ats_lab_41 ; }
tmp182 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_9*)tmp83)->atslab_2 ;
tmp183 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_9*)tmp83)->atslab_3 ;
/* tmp184 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__depgen_d0exp (tmp182) ;
tmp185 = tmp183 ;
arg0 = tmp185 ;
goto __ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__depgen_d0exp ;
break ;

__ats_lab_41:
break ;

} while (0) ;
return ;
} /* fun */

ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__depgen_d0ec (ats_ptr_type arg0) {
ATSlocal_void(tmp187) ;
ATSlocal(ats_ptr_type, tmp188) ;
ATSlocal(ats_ptr_type, tmp190) ;
ATSlocal(ats_bool_type, tmp191) ;
ATSlocal(ats_ptr_type, tmp195) ;
ATSlocal(ats_ptr_type, tmp196) ;
ATSlocal_void(tmp197) ;
ATSlocal(ats_ptr_type, tmp199) ;
ATSlocal(ats_ptr_type, tmp200) ;
ATSlocal_void(tmp201) ;
ATSlocal(ats_ptr_type, tmp203) ;
ATSlocal(ats_ptr_type, tmp204) ;
ATSlocal_void(tmp205) ;
ATSlocal(ats_ptr_type, tmp207) ;
ATSlocal(ats_ptr_type, tmp208) ;
ATSlocal_void(tmp209) ;
ATSlocal(ats_ptr_type, tmp211) ;
ATSlocal(ats_ptr_type, tmp212) ;
ATSlocal(ats_ptr_type, tmp214) ;
ATSlocal(ats_bool_type, tmp215) ;
ATSlocal(ats_ptr_type, tmp219) ;
ATSlocal(ats_ptr_type, tmp220) ;
ATSlocal_void(tmp221) ;
ATSlocal(ats_ptr_type, tmp223) ;
ATSlocal(ats_ptr_type, tmp224) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__depgen_d0ec:
tmp188 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_rec_16*)arg0)->atslab_d0ec_node ;
do {
__ats_lab_42:
if (((ats_sum_ptr_type)tmp188)->tag != 2) { goto __ats_lab_43 ; }
tmp190 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_15*)tmp188)->atslab_1 ;
tmp191 = atspre_test_file_exists (tmp190) ;
if (tmp191) {
/* tmp187 = */ the_deplst_push_2 (tmp190) ;
} else {
} /* if */
break ;

__ats_lab_43:
if (((ats_sum_ptr_type)tmp188)->tag != 22) { goto __ats_lab_44 ; }
tmp195 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_8*)tmp188)->atslab_1 ;
tmp196 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_8*)tmp188)->atslab_2 ;
/* tmp197 = */ depgen_v0aldec_13 (tmp195) ;
/* tmp187 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_list_2esats__list_foreach_fun (tmp196, &depgen_v0aldec_13) ;
break ;

__ats_lab_44:
if (((ats_sum_ptr_type)tmp188)->tag != 24) { goto __ats_lab_45 ; }
tmp199 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_7*)tmp188)->atslab_0 ;
tmp200 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_7*)tmp188)->atslab_1 ;
/* tmp201 = */ depgen_v0aldec_13 (tmp199) ;
/* tmp187 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_list_2esats__list_foreach_fun (tmp200, &depgen_v0aldec_13) ;
break ;

__ats_lab_45:
if (((ats_sum_ptr_type)tmp188)->tag != 25) { goto __ats_lab_46 ; }
tmp203 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_9*)tmp188)->atslab_2 ;
tmp204 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_9*)tmp188)->atslab_3 ;
/* tmp205 = */ depgen_f0undec_14 (tmp203) ;
/* tmp187 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_list_2esats__list_foreach_fun (tmp204, &depgen_f0undec_14) ;
break ;

__ats_lab_46:
if (((ats_sum_ptr_type)tmp188)->tag != 26) { goto __ats_lab_47 ; }
tmp207 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_7*)tmp188)->atslab_0 ;
tmp208 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_7*)tmp188)->atslab_1 ;
/* tmp209 = */ depgen_v0ardec_15 (tmp207) ;
/* tmp187 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_list_2esats__list_foreach_fun (tmp208, &depgen_v0ardec_15) ;
break ;

__ats_lab_47:
if (((ats_sum_ptr_type)tmp188)->tag != 28) { goto __ats_lab_48 ; }
tmp211 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_7*)tmp188)->atslab_1 ;
tmp212 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_rec_17*)tmp211)->atslab_i0mpdec_def ;
/* tmp187 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__depgen_d0exp (tmp212) ;
break ;

__ats_lab_48:
if (((ats_sum_ptr_type)tmp188)->tag != 30) { goto __ats_lab_49 ; }
tmp214 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_7*)tmp188)->atslab_1 ;
tmp215 = atspre_test_file_exists (tmp214) ;
if (tmp215) {
/* tmp187 = */ the_deplst_push_2 (tmp214) ;
} else {
} /* if */
break ;

__ats_lab_49:
if (((ats_sum_ptr_type)tmp188)->tag != 31) { goto __ats_lab_50 ; }
tmp219 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_7*)tmp188)->atslab_0 ;
tmp220 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_7*)tmp188)->atslab_1 ;
/* tmp221 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__depgen_d0eclst (tmp219) ;
/* tmp187 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__depgen_d0eclst (tmp220) ;
break ;

__ats_lab_50:
if (((ats_sum_ptr_type)tmp188)->tag != 32) { goto __ats_lab_51 ; }
tmp223 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_sum_7*)tmp188)->atslab_1 ;
tmp224 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats_rec_18*)tmp223)->atslab_guad0ec_node ;
/* tmp187 = */ depgen_guad0ec_node_16 (tmp224) ;
break ;

__ats_lab_51:
break ;

} while (0) ;
return ;
} /* fun */

ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__depgen_d0eclst (ats_ptr_type arg0) {
ATSlocal_void(tmp226) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__depgen_d0eclst:
/* tmp226 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_list_2esats__list_foreach_fun (arg0, &_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__depgen_d0ec) ;
return ;
} /* fun */

/* static load function */

extern ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_list_2esats__staload () ;
extern ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_reference_2esats__staload () ;
extern ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_reference_2edats__staload () ;
extern ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_filename_2esats__staload () ;
extern ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_parser_2esats__staload () ;
extern ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__staload () ;
extern ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_comarg_2esats__staload () ;
static int _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__staload_flag = 0 ;
ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__staload () {
if (_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__staload_flag) return ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__staload_flag = 1 ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_list_2esats__staload () ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_reference_2esats__staload () ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_reference_2edats__staload () ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_filename_2esats__staload () ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_parser_2esats__staload () ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_2esats__staload () ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_comarg_2esats__staload () ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_lexing_2esats__LexingErrorException.tag = ats_exception_con_tag_new () ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_lexing_2esats__LexingErrorException.name = "_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_lexing_2esats__LexingErrorException" ;
}

/* dynamic load function */

extern int _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__dynload_flag ;
ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__dynload () {
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__dynload_flag = 1 ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_syntax_depgen_2edats__staload () ;
ats_gc_markroot(&tmp0, sizeof(ats_ptr_type)) ;
ats_gc_markroot(&tmp3, sizeof(ats_ptr_type)) ;
tmp3 = (ats_sum_ptr_type)0 ;

tmp0 = _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_reference_2esats__ref_make_elt__ats_ptr_type (tmp3) ;
}

/* external types */

/* external codes at mid */

/* external codes at bot */

