/*
 *
 * This C code is generated by ATS/Geizella
 * The compilation time is: 2012-5-27: 21:24
 *
 */

#define _ATS_GEIZELLA 1

#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"

/* include some .cats files */

#include "prelude/CATS/array.cats"
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/string.cats"

/* external codes at top */

/* type definitions */

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats_sum_0 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats_sum_1 ;

typedef struct {
int tag ;
ats_bool_type atslab_0 ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats_sum_2 ;

typedef struct {
int tag ;
ats_int_type atslab_0 ;
ats_ptr_type atslab_1 ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats_sum_3 ;

typedef struct {
int tag ;
ats_int_type atslab_0 ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats_sum_4 ;

/* external dynamic constructor declarations */

ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__S3AEcst) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__S3AEexp) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__S3AEvar) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__S3AEpadd) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__S3BEcst) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__S3BEexp) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__S3BEvar) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__S3BEbool) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__S3BEbadd) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__S3BEbmul) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__S3BEbneg) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__S3BEiexp) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__S3IEcst) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__S3IEexp) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__S3IEint) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__S3IEintinf) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__S3IEvar) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__S3IEineg) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__S3IEiadd) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__S3IEisub) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__S3IEimul) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__S3IEpdiff) ;

/* external dynamic constant declarations */

extern ats_ptr_type atspre_stdout_get() ;
extern ats_void_type atspre_stdout_view_set() ;
extern ats_ptr_type atspre_stderr_get() ;
extern ats_void_type atspre_stderr_view_set() ;
extern ats_void_type atspre_fprint_bool(ats_ref_type, ats_bool_type) ;
extern ats_void_type atspre_fprint_int(ats_ref_type, ats_int_type) ;
extern ats_void_type atspre_fprint_string(ats_ref_type, ats_ptr_type) ;
extern ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_intinf_2esats__fprint_intinf(ats_ref_type, ats_ptr_type) ;
extern ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_list_2esats__fprintlst(ats_ref_type, ats_ptr_type, ats_ptr_type, ats_ptr_type) ;
extern ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_staexp2_2esats__fprint_s2cst(ats_ref_type, ats_ptr_type) ;
extern ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_staexp2_2esats__fprint_s2var(ats_ref_type, ats_ptr_type) ;
extern ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_staexp2_2esats__fprint_s2exp(ats_ref_type, ats_ptr_type) ;
extern ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__fprint_s3aexp(ats_ref_type, ats_ptr_type) ;
extern ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__fprint_s3bexp(ats_ref_type, ats_ptr_type) ;
extern ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__fprint_s3bexplst(ats_ref_type, ats_ptr_type) ;
extern ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__fprint_s3iexp(ats_ref_type, ats_ptr_type) ;

/* internal function declarations */

/* sum constructor declarations */

/* exception constructor declarations */

ATSglobal(ats_exn_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_lexing_2esats__LexingErrorException) ;

/* global dynamic constant declarations */

/* static temporary variable declarations */

/* function implementations */

ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__fprint_s3aexp (ats_ref_type arg0, ats_ptr_type arg1) {
ATSlocal_void(tmp0) ;
ATSlocal(ats_ptr_type, tmp2) ;
ATSlocal_void(tmp3) ;
ATSlocal_void(tmp4) ;
ATSlocal(ats_ptr_type, tmp6) ;
ATSlocal_void(tmp7) ;
ATSlocal_void(tmp8) ;
ATSlocal(ats_ptr_type, tmp10) ;
ATSlocal_void(tmp11) ;
ATSlocal_void(tmp12) ;
ATSlocal(ats_ptr_type, tmp14) ;
ATSlocal(ats_ptr_type, tmp15) ;
ATSlocal_void(tmp16) ;
ATSlocal_void(tmp17) ;
ATSlocal_void(tmp18) ;
ATSlocal_void(tmp19) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__fprint_s3aexp:
do {
__ats_lab_0:
if (((ats_sum_ptr_type)arg1)->tag != 0) { goto __ats_lab_1 ; }
tmp2 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats_sum_0*)arg1)->atslab_0 ;
/* tmp3 = */ atspre_fprint_string (arg0, "S3AEcst(") ;
/* tmp4 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_staexp2_2esats__fprint_s2cst (arg0, tmp2) ;
/* tmp0 = */ atspre_fprint_string (arg0, ")") ;
break ;

__ats_lab_1:
if (((ats_sum_ptr_type)arg1)->tag != 1) { goto __ats_lab_2 ; }
tmp6 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats_sum_0*)arg1)->atslab_0 ;
/* tmp7 = */ atspre_fprint_string (arg0, "S3AEexp(") ;
/* tmp8 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_staexp2_2esats__fprint_s2exp (arg0, tmp6) ;
/* tmp0 = */ atspre_fprint_string (arg0, ")") ;
break ;

__ats_lab_2:
if (((ats_sum_ptr_type)arg1)->tag != 2) { goto __ats_lab_3 ; }
tmp10 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats_sum_0*)arg1)->atslab_0 ;
/* tmp11 = */ atspre_fprint_string (arg0, "S3AEvar(") ;
/* tmp12 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_staexp2_2esats__fprint_s2var (arg0, tmp10) ;
/* tmp0 = */ atspre_fprint_string (arg0, ")") ;
break ;

__ats_lab_3:
if (((ats_sum_ptr_type)arg1)->tag != 4) { goto __ats_lab_4 ; }
tmp14 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats_sum_1*)arg1)->atslab_0 ;
tmp15 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats_sum_1*)arg1)->atslab_1 ;
/* tmp16 = */ atspre_fprint_string (arg0, "S3AEpadd(") ;
/* tmp17 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__fprint_s3aexp (arg0, tmp14) ;
/* tmp18 = */ atspre_fprint_string (arg0, "; ") ;
/* tmp19 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__fprint_s3iexp (arg0, tmp15) ;
/* tmp0 = */ atspre_fprint_string (arg0, ")") ;
break ;

__ats_lab_4:
/* tmp0 = */ atspre_fprint_string (arg0, "S3AEnull()") ;
break ;

} while (0) ;
return ;
} /* fun */

ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__print_s3aexp (ats_ptr_type arg0) {
ATSlocal_void(tmp21) ;
ATSlocal(ats_ptr_type, tmp22) ;
ATSlocal(ats_ptr_type, tmp23) ;
ATSlocal_void(tmp24) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__print_s3aexp:
tmp22 = atspre_stdout_get () ;
tmp23 = (tmp22) ;
/* tmp24 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__fprint_s3aexp (tmp23, arg0) ;
/* tmp21 = */ atspre_stdout_view_set () ;
return ;
} /* fun */

ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__prerr_s3aexp (ats_ptr_type arg0) {
ATSlocal_void(tmp25) ;
ATSlocal(ats_ptr_type, tmp26) ;
ATSlocal(ats_ptr_type, tmp27) ;
ATSlocal_void(tmp28) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__prerr_s3aexp:
tmp26 = atspre_stderr_get () ;
tmp27 = (tmp26) ;
/* tmp28 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__fprint_s3aexp (tmp27, arg0) ;
/* tmp25 = */ atspre_stderr_view_set () ;
return ;
} /* fun */

ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__fprint_s3bexp (ats_ref_type arg0, ats_ptr_type arg1) {
ATSlocal_void(tmp29) ;
ATSlocal(ats_ptr_type, tmp31) ;
ATSlocal_void(tmp32) ;
ATSlocal_void(tmp33) ;
ATSlocal(ats_ptr_type, tmp35) ;
ATSlocal_void(tmp36) ;
ATSlocal_void(tmp37) ;
ATSlocal(ats_ptr_type, tmp39) ;
ATSlocal_void(tmp40) ;
ATSlocal_void(tmp41) ;
ATSlocal(ats_bool_type, tmp43) ;
ATSlocal_void(tmp44) ;
ATSlocal_void(tmp45) ;
ATSlocal(ats_ptr_type, tmp47) ;
ATSlocal_void(tmp48) ;
ATSlocal_void(tmp49) ;
ATSlocal(ats_ptr_type, tmp51) ;
ATSlocal(ats_ptr_type, tmp52) ;
ATSlocal_void(tmp53) ;
ATSlocal_void(tmp54) ;
ATSlocal_void(tmp55) ;
ATSlocal_void(tmp56) ;
ATSlocal(ats_ptr_type, tmp58) ;
ATSlocal(ats_ptr_type, tmp59) ;
ATSlocal_void(tmp60) ;
ATSlocal_void(tmp61) ;
ATSlocal_void(tmp62) ;
ATSlocal_void(tmp63) ;
ATSlocal(ats_int_type, tmp65) ;
ATSlocal(ats_ptr_type, tmp66) ;
ATSlocal_void(tmp67) ;
ATSlocal_void(tmp68) ;
ATSlocal_void(tmp69) ;
ATSlocal_void(tmp70) ;
ATSlocal_void(tmp71) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__fprint_s3bexp:
do {
__ats_lab_5:
if (((ats_sum_ptr_type)arg1)->tag != 0) { goto __ats_lab_6 ; }
tmp31 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats_sum_0*)arg1)->atslab_0 ;
/* tmp32 = */ atspre_fprint_string (arg0, "S3BEcst(") ;
/* tmp33 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_staexp2_2esats__fprint_s2cst (arg0, tmp31) ;
/* tmp29 = */ atspre_fprint_string (arg0, ")") ;
break ;

__ats_lab_6:
if (((ats_sum_ptr_type)arg1)->tag != 1) { goto __ats_lab_7 ; }
tmp35 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats_sum_0*)arg1)->atslab_0 ;
/* tmp36 = */ atspre_fprint_string (arg0, "S3BEexp(") ;
/* tmp37 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_staexp2_2esats__fprint_s2exp (arg0, tmp35) ;
/* tmp29 = */ atspre_fprint_string (arg0, ")") ;
break ;

__ats_lab_7:
if (((ats_sum_ptr_type)arg1)->tag != 2) { goto __ats_lab_8 ; }
tmp39 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats_sum_0*)arg1)->atslab_0 ;
/* tmp40 = */ atspre_fprint_string (arg0, "S3BEvar(") ;
/* tmp41 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_staexp2_2esats__fprint_s2var (arg0, tmp39) ;
/* tmp29 = */ atspre_fprint_string (arg0, ")") ;
break ;

__ats_lab_8:
if (((ats_sum_ptr_type)arg1)->tag != 3) { goto __ats_lab_9 ; }
tmp43 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats_sum_2*)arg1)->atslab_0 ;
/* tmp44 = */ atspre_fprint_string (arg0, "S3BEbool(") ;
/* tmp45 = */ atspre_fprint_bool (arg0, tmp43) ;
/* tmp29 = */ atspre_fprint_string (arg0, ")") ;
break ;

__ats_lab_9:
if (((ats_sum_ptr_type)arg1)->tag != 6) { goto __ats_lab_10 ; }
tmp47 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats_sum_0*)arg1)->atslab_0 ;
/* tmp48 = */ atspre_fprint_string (arg0, "S3BEbneg(") ;
/* tmp49 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__fprint_s3bexp (arg0, tmp47) ;
/* tmp29 = */ atspre_fprint_string (arg0, ")") ;
break ;

__ats_lab_10:
if (((ats_sum_ptr_type)arg1)->tag != 4) { goto __ats_lab_11 ; }
tmp51 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats_sum_1*)arg1)->atslab_0 ;
tmp52 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats_sum_1*)arg1)->atslab_1 ;
/* tmp53 = */ atspre_fprint_string (arg0, "S3BEbadd(") ;
/* tmp54 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__fprint_s3bexp (arg0, tmp51) ;
/* tmp55 = */ atspre_fprint_string (arg0, "; ") ;
/* tmp56 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__fprint_s3bexp (arg0, tmp52) ;
/* tmp29 = */ atspre_fprint_string (arg0, ")") ;
break ;

__ats_lab_11:
if (((ats_sum_ptr_type)arg1)->tag != 5) { goto __ats_lab_12 ; }
tmp58 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats_sum_1*)arg1)->atslab_0 ;
tmp59 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats_sum_1*)arg1)->atslab_1 ;
/* tmp60 = */ atspre_fprint_string (arg0, "S3BEbmul(") ;
/* tmp61 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__fprint_s3bexp (arg0, tmp58) ;
/* tmp62 = */ atspre_fprint_string (arg0, "; ") ;
/* tmp63 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__fprint_s3bexp (arg0, tmp59) ;
/* tmp29 = */ atspre_fprint_string (arg0, ")") ;
break ;

__ats_lab_12:
tmp65 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats_sum_3*)arg1)->atslab_0 ;
tmp66 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats_sum_3*)arg1)->atslab_1 ;
/* tmp67 = */ atspre_fprint_string (arg0, "S3BEiexp(") ;
/* tmp68 = */ atspre_fprint_string (arg0, "knd=") ;
/* tmp69 = */ atspre_fprint_int (arg0, tmp65) ;
/* tmp70 = */ atspre_fprint_string (arg0, "; ") ;
/* tmp71 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__fprint_s3iexp (arg0, tmp66) ;
/* tmp29 = */ atspre_fprint_string (arg0, ")") ;
break ;

} while (0) ;
return ;
} /* fun */

ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__print_s3bexp (ats_ptr_type arg0) {
ATSlocal_void(tmp72) ;
ATSlocal(ats_ptr_type, tmp73) ;
ATSlocal(ats_ptr_type, tmp74) ;
ATSlocal_void(tmp75) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__print_s3bexp:
tmp73 = atspre_stdout_get () ;
tmp74 = (tmp73) ;
/* tmp75 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__fprint_s3bexp (tmp74, arg0) ;
/* tmp72 = */ atspre_stdout_view_set () ;
return ;
} /* fun */

ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__prerr_s3bexp (ats_ptr_type arg0) {
ATSlocal_void(tmp76) ;
ATSlocal(ats_ptr_type, tmp77) ;
ATSlocal(ats_ptr_type, tmp78) ;
ATSlocal_void(tmp79) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__prerr_s3bexp:
tmp77 = atspre_stderr_get () ;
tmp78 = (tmp77) ;
/* tmp79 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__fprint_s3bexp (tmp78, arg0) ;
/* tmp76 = */ atspre_stderr_view_set () ;
return ;
} /* fun */

ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__fprint_s3bexplst (ats_ref_type arg0, ats_ptr_type arg1) {
ATSlocal_void(tmp80) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__fprint_s3bexplst:
/* tmp80 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_list_2esats__fprintlst (arg0, arg1, ", ", &_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__fprint_s3bexp) ;
return ;
} /* fun */

ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__print_s3bexplst (ats_ptr_type arg0) {
ATSlocal_void(tmp81) ;
ATSlocal(ats_ptr_type, tmp82) ;
ATSlocal(ats_ptr_type, tmp83) ;
ATSlocal_void(tmp84) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__print_s3bexplst:
tmp82 = atspre_stdout_get () ;
tmp83 = (tmp82) ;
/* tmp84 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__fprint_s3bexplst (tmp83, arg0) ;
/* tmp81 = */ atspre_stdout_view_set () ;
return ;
} /* fun */

ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__prerr_s3bexplst (ats_ptr_type arg0) {
ATSlocal_void(tmp85) ;
ATSlocal(ats_ptr_type, tmp86) ;
ATSlocal(ats_ptr_type, tmp87) ;
ATSlocal_void(tmp88) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__prerr_s3bexplst:
tmp86 = atspre_stderr_get () ;
tmp87 = (tmp86) ;
/* tmp88 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__fprint_s3bexplst (tmp87, arg0) ;
/* tmp85 = */ atspre_stderr_view_set () ;
return ;
} /* fun */

ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__fprint_s3iexp (ats_ref_type arg0, ats_ptr_type arg1) {
ATSlocal_void(tmp89) ;
ATSlocal(ats_ptr_type, tmp91) ;
ATSlocal_void(tmp92) ;
ATSlocal_void(tmp93) ;
ATSlocal(ats_ptr_type, tmp95) ;
ATSlocal_void(tmp96) ;
ATSlocal_void(tmp97) ;
ATSlocal(ats_ptr_type, tmp99) ;
ATSlocal_void(tmp100) ;
ATSlocal_void(tmp101) ;
ATSlocal(ats_int_type, tmp103) ;
ATSlocal_void(tmp104) ;
ATSlocal_void(tmp105) ;
ATSlocal(ats_ptr_type, tmp107) ;
ATSlocal_void(tmp108) ;
ATSlocal_void(tmp109) ;
ATSlocal(ats_ptr_type, tmp111) ;
ATSlocal_void(tmp112) ;
ATSlocal_void(tmp113) ;
ATSlocal(ats_ptr_type, tmp115) ;
ATSlocal(ats_ptr_type, tmp116) ;
ATSlocal_void(tmp117) ;
ATSlocal_void(tmp118) ;
ATSlocal_void(tmp119) ;
ATSlocal_void(tmp120) ;
ATSlocal(ats_ptr_type, tmp122) ;
ATSlocal(ats_ptr_type, tmp123) ;
ATSlocal_void(tmp124) ;
ATSlocal_void(tmp125) ;
ATSlocal_void(tmp126) ;
ATSlocal_void(tmp127) ;
ATSlocal(ats_ptr_type, tmp129) ;
ATSlocal(ats_ptr_type, tmp130) ;
ATSlocal_void(tmp131) ;
ATSlocal_void(tmp132) ;
ATSlocal_void(tmp133) ;
ATSlocal_void(tmp134) ;
ATSlocal(ats_ptr_type, tmp136) ;
ATSlocal(ats_ptr_type, tmp137) ;
ATSlocal_void(tmp138) ;
ATSlocal_void(tmp139) ;
ATSlocal_void(tmp140) ;
ATSlocal_void(tmp141) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__fprint_s3iexp:
do {
__ats_lab_13:
if (((ats_sum_ptr_type)arg1)->tag != 0) { goto __ats_lab_14 ; }
tmp91 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats_sum_0*)arg1)->atslab_0 ;
/* tmp92 = */ atspre_fprint_string (arg0, "S3IEcst(") ;
/* tmp93 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_staexp2_2esats__fprint_s2cst (arg0, tmp91) ;
/* tmp89 = */ atspre_fprint_string (arg0, ")") ;
break ;

__ats_lab_14:
if (((ats_sum_ptr_type)arg1)->tag != 1) { goto __ats_lab_15 ; }
tmp95 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats_sum_0*)arg1)->atslab_0 ;
/* tmp96 = */ atspre_fprint_string (arg0, "S3IEexp(") ;
/* tmp97 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_staexp2_2esats__fprint_s2exp (arg0, tmp95) ;
/* tmp89 = */ atspre_fprint_string (arg0, ")") ;
break ;

__ats_lab_15:
if (((ats_sum_ptr_type)arg1)->tag != 4) { goto __ats_lab_16 ; }
tmp99 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats_sum_0*)arg1)->atslab_0 ;
/* tmp100 = */ atspre_fprint_string (arg0, "S3IEvar(") ;
/* tmp101 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_staexp2_2esats__fprint_s2var (arg0, tmp99) ;
/* tmp89 = */ atspre_fprint_string (arg0, ")") ;
break ;

__ats_lab_16:
if (((ats_sum_ptr_type)arg1)->tag != 2) { goto __ats_lab_17 ; }
tmp103 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats_sum_4*)arg1)->atslab_0 ;
/* tmp104 = */ atspre_fprint_string (arg0, "S3IEint(") ;
/* tmp105 = */ atspre_fprint_int (arg0, tmp103) ;
/* tmp89 = */ atspre_fprint_string (arg0, ")") ;
break ;

__ats_lab_17:
if (((ats_sum_ptr_type)arg1)->tag != 3) { goto __ats_lab_18 ; }
tmp107 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats_sum_0*)arg1)->atslab_0 ;
/* tmp108 = */ atspre_fprint_string (arg0, "S3IEintinf(") ;
/* tmp109 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_intinf_2esats__fprint_intinf (arg0, tmp107) ;
/* tmp89 = */ atspre_fprint_string (arg0, ")") ;
break ;

__ats_lab_18:
if (((ats_sum_ptr_type)arg1)->tag != 5) { goto __ats_lab_19 ; }
tmp111 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats_sum_0*)arg1)->atslab_0 ;
/* tmp112 = */ atspre_fprint_string (arg0, "S3IEineg(") ;
/* tmp113 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__fprint_s3iexp (arg0, tmp111) ;
/* tmp89 = */ atspre_fprint_string (arg0, ")") ;
break ;

__ats_lab_19:
if (((ats_sum_ptr_type)arg1)->tag != 6) { goto __ats_lab_20 ; }
tmp115 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats_sum_1*)arg1)->atslab_0 ;
tmp116 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats_sum_1*)arg1)->atslab_1 ;
/* tmp117 = */ atspre_fprint_string (arg0, "S3IEiadd(") ;
/* tmp118 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__fprint_s3iexp (arg0, tmp115) ;
/* tmp119 = */ atspre_fprint_string (arg0, "; ") ;
/* tmp120 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__fprint_s3iexp (arg0, tmp116) ;
/* tmp89 = */ atspre_fprint_string (arg0, ")") ;
break ;

__ats_lab_20:
if (((ats_sum_ptr_type)arg1)->tag != 7) { goto __ats_lab_21 ; }
tmp122 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats_sum_1*)arg1)->atslab_0 ;
tmp123 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats_sum_1*)arg1)->atslab_1 ;
/* tmp124 = */ atspre_fprint_string (arg0, "S3IEisub(") ;
/* tmp125 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__fprint_s3iexp (arg0, tmp122) ;
/* tmp126 = */ atspre_fprint_string (arg0, "; ") ;
/* tmp127 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__fprint_s3iexp (arg0, tmp123) ;
/* tmp89 = */ atspre_fprint_string (arg0, ")") ;
break ;

__ats_lab_21:
if (((ats_sum_ptr_type)arg1)->tag != 8) { goto __ats_lab_22 ; }
tmp129 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats_sum_1*)arg1)->atslab_0 ;
tmp130 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats_sum_1*)arg1)->atslab_1 ;
/* tmp131 = */ atspre_fprint_string (arg0, "S3IEimul(") ;
/* tmp132 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__fprint_s3iexp (arg0, tmp129) ;
/* tmp133 = */ atspre_fprint_string (arg0, "; ") ;
/* tmp134 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__fprint_s3iexp (arg0, tmp130) ;
/* tmp89 = */ atspre_fprint_string (arg0, ")") ;
break ;

__ats_lab_22:
tmp136 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats_sum_1*)arg1)->atslab_0 ;
tmp137 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats_sum_1*)arg1)->atslab_1 ;
/* tmp138 = */ atspre_fprint_string (arg0, "S3IEpdiff(") ;
/* tmp139 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__fprint_s3aexp (arg0, tmp136) ;
/* tmp140 = */ atspre_fprint_string (arg0, "; ") ;
/* tmp141 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__fprint_s3aexp (arg0, tmp137) ;
/* tmp89 = */ atspre_fprint_string (arg0, ")") ;
break ;

} while (0) ;
return ;
} /* fun */

ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__print_s3iexp (ats_ptr_type arg0) {
ATSlocal_void(tmp142) ;
ATSlocal(ats_ptr_type, tmp143) ;
ATSlocal(ats_ptr_type, tmp144) ;
ATSlocal_void(tmp145) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__print_s3iexp:
tmp143 = atspre_stdout_get () ;
tmp144 = (tmp143) ;
/* tmp145 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__fprint_s3iexp (tmp144, arg0) ;
/* tmp142 = */ atspre_stdout_view_set () ;
return ;
} /* fun */

ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__prerr_s3iexp (ats_ptr_type arg0) {
ATSlocal_void(tmp146) ;
ATSlocal(ats_ptr_type, tmp147) ;
ATSlocal(ats_ptr_type, tmp148) ;
ATSlocal_void(tmp149) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__prerr_s3iexp:
tmp147 = atspre_stderr_get () ;
tmp148 = (tmp147) ;
/* tmp149 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__fprint_s3iexp (tmp148, arg0) ;
/* tmp146 = */ atspre_stderr_view_set () ;
return ;
} /* fun */

/* static load function */

extern ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_intinf_2esats__staload () ;
extern ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_list_2esats__staload () ;
extern ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_staexp2_2esats__staload () ;
extern ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__staload () ;
static int _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats__staload_flag = 0 ;
ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats__staload () {
if (_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats__staload_flag) return ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats__staload_flag = 1 ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_intinf_2esats__staload () ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_list_2esats__staload () ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_staexp2_2esats__staload () ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_2esats__staload () ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_lexing_2esats__LexingErrorException.tag = ats_exception_con_tag_new () ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_lexing_2esats__LexingErrorException.name = "_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_lexing_2esats__LexingErrorException" ;
}

/* dynamic load function */

extern int _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats__dynload_flag ;
ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats__dynload () {
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats__dynload_flag = 1 ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_constraint_print_2edats__staload () ;
}

/* external types */

/* external codes at mid */

/* external codes at bot */

