/*
 *
 * This C code is generated by ATS/Geizella
 * The compilation time is: 2012-5-27: 21:24
 *
 */

#define _ATS_GEIZELLA 1

#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"

/* include some .cats files */

#include "prelude/CATS/array.cats"
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/string.cats"

/* external codes at top */

/* type definitions */

typedef struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_0 ;

typedef struct {
ats_int_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_int_type atslab_2 ;
ats_ptr_type atslab_3 ;
ats_ptr_type atslab_4 ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_1 ;

typedef struct {
ats_int_type atslab_0 ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_2 ;

typedef struct {
ats_ptr_type atslab_0 ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_3 ;

typedef struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_int_type atslab_2 ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_4 ;

typedef struct {
ats_ptr_type atslab_branch_lab ;
ats_ptr_type atslab_branch_inss ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_rec_5 ;

typedef struct {
ats_ptr_type atslab_instr_loc ;
ats_ptr_type atslab_instr_node ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_rec_6 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_int_type atslab_1 ;
ats_ptr_type atslab_2 ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_7 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_int_type atslab_1 ;
ats_ptr_type atslab_2 ;
ats_ptr_type atslab_3 ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_8 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
ats_ptr_type atslab_3 ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_9 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_10 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_11 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
ats_ptr_type atslab_3 ;
ats_ptr_type atslab_4 ;
ats_ptr_type atslab_5 ;
ats_ptr_type atslab_6 ;
ats_ptr_type atslab_7 ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_12 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
ats_int_type atslab_3 ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_13 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_14 ;

typedef struct {
ats_int_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
ats_ptr_type atslab_3 ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_15 ;

/* external dynamic constructor declarations */

ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fprelude_2fGEIZELLA_2fbasics_sta_2esats__list_cons) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fprelude_2fGEIZELLA_2fbasics_sta_2esats__list_nil) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fprelude_2fGEIZELLA_2fbasics_sta_2esats__None_vt) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fprelude_2fGEIZELLA_2fbasics_sta_2esats__Some_vt) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_hiexp_2esats__TMPVAROPTsome) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_hiexp_2esats__TMPVAROPTnone) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__INSTRarr_heap) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__INSTRarr_stack) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__INSTRassgn_clo) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__INSTRcall) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__INSTRcond) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__INSTRfunction) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__INSTRload_ptr) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__INSTRload_ptr_offs) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__INSTRload_var) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__INSTRload_var_offs) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__INSTRloop) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__INSTRmove_con) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__INSTRmove_lazy_delay) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__INSTRmove_lazy_force) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__INSTRmove_rec_box) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__INSTRmove_rec_flt) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__INSTRmove_ref) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__INSTRmove_val) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__INSTRraise) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__INSTRselect) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__INSTRselcon) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__INSTRselcon_ptr) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__INSTRswitch) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__INSTRtrywith) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__INSTRvardec) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__TAILJOINLSTcons) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__TAILJOINLSTnil) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_map_lin_2edats__BSTcons) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_map_lin_2edats__BSTnil) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_map_lin_2edats__MAP) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats__ENVcon) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats__ENVcon) ;

/* external dynamic constant declarations */

extern ats_int_type atspre_add_int_int(ats_int_type, ats_int_type) ;
extern ats_bool_type atspre_eq_int_int(ats_int_type, ats_int_type) ;
extern ats_int_type atspre_iadd(ats_int_type, ats_int_type) ;
extern ats_int_type atspre_isub(ats_int_type, ats_int_type) ;
extern ats_bool_type atspre_ilte(ats_int_type, ats_int_type) ;
extern ats_void_type atspre_fprint_string(ats_ref_type, ats_ptr_type) ;
extern ats_ptr_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_map_lin_2esats__map_make(ats_ptr_type) ;
extern ats_int_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__compare_tmpvar_tmpvar(ats_ptr_type, ats_ptr_type) ;
extern ats_ptr_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__tmpvar_get_root(ats_ptr_type) ;
extern ats_ptr_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__tmpvar_get_typ(ats_ptr_type) ;
extern ats_bool_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__tmpvar_is_void(ats_ptr_type) ;
extern ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__emit_tmpvar(ats_ref_type, ats_ptr_type) ;
extern ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__emit_hityp(ats_ref_type, ats_ptr_type) ;
extern ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__instr_tmpvarmap_add(ats_ref_type, ats_ptr_type) ;
extern ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__instrlst_tmpvarmap_add(ats_ref_type, ats_ptr_type) ;
extern ats_ptr_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_env_2esats__funentry_get_ret(ats_ptr_type) ;
extern ats_ptr_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_env_2esats__funentry_get_body(ats_ptr_type) ;
extern ats_bool_type atsopt_map_lin_dice(ats_int_type, ats_int_type) ;
extern ats_void_type atsopt_tmpvar_set_top(ats_ptr_type, ats_int_type) ;

/* internal function declarations */

static ats_void_type tmpvarmap_add_0 (ats_ref_type arg0, ats_ptr_type arg1) ;

static ats_ptr_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_map_lin_2esats__map_search__ats_ptr_type_ats_int_type (ats_ptr_type arg0, ats_ptr_type arg1) ;

static ats_ptr_type bst_search__ats_ptr_type_ats_int_type (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) ;

static ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_map_lin_2esats__map_insert__ats_ptr_type_ats_int_type (ats_ptr_type arg0, ats_ptr_type arg1, ats_int_type arg2) ;

static ats_ptr_type bst_insert_random__ats_ptr_type_ats_int_type (ats_ptr_type arg0, ats_ptr_type arg1, ats_int_type arg2, ats_ptr_type arg3) ;

static ats_ptr_type bst_insert_atroot__ats_ptr_type_ats_int_type (ats_ptr_type arg0, ats_ptr_type arg1, ats_int_type arg2, ats_ptr_type arg3) ;

static ats_int_type bst_size__ats_ptr_type_ats_int_type (ats_ptr_type arg0) ;

static ats_void_type tmpvarmap_add_root_7 (ats_ref_type arg0, ats_ptr_type arg1) ;

static ats_void_type tmpvarmap_addlst_8 (ats_ref_type arg0, ats_ptr_type arg1) ;

static ats_int_type _emit_tmpvarmap_dec_9 (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2) ;

static ats_void_type f_10 (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2) ;

static ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_map_lin_2esats__map_foreach_inf__ats_ptr_type_ats_int_type (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) ;

static ats_void_type bst_foreach_inf__ats_ptr_type_ats_int_type (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) ;

static ats_int_type _emit_tmpvarmap_markroot_13 (ats_ptr_type arg0, ats_ptr_type arg1) ;

static ats_void_type f_14 (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2) ;

static ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_map_lin_2esats__map_free__ats_ptr_type_ats_int_type (ats_ptr_type arg0) ;

static ats_void_type bst_free__ats_ptr_type_ats_int_type (ats_ptr_type arg0) ;

static ats_void_type aux_branchlst_20 (ats_ref_type arg0, ats_ptr_type arg1) ;

static ats_void_type loop_27 (ats_ref_type arg0, ats_ptr_type arg1) ;

/* sum constructor declarations */

ATSglobal(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats__ENVcon) ;
ATSglobal(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats__ENVcon) ;

/* exception constructor declarations */

ATSglobal(ats_exn_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_lexing_2esats__LexingErrorException) ;

/* global dynamic constant declarations */

/* static temporary variable declarations */

/* function implementations */

ats_void_type
tmpvarmap_add_0 (ats_ref_type arg0, ats_ptr_type arg1) {
ATSlocal_void(tmp0) ;
ATSlocal(ats_ptr_type, tmp1) ;
__ats_lab_tmpvarmap_add_0:
tmp1 = _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_map_lin_2esats__map_search__ats_ptr_type_ats_int_type (*((ats_ptr_type*)arg0), arg1) ;
do {
__ats_lab_5:
if (tmp1 == (ats_sum_ptr_type)0) { goto __ats_lab_6 ; }
ATS_FREE(tmp1) ;
break ;

__ats_lab_6:
/* tmp0 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_map_lin_2esats__map_insert__ats_ptr_type_ats_int_type (*((ats_ptr_type*)arg0), arg1, 0) ;
break ;

} while (0) ;
return ;
} /* fun */

ats_ptr_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_map_lin_2esats__map_search__ats_ptr_type_ats_int_type (ats_ptr_type arg0, ats_ptr_type arg1) {
ATSlocal(ats_ptr_type, tmp2) ;
ATSlocal(ats_ptr_type, tmp3) ;
ATSlocal(ats_ptr_type, tmp4) ;
ATSlocal(ats_ptr_type, tmp24) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_map_lin_2esats__map_search__ats_ptr_type_ats_int_type:
tmp3 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_0*)arg0)->atslab_0 ;
tmp4 = &(((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_0*)arg0)->atslab_1) ;
tmp24 = *((ats_ptr_type*)tmp4) ;
tmp2 = bst_search__ats_ptr_type_ats_int_type (tmp24, arg1, tmp3) ;
return tmp2 ;
} /* fun */

ats_ptr_type
bst_search__ats_ptr_type_ats_int_type (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
ATSlocal(ats_ptr_type, tmp5) ;
ATSlocal(ats_ptr_type, tmp7) ;
ATSlocal(ats_int_type, tmp8) ;
ATSlocal(ats_ptr_type, tmp9) ;
ATSlocal(ats_ptr_type, tmp10) ;
ATSlocal(ats_int_type, tmp11) ;
ATSlocal(ats_ptr_type, tmp13) ;
ATSlocal(ats_ptr_type, tmp14) ;
ATSlocal(ats_ptr_type, tmp15) ;
ATSlocal(ats_ptr_type, tmp16) ;
ATSlocal(ats_ptr_type, tmp18) ;
ATSlocal(ats_ptr_type, tmp19) ;
ATSlocal(ats_ptr_type, tmp20) ;
ATSlocal(ats_ptr_type, tmp21) ;
__ats_lab_bst_search__ats_ptr_type_ats_int_type:
do {
__ats_lab_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_1 ; }
tmp7 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_1*)arg0)->atslab_1 ;
tmp8 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_1*)arg0)->atslab_2 ;
tmp9 = &(((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_1*)arg0)->atslab_3) ;
tmp10 = &(((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_1*)arg0)->atslab_4) ;
tmp11 = ((ats_int_type (*)(ats_ptr_type, ats_ptr_type))arg2) (arg1, tmp7) ;
do {
__ats_lab_2:
if (tmp11 != -1) { goto __ats_lab_3 ; }
tmp14 = *((ats_ptr_type*)tmp9) ;
tmp13 = tmp14 ;
tmp15 = arg1 ;
tmp16 = arg2 ;
arg0 = tmp13 ;
arg1 = tmp15 ;
arg2 = tmp16 ;
goto __ats_lab_bst_search__ats_ptr_type_ats_int_type ;
break ;

__ats_lab_3:
if (tmp11 != 1) { goto __ats_lab_4 ; }
tmp19 = *((ats_ptr_type*)tmp10) ;
tmp18 = tmp19 ;
tmp20 = arg1 ;
tmp21 = arg2 ;
arg0 = tmp18 ;
arg1 = tmp20 ;
arg2 = tmp21 ;
goto __ats_lab_bst_search__ats_ptr_type_ats_int_type ;
break ;

__ats_lab_4:
tmp5 = ATS_MALLOC(sizeof(_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_2)) ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_2*)tmp5)->atslab_0 = tmp8 ;

break ;

} while (0) ;
break ;

__ats_lab_1:
tmp5 = (ats_sum_ptr_type)0 ;

break ;

} while (0) ;
return tmp5 ;
} /* fun */

ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_map_lin_2esats__map_insert__ats_ptr_type_ats_int_type (ats_ptr_type arg0, ats_ptr_type arg1, ats_int_type arg2) {
ATSlocal_void(tmp27) ;
ATSlocal(ats_ptr_type, tmp28) ;
ATSlocal(ats_ptr_type, tmp29) ;
ATSlocal(ats_ptr_type, tmp31) ;
ATSlocal(ats_ptr_type, tmp106) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_map_lin_2esats__map_insert__ats_ptr_type_ats_int_type:
tmp28 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_0*)arg0)->atslab_0 ;
tmp29 = &(((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_0*)arg0)->atslab_1) ;
tmp106 = *((ats_ptr_type*)tmp29) ;
tmp31 = bst_insert_random__ats_ptr_type_ats_int_type (tmp106, arg1, arg2, tmp28) ;
*((ats_ptr_type*)tmp29) = tmp31 ;
return ;
} /* fun */

ats_ptr_type
bst_insert_random__ats_ptr_type_ats_int_type (ats_ptr_type arg0, ats_ptr_type arg1, ats_int_type arg2, ats_ptr_type arg3) {
ATSlocal(ats_ptr_type, tmp32) ;
ATSlocal(ats_ptr_type, tmp34) ;
ATSlocal(ats_ptr_type, tmp35) ;
ATSlocal(ats_ptr_type, tmp36) ;
ATSlocal(ats_ptr_type, tmp37) ;
ATSlocal(ats_bool_type, tmp38) ;
ATSlocal(ats_int_type, tmp39) ;
ATSlocal(ats_bool_type, tmp89) ;
ATSlocal(ats_int_type, tmp90) ;
ATSlocal(ats_ptr_type, tmp92) ;
ATSlocal(ats_ptr_type, tmp93) ;
ATSlocal(ats_int_type, tmp95) ;
ATSlocal(ats_int_type, tmp96) ;
ATSlocal(ats_ptr_type, tmp98) ;
ATSlocal(ats_ptr_type, tmp99) ;
ATSlocal(ats_int_type, tmp101) ;
ATSlocal(ats_int_type, tmp102) ;
ATSlocal(ats_ptr_type, tmp104) ;
ATSlocal(ats_ptr_type, tmp105) ;
__ats_lab_bst_insert_random__ats_ptr_type_ats_int_type:
do {
__ats_lab_7:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_8 ; }
tmp34 = &(((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_1*)arg0)->atslab_0) ;
tmp35 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_1*)arg0)->atslab_1 ;
tmp36 = &(((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_1*)arg0)->atslab_3) ;
tmp37 = &(((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_1*)arg0)->atslab_4) ;
tmp39 = *((ats_int_type*)tmp34) ;
tmp38 = atsopt_map_lin_dice (1, tmp39) ;
if (tmp38) {
tmp32 = bst_insert_atroot__ats_ptr_type_ats_int_type (arg0, arg1, arg2, arg3) ;
} else {
tmp90 = ((ats_int_type (*)(ats_ptr_type, ats_ptr_type))arg3) (arg1, tmp35) ;
tmp89 = atspre_ilte (tmp90, 0) ;
if (tmp89) {
tmp93 = *((ats_ptr_type*)tmp36) ;
tmp92 = bst_insert_random__ats_ptr_type_ats_int_type (tmp93, arg1, arg2, arg3) ;
*((ats_ptr_type*)tmp36) = tmp92 ;
tmp96 = *((ats_int_type*)tmp34) ;
tmp95 = atspre_iadd (tmp96, 1) ;
*((ats_int_type*)tmp34) = tmp95 ;
tmp32 = arg0 ;
} else {
tmp99 = *((ats_ptr_type*)tmp37) ;
tmp98 = bst_insert_random__ats_ptr_type_ats_int_type (tmp99, arg1, arg2, arg3) ;
*((ats_ptr_type*)tmp37) = tmp98 ;
tmp102 = *((ats_int_type*)tmp34) ;
tmp101 = atspre_iadd (tmp102, 1) ;
*((ats_int_type*)tmp34) = tmp101 ;
tmp32 = arg0 ;
} /* if */
} /* if */
break ;

__ats_lab_8:
tmp104 = (ats_sum_ptr_type)0 ;

tmp105 = (ats_sum_ptr_type)0 ;

tmp32 = ATS_MALLOC(sizeof(_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_1)) ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_1*)tmp32)->atslab_0 = 1 ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_1*)tmp32)->atslab_1 = arg1 ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_1*)tmp32)->atslab_2 = arg2 ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_1*)tmp32)->atslab_3 = tmp104 ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_1*)tmp32)->atslab_4 = tmp105 ;

break ;

} while (0) ;
return tmp32 ;
} /* fun */

ats_ptr_type
bst_insert_atroot__ats_ptr_type_ats_int_type (ats_ptr_type arg0, ats_ptr_type arg1, ats_int_type arg2, ats_ptr_type arg3) {
ATSlocal(ats_ptr_type, tmp41) ;
ATSlocal(ats_ptr_type, tmp43) ;
ATSlocal(ats_ptr_type, tmp44) ;
ATSlocal(ats_ptr_type, tmp45) ;
ATSlocal(ats_ptr_type, tmp46) ;
ATSlocal(ats_bool_type, tmp47) ;
ATSlocal(ats_int_type, tmp48) ;
ATSlocal(ats_ptr_type, tmp50) ;
ATSlocal(ats_ptr_type, tmp51) ;
ATSlocal(ats_ptr_type, tmp52) ;
ATSlocal(ats_ptr_type, tmp53) ;
ATSlocal(ats_ptr_type, tmp54) ;
ATSlocal(ats_int_type, tmp55) ;
ATSlocal(ats_int_type, tmp56) ;
ATSlocal(ats_ptr_type, tmp61) ;
ATSlocal(ats_ptr_type, tmp63) ;
ATSlocal(ats_int_type, tmp65) ;
ATSlocal(ats_int_type, tmp68) ;
ATSlocal(ats_ptr_type, tmp70) ;
ATSlocal(ats_ptr_type, tmp71) ;
ATSlocal(ats_ptr_type, tmp72) ;
ATSlocal(ats_ptr_type, tmp73) ;
ATSlocal(ats_ptr_type, tmp74) ;
ATSlocal(ats_int_type, tmp75) ;
ATSlocal(ats_int_type, tmp76) ;
ATSlocal(ats_ptr_type, tmp77) ;
ATSlocal(ats_ptr_type, tmp79) ;
ATSlocal(ats_int_type, tmp81) ;
ATSlocal(ats_int_type, tmp84) ;
ATSlocal(ats_ptr_type, tmp86) ;
ATSlocal(ats_ptr_type, tmp87) ;
__ats_lab_bst_insert_atroot__ats_ptr_type_ats_int_type:
do {
__ats_lab_9:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_10 ; }
tmp43 = &(((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_1*)arg0)->atslab_0) ;
tmp44 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_1*)arg0)->atslab_1 ;
tmp45 = &(((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_1*)arg0)->atslab_3) ;
tmp46 = &(((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_1*)arg0)->atslab_4) ;
tmp48 = ((ats_int_type (*)(ats_ptr_type, ats_ptr_type))arg3) (arg1, tmp44) ;
tmp47 = atspre_ilte (tmp48, 0) ;
if (tmp47) {
tmp51 = *((ats_ptr_type*)tmp45) ;
tmp50 = bst_insert_atroot__ats_ptr_type_ats_int_type (tmp51, arg1, arg2, arg3) ;
tmp52 = &(((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_1*)tmp50)->atslab_0) ;
tmp53 = &(((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_1*)tmp50)->atslab_3) ;
tmp54 = &(((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_1*)tmp50)->atslab_4) ;
tmp55 = *((ats_int_type*)tmp43) ;
tmp61 = *((ats_ptr_type*)tmp53) ;
tmp56 = bst_size__ats_ptr_type_ats_int_type (tmp61) ;
tmp63 = *((ats_ptr_type*)tmp54) ;
*((ats_ptr_type*)tmp45) = tmp63 ;
tmp65 = atspre_isub (tmp55, tmp56) ;
*((ats_int_type*)tmp43) = tmp65 ;
*((ats_ptr_type*)tmp54) = arg0 ;
tmp68 = atspre_iadd (tmp55, 1) ;
*((ats_int_type*)tmp52) = tmp68 ;
tmp41 = tmp50 ;
} else {
tmp71 = *((ats_ptr_type*)tmp46) ;
tmp70 = bst_insert_atroot__ats_ptr_type_ats_int_type (tmp71, arg1, arg2, arg3) ;
tmp72 = &(((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_1*)tmp70)->atslab_0) ;
tmp73 = &(((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_1*)tmp70)->atslab_3) ;
tmp74 = &(((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_1*)tmp70)->atslab_4) ;
tmp75 = *((ats_int_type*)tmp43) ;
tmp77 = *((ats_ptr_type*)tmp74) ;
tmp76 = bst_size__ats_ptr_type_ats_int_type (tmp77) ;
tmp79 = *((ats_ptr_type*)tmp73) ;
*((ats_ptr_type*)tmp46) = tmp79 ;
tmp81 = atspre_isub (tmp75, tmp76) ;
*((ats_int_type*)tmp43) = tmp81 ;
*((ats_ptr_type*)tmp73) = arg0 ;
tmp84 = atspre_iadd (tmp75, 1) ;
*((ats_int_type*)tmp72) = tmp84 ;
tmp41 = tmp70 ;
} /* if */
break ;

__ats_lab_10:
tmp86 = (ats_sum_ptr_type)0 ;

tmp87 = (ats_sum_ptr_type)0 ;

tmp41 = ATS_MALLOC(sizeof(_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_1)) ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_1*)tmp41)->atslab_0 = 1 ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_1*)tmp41)->atslab_1 = arg1 ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_1*)tmp41)->atslab_2 = arg2 ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_1*)tmp41)->atslab_3 = tmp86 ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_1*)tmp41)->atslab_4 = tmp87 ;

break ;

} while (0) ;
return tmp41 ;
} /* fun */

ats_int_type
bst_size__ats_ptr_type_ats_int_type (ats_ptr_type arg0) {
ATSlocal(ats_int_type, tmp57) ;
ATSlocal(ats_int_type, tmp59) ;
__ats_lab_bst_size__ats_ptr_type_ats_int_type:
do {
__ats_lab_11:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_12 ; }
tmp59 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_1*)arg0)->atslab_0 ;
tmp57 = tmp59 ;
break ;

__ats_lab_12:
tmp57 = 0 ;
break ;

} while (0) ;
return tmp57 ;
} /* fun */

ats_void_type
tmpvarmap_add_root_7 (ats_ref_type arg0, ats_ptr_type arg1) {
ATSlocal_void(tmp107) ;
ATSlocal(ats_ptr_type, tmp108) ;
ATSlocal(ats_ptr_type, tmp109) ;
ATSlocal(ats_ptr_type, tmp111) ;
ATSlocal(ats_ptr_type, tmp113) ;
__ats_lab_tmpvarmap_add_root_7:
tmp109 = _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__tmpvar_get_root (arg1) ;
do {
__ats_lab_13:
if (tmp109 == (ats_sum_ptr_type)0) { goto __ats_lab_14 ; }
tmp111 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_3*)tmp109)->atslab_0 ;
tmp108 = tmp111 ;
break ;

__ats_lab_14:
tmp108 = arg1 ;
break ;

} while (0) ;
tmp113 = _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_map_lin_2esats__map_search__ats_ptr_type_ats_int_type (*((ats_ptr_type*)arg0), tmp108) ;
do {
__ats_lab_15:
if (tmp113 == (ats_sum_ptr_type)0) { goto __ats_lab_16 ; }
ATS_FREE(tmp113) ;
break ;

__ats_lab_16:
/* tmp107 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_map_lin_2esats__map_insert__ats_ptr_type_ats_int_type (*((ats_ptr_type*)arg0), tmp108, 0) ;
break ;

} while (0) ;
return ;
} /* fun */

ats_void_type
tmpvarmap_addlst_8 (ats_ref_type arg0, ats_ptr_type arg1) {
ATSlocal_void(tmp116) ;
ATSlocal(ats_ptr_type, tmp118) ;
ATSlocal(ats_ptr_type, tmp119) ;
ATSlocal_void(tmp120) ;
ATSlocal(ats_ref_type, tmp121) ;
ATSlocal(ats_ptr_type, tmp122) ;
__ats_lab_tmpvarmap_addlst_8:
do {
__ats_lab_17:
if (arg1 == (ats_sum_ptr_type)0) { goto __ats_lab_18 ; }
tmp118 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_0*)arg1)->atslab_0 ;
tmp119 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_0*)arg1)->atslab_1 ;
/* tmp120 = */ tmpvarmap_add_0 (arg0, tmp118) ;
tmp121 = arg0 ;
tmp122 = tmp119 ;
arg0 = tmp121 ;
arg1 = tmp122 ;
goto __ats_lab_tmpvarmap_addlst_8 ;
break ;

__ats_lab_18:
break ;

} while (0) ;
return ;
} /* fun */

ats_int_type
_emit_tmpvarmap_dec_9 (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2) {
ATSlocal(ats_int_type, tmp124) ;
ATSlocal(ats_int_type, tmp125) ;
ATSlocal(ats_ptr_type, tmp160) ;
ATSlocal_void(tmp161) ;
__ats_lab__emit_tmpvarmap_dec_9:
tmp125 = 0 ;
tmp160 = ATS_MALLOC(sizeof(_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_4)) ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_4*)tmp160)->atslab_0 = arg0 ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_4*)tmp160)->atslab_1 = (&tmp125) ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_4*)tmp160)->atslab_2 = arg1 ;

/* tmp161 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_map_lin_2esats__map_foreach_inf__ats_ptr_type_ats_int_type (arg2, &f_10, tmp160) ;
ATS_FREE(tmp160) ;
tmp124 = tmp125 ;
return tmp124 ;
} /* fun */

ats_void_type
f_10 (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2) {
ATSlocal_void(tmp126) ;
ATSlocal(ats_ptr_type, tmp127) ;
ATSlocal(ats_ptr_type, tmp128) ;
ATSlocal(ats_int_type, tmp129) ;
ATSlocal_void(tmp130) ;
ATSlocal(ats_bool_type, tmp131) ;
ATSlocal(ats_int_type, tmp134) ;
ATSlocal(ats_int_type, tmp135) ;
ATSlocal(ats_bool_type, tmp137) ;
ATSlocal_void(tmp138) ;
ATSlocal(ats_bool_type, tmp139) ;
ATSlocal_void(tmp142) ;
ATSlocal(ats_bool_type, tmp143) ;
ATSlocal_void(tmp146) ;
ATSlocal_void(tmp148) ;
ATSlocal(ats_bool_type, tmp149) ;
ATSlocal_void(tmp152) ;
ATSlocal(ats_bool_type, tmp153) ;
ATSlocal_void(tmp156) ;
ATSlocal(ats_ptr_type, tmp157) ;
ATSlocal_void(tmp158) ;
ATSlocal_void(tmp159) ;
__ats_lab_f_10:
tmp127 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_4*)arg2)->atslab_0 ;
tmp128 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_4*)arg2)->atslab_1 ;
tmp129 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_4*)arg2)->atslab_2 ;
tmp131 = atspre_eq_int_int (tmp129, 1) ;
if (tmp131) {
/* tmp130 = */ atsopt_tmpvar_set_top (arg0, 1) ;
} else {
} /* if */
tmp135 = *((ats_int_type*)tmp128) ;
tmp134 = atspre_add_int_int (tmp135, 1) ;
*((ats_int_type*)tmp128) = tmp134 ;
do {
__ats_lab_19:
tmp137 = _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__tmpvar_is_void (arg0) ;
if (!tmp137) { goto __ats_lab_20 ; }
tmp139 = atspre_eq_int_int (tmp129, 0) ;
if (tmp139) {
/* tmp138 = */ atspre_fprint_string (tmp127, "// ATSlocal_void (") ;
} else {
} /* if */
tmp143 = atspre_eq_int_int (tmp129, 1) ;
if (tmp143) {
/* tmp142 = */ atspre_fprint_string (tmp127, "// ATSstatic_void (") ;
} else {
} /* if */
/* tmp146 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__emit_tmpvar (tmp127, arg0) ;
/* tmp126 = */ atspre_fprint_string (tmp127, ") ;\n") ;
break ;

__ats_lab_20:
tmp149 = atspre_eq_int_int (tmp129, 0) ;
if (tmp149) {
/* tmp148 = */ atspre_fprint_string (tmp127, "ATSlocal (") ;
} else {
} /* if */
tmp153 = atspre_eq_int_int (tmp129, 1) ;
if (tmp153) {
/* tmp152 = */ atspre_fprint_string (tmp127, "ATSstatic (") ;
} else {
} /* if */
tmp157 = _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__tmpvar_get_typ (arg0) ;
/* tmp156 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__emit_hityp (tmp127, tmp157) ;
/* tmp158 = */ atspre_fprint_string (tmp127, ", ") ;
/* tmp159 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__emit_tmpvar (tmp127, arg0) ;
/* tmp126 = */ atspre_fprint_string (tmp127, ") ;\n") ;
break ;

} while (0) ;
return ;
} /* fun */

ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_map_lin_2esats__map_foreach_inf__ats_ptr_type_ats_int_type (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
ATSlocal_void(tmp162) ;
ATSlocal(ats_ptr_type, tmp163) ;
ATSlocal(ats_ptr_type, tmp178) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_map_lin_2esats__map_foreach_inf__ats_ptr_type_ats_int_type:
tmp163 = &(((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_0*)arg0)->atslab_1) ;
tmp178 = *((ats_ptr_type*)tmp163) ;
/* tmp162 = */ bst_foreach_inf__ats_ptr_type_ats_int_type (tmp178, arg1, arg2) ;
return ;
} /* fun */

ats_void_type
bst_foreach_inf__ats_ptr_type_ats_int_type (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
ATSlocal_void(tmp164) ;
ATSlocal(ats_ptr_type, tmp166) ;
ATSlocal(ats_int_type, tmp167) ;
ATSlocal(ats_ptr_type, tmp168) ;
ATSlocal(ats_ptr_type, tmp169) ;
ATSlocal_void(tmp170) ;
ATSlocal(ats_ptr_type, tmp171) ;
ATSlocal_void(tmp172) ;
ATSlocal(ats_ptr_type, tmp173) ;
ATSlocal(ats_ptr_type, tmp174) ;
ATSlocal(ats_ptr_type, tmp175) ;
ATSlocal(ats_ptr_type, tmp176) ;
__ats_lab_bst_foreach_inf__ats_ptr_type_ats_int_type:
do {
__ats_lab_21:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_22 ; }
tmp166 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_1*)arg0)->atslab_1 ;
tmp167 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_1*)arg0)->atslab_2 ;
tmp168 = &(((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_1*)arg0)->atslab_3) ;
tmp169 = &(((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_1*)arg0)->atslab_4) ;
tmp171 = *((ats_ptr_type*)tmp168) ;
/* tmp170 = */ bst_foreach_inf__ats_ptr_type_ats_int_type (tmp171, arg1, arg2) ;
/* tmp172 = */ ((ats_void_type (*)(ats_ptr_type, ats_int_type, ats_ptr_type))arg1) (tmp166, tmp167, arg2) ;
tmp174 = *((ats_ptr_type*)tmp169) ;
tmp173 = tmp174 ;
tmp175 = arg1 ;
tmp176 = arg2 ;
arg0 = tmp173 ;
arg1 = tmp175 ;
arg2 = tmp176 ;
goto __ats_lab_bst_foreach_inf__ats_ptr_type_ats_int_type ;
break ;

__ats_lab_22:
break ;

} while (0) ;
return ;
} /* fun */

ats_int_type
_emit_tmpvarmap_markroot_13 (ats_ptr_type arg0, ats_ptr_type arg1) {
ATSlocal(ats_int_type, tmp179) ;
ATSlocal(ats_int_type, tmp180) ;
ATSlocal(ats_ptr_type, tmp194) ;
ATSlocal_void(tmp195) ;
__ats_lab__emit_tmpvarmap_markroot_13:
tmp180 = 0 ;
tmp194 = ATS_MALLOC(sizeof(_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_0)) ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_0*)tmp194)->atslab_0 = arg0 ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_0*)tmp194)->atslab_1 = (&tmp180) ;

/* tmp195 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_map_lin_2esats__map_foreach_inf__ats_ptr_type_ats_int_type (arg1, &f_14, tmp194) ;
ATS_FREE(tmp194) ;
tmp179 = tmp180 ;
return tmp179 ;
} /* fun */

ats_void_type
f_14 (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2) {
ATSlocal_void(tmp181) ;
ATSlocal(ats_ptr_type, tmp182) ;
ATSlocal(ats_ptr_type, tmp183) ;
ATSlocal(ats_int_type, tmp184) ;
ATSlocal(ats_int_type, tmp185) ;
ATSlocal(ats_bool_type, tmp187) ;
ATSlocal_void(tmp189) ;
ATSlocal_void(tmp190) ;
ATSlocal_void(tmp191) ;
ATSlocal_void(tmp192) ;
ATSlocal(ats_ptr_type, tmp193) ;
__ats_lab_f_14:
tmp182 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_0*)arg2)->atslab_0 ;
tmp183 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_0*)arg2)->atslab_1 ;
tmp185 = *((ats_int_type*)tmp183) ;
tmp184 = atspre_add_int_int (tmp185, 1) ;
*((ats_int_type*)tmp183) = tmp184 ;
do {
__ats_lab_23:
tmp187 = _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__tmpvar_is_void (arg0) ;
if (!tmp187) { goto __ats_lab_24 ; }
break ;

__ats_lab_24:
/* tmp189 = */ atspre_fprint_string (tmp182, "ATS_GC_MARKROOT(&") ;
/* tmp190 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__emit_tmpvar (tmp182, arg0) ;
/* tmp191 = */ atspre_fprint_string (tmp182, ", sizeof(") ;
tmp193 = _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__tmpvar_get_typ (arg0) ;
/* tmp192 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__emit_hityp (tmp182, tmp193) ;
/* tmp181 = */ atspre_fprint_string (tmp182, ")) ;\n") ;
break ;

} while (0) ;
return ;
} /* fun */

ats_ptr_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__tmpvarmap_nil () {
ATSlocal(ats_ptr_type, tmp196) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__tmpvarmap_nil:
tmp196 = _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_map_lin_2esats__map_make ((&_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__compare_tmpvar_tmpvar)) ;
return tmp196 ;
} /* fun */

ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__tmpvarmap_free (ats_ptr_type arg0) {
ATSlocal_void(tmp197) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__tmpvarmap_free:
/* tmp197 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_map_lin_2esats__map_free__ats_ptr_type_ats_int_type (arg0) ;
return ;
} /* fun */

ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_map_lin_2esats__map_free__ats_ptr_type_ats_int_type (ats_ptr_type arg0) {
ATSlocal_void(tmp198) ;
ATSlocal(ats_ptr_type, tmp199) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_map_lin_2esats__map_free__ats_ptr_type_ats_int_type:
tmp199 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_0*)arg0)->atslab_1 ;
ATS_FREE(arg0) ;
/* tmp198 = */ bst_free__ats_ptr_type_ats_int_type (tmp199) ;
return ;
} /* fun */

ats_void_type
bst_free__ats_ptr_type_ats_int_type (ats_ptr_type arg0) {
ATSlocal_void(tmp200) ;
ATSlocal(ats_ptr_type, tmp202) ;
ATSlocal(ats_ptr_type, tmp203) ;
ATSlocal_void(tmp204) ;
ATSlocal(ats_ptr_type, tmp205) ;
__ats_lab_bst_free__ats_ptr_type_ats_int_type:
do {
__ats_lab_25:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_26 ; }
tmp202 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_1*)arg0)->atslab_3 ;
tmp203 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_1*)arg0)->atslab_4 ;
ATS_FREE(arg0) ;
/* tmp204 = */ bst_free__ats_ptr_type_ats_int_type (tmp202) ;
tmp205 = tmp203 ;
arg0 = tmp205 ;
goto __ats_lab_bst_free__ats_ptr_type_ats_int_type ;
break ;

__ats_lab_26:
break ;

} while (0) ;
return ;
} /* fun */

ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__instr_tmpvarmap_add (ats_ref_type arg0, ats_ptr_type arg1) {
ATSlocal_void(tmp207) ;
ATSlocal(ats_ptr_type, tmp217) ;
ATSlocal(ats_ptr_type, tmp219) ;
ATSlocal(ats_ptr_type, tmp221) ;
ATSlocal(ats_ptr_type, tmp223) ;
ATSlocal(ats_ptr_type, tmp225) ;
ATSlocal(ats_ptr_type, tmp227) ;
ATSlocal(ats_ptr_type, tmp228) ;
ATSlocal_void(tmp229) ;
ATSlocal(ats_ptr_type, tmp231) ;
ATSlocal(ats_ptr_type, tmp232) ;
ATSlocal(ats_ptr_type, tmp233) ;
ATSlocal_void(tmp234) ;
ATSlocal_void(tmp235) ;
ATSlocal(ats_ptr_type, tmp237) ;
ATSlocal(ats_ptr_type, tmp239) ;
ATSlocal(ats_ptr_type, tmp241) ;
ATSlocal(ats_ptr_type, tmp243) ;
ATSlocal(ats_ptr_type, tmp245) ;
ATSlocal(ats_ptr_type, tmp246) ;
ATSlocal(ats_ptr_type, tmp247) ;
ATSlocal(ats_ptr_type, tmp248) ;
ATSlocal_void(tmp249) ;
ATSlocal_void(tmp250) ;
ATSlocal_void(tmp251) ;
ATSlocal_void(tmp252) ;
ATSlocal(ats_ptr_type, tmp254) ;
ATSlocal(ats_ptr_type, tmp256) ;
ATSlocal(ats_ptr_type, tmp258) ;
ATSlocal(ats_ptr_type, tmp260) ;
ATSlocal(ats_ptr_type, tmp262) ;
ATSlocal(ats_ptr_type, tmp264) ;
ATSlocal(ats_ptr_type, tmp266) ;
ATSlocal(ats_ptr_type, tmp268) ;
ATSlocal(ats_ptr_type, tmp270) ;
ATSlocal(ats_ptr_type, tmp272) ;
ATSlocal(ats_ptr_type, tmp274) ;
ATSlocal(ats_ptr_type, tmp276) ;
ATSlocal(ats_ptr_type, tmp278) ;
ATSlocal(ats_ptr_type, tmp279) ;
ATSlocal(ats_ptr_type, tmp280) ;
ATSlocal_void(tmp281) ;
ATSlocal_void(tmp282) ;
ATSlocal(ats_ptr_type, tmp284) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__instr_tmpvarmap_add:
tmp217 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_rec_6*)arg1)->atslab_instr_node ;
do {
__ats_lab_29:
if (((ats_sum_ptr_type)tmp217)->tag != 0) { goto __ats_lab_30 ; }
tmp219 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_7*)tmp217)->atslab_0 ;
/* tmp207 = */ tmpvarmap_add_root_7 (arg0, tmp219) ;
break ;

__ats_lab_30:
if (((ats_sum_ptr_type)tmp217)->tag != 1) { goto __ats_lab_31 ; }
tmp221 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_8*)tmp217)->atslab_0 ;
/* tmp207 = */ tmpvarmap_add_root_7 (arg0, tmp221) ;
break ;

__ats_lab_31:
if (((ats_sum_ptr_type)tmp217)->tag != 3) { goto __ats_lab_32 ; }
tmp223 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_9*)tmp217)->atslab_1 ;
/* tmp207 = */ tmpvarmap_add_0 (arg0, tmp223) ;
break ;

__ats_lab_32:
if (((ats_sum_ptr_type)tmp217)->tag != 4) { goto __ats_lab_33 ; }
tmp225 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_9*)tmp217)->atslab_0 ;
/* tmp207 = */ tmpvarmap_add_root_7 (arg0, tmp225) ;
break ;

__ats_lab_33:
if (((ats_sum_ptr_type)tmp217)->tag != 6) { goto __ats_lab_34 ; }
tmp227 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_10*)tmp217)->atslab_1 ;
tmp228 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_10*)tmp217)->atslab_2 ;
/* tmp229 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__instrlst_tmpvarmap_add (arg0, tmp227) ;
/* tmp207 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__instrlst_tmpvarmap_add (arg0, tmp228) ;
break ;

__ats_lab_34:
if (((ats_sum_ptr_type)tmp217)->tag != 14) { goto __ats_lab_35 ; }
tmp231 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_9*)tmp217)->atslab_0 ;
tmp232 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_9*)tmp217)->atslab_2 ;
tmp233 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_9*)tmp217)->atslab_3 ;
/* tmp234 = */ tmpvarmap_add_root_7 (arg0, tmp231) ;
/* tmp235 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__instrlst_tmpvarmap_add (arg0, tmp232) ;
/* tmp207 = */ tmpvarmap_add_root_7 (arg0, tmp233) ;
break ;

__ats_lab_35:
if (((ats_sum_ptr_type)tmp217)->tag != 17) { goto __ats_lab_36 ; }
tmp237 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_11*)tmp217)->atslab_0 ;
/* tmp207 = */ tmpvarmap_add_root_7 (arg0, tmp237) ;
break ;

__ats_lab_36:
if (((ats_sum_ptr_type)tmp217)->tag != 18) { goto __ats_lab_37 ; }
tmp239 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_10*)tmp217)->atslab_0 ;
/* tmp207 = */ tmpvarmap_add_root_7 (arg0, tmp239) ;
break ;

__ats_lab_37:
if (((ats_sum_ptr_type)tmp217)->tag != 19) { goto __ats_lab_38 ; }
tmp241 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_11*)tmp217)->atslab_0 ;
/* tmp207 = */ tmpvarmap_add_root_7 (arg0, tmp241) ;
break ;

__ats_lab_38:
if (((ats_sum_ptr_type)tmp217)->tag != 20) { goto __ats_lab_39 ; }
tmp243 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_10*)tmp217)->atslab_0 ;
/* tmp207 = */ tmpvarmap_add_root_7 (arg0, tmp243) ;
break ;

__ats_lab_39:
if (((ats_sum_ptr_type)tmp217)->tag != 21) { goto __ats_lab_40 ; }
tmp245 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_12*)tmp217)->atslab_3 ;
tmp246 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_12*)tmp217)->atslab_5 ;
tmp247 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_12*)tmp217)->atslab_6 ;
tmp248 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_12*)tmp217)->atslab_7 ;
/* tmp249 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__instrlst_tmpvarmap_add (arg0, tmp245) ;
/* tmp250 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__instrlst_tmpvarmap_add (arg0, tmp246) ;
/* tmp251 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__instrlst_tmpvarmap_add (arg0, tmp247) ;
/* tmp252 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__instrlst_tmpvarmap_add (arg0, tmp248) ;
break ;

__ats_lab_40:
if (((ats_sum_ptr_type)tmp217)->tag != 24) { goto __ats_lab_41 ; }
tmp254 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_9*)tmp217)->atslab_0 ;
/* tmp207 = */ tmpvarmap_add_root_7 (arg0, tmp254) ;
break ;

__ats_lab_41:
if (((ats_sum_ptr_type)tmp217)->tag != 25) { goto __ats_lab_42 ; }
tmp256 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_8*)tmp217)->atslab_0 ;
/* tmp207 = */ tmpvarmap_add_root_7 (arg0, tmp256) ;
break ;

__ats_lab_42:
if (((ats_sum_ptr_type)tmp217)->tag != 26) { goto __ats_lab_43 ; }
tmp258 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_8*)tmp217)->atslab_0 ;
/* tmp207 = */ tmpvarmap_add_root_7 (arg0, tmp258) ;
break ;

__ats_lab_43:
if (((ats_sum_ptr_type)tmp217)->tag != 27) { goto __ats_lab_44 ; }
tmp260 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_10*)tmp217)->atslab_0 ;
/* tmp207 = */ tmpvarmap_add_root_7 (arg0, tmp260) ;
break ;

__ats_lab_44:
if (((ats_sum_ptr_type)tmp217)->tag != 28) { goto __ats_lab_45 ; }
tmp262 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_10*)tmp217)->atslab_0 ;
/* tmp207 = */ tmpvarmap_add_root_7 (arg0, tmp262) ;
break ;

__ats_lab_45:
if (((ats_sum_ptr_type)tmp217)->tag != 29) { goto __ats_lab_46 ; }
tmp264 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_11*)tmp217)->atslab_0 ;
/* tmp207 = */ tmpvarmap_add_root_7 (arg0, tmp264) ;
break ;

__ats_lab_46:
if (((ats_sum_ptr_type)tmp217)->tag != 30) { goto __ats_lab_47 ; }
tmp266 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_11*)tmp217)->atslab_0 ;
/* tmp207 = */ tmpvarmap_add_root_7 (arg0, tmp266) ;
break ;

__ats_lab_47:
if (((ats_sum_ptr_type)tmp217)->tag != 32) { goto __ats_lab_48 ; }
tmp268 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_11*)tmp217)->atslab_0 ;
/* tmp207 = */ tmpvarmap_add_root_7 (arg0, tmp268) ;
break ;

__ats_lab_48:
if (((ats_sum_ptr_type)tmp217)->tag != 33) { goto __ats_lab_49 ; }
tmp270 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_10*)tmp217)->atslab_0 ;
/* tmp207 = */ tmpvarmap_add_root_7 (arg0, tmp270) ;
break ;

__ats_lab_49:
if (((ats_sum_ptr_type)tmp217)->tag != 34) { goto __ats_lab_50 ; }
tmp272 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_13*)tmp217)->atslab_0 ;
/* tmp207 = */ tmpvarmap_add_root_7 (arg0, tmp272) ;
break ;

__ats_lab_50:
if (((ats_sum_ptr_type)tmp217)->tag != 35) { goto __ats_lab_51 ; }
tmp274 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_13*)tmp217)->atslab_0 ;
/* tmp207 = */ tmpvarmap_add_root_7 (arg0, tmp274) ;
break ;

__ats_lab_51:
if (((ats_sum_ptr_type)tmp217)->tag != 36) { goto __ats_lab_52 ; }
tmp276 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_14*)tmp217)->atslab_0 ;
/* tmp207 = */ aux_branchlst_20 (arg0, tmp276) ;
break ;

__ats_lab_52:
if (((ats_sum_ptr_type)tmp217)->tag != 45) { goto __ats_lab_53 ; }
tmp278 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_10*)tmp217)->atslab_0 ;
tmp279 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_10*)tmp217)->atslab_1 ;
tmp280 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_10*)tmp217)->atslab_2 ;
/* tmp281 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__instrlst_tmpvarmap_add (arg0, tmp278) ;
/* tmp282 = */ tmpvarmap_add_root_7 (arg0, tmp279) ;
/* tmp207 = */ aux_branchlst_20 (arg0, tmp280) ;
break ;

__ats_lab_53:
if (((ats_sum_ptr_type)tmp217)->tag != 46) { goto __ats_lab_54 ; }
tmp284 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_14*)tmp217)->atslab_0 ;
/* tmp207 = */ tmpvarmap_add_0 (arg0, tmp284) ;
break ;

__ats_lab_54:
break ;

} while (0) ;
return ;
} /* fun */

ats_void_type
aux_branchlst_20 (ats_ref_type arg0, ats_ptr_type arg1) {
ATSlocal_void(tmp208) ;
ATSlocal(ats_ptr_type, tmp210) ;
ATSlocal(ats_ptr_type, tmp211) ;
ATSlocal_void(tmp212) ;
ATSlocal(ats_ptr_type, tmp213) ;
ATSlocal(ats_ref_type, tmp214) ;
ATSlocal(ats_ptr_type, tmp215) ;
__ats_lab_aux_branchlst_20:
do {
__ats_lab_27:
if (arg1 == (ats_sum_ptr_type)0) { goto __ats_lab_28 ; }
tmp210 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_0*)arg1)->atslab_0 ;
tmp211 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_0*)arg1)->atslab_1 ;
tmp213 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_rec_5*)tmp210)->atslab_branch_inss ;
/* tmp212 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__instrlst_tmpvarmap_add (arg0, tmp213) ;
tmp214 = arg0 ;
tmp215 = tmp211 ;
arg0 = tmp214 ;
arg1 = tmp215 ;
goto __ats_lab_aux_branchlst_20 ;
break ;

__ats_lab_28:
break ;

} while (0) ;
return ;
} /* fun */

ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__instrlst_tmpvarmap_add (ats_ref_type arg0, ats_ptr_type arg1) {
ATSlocal_void(tmp286) ;
ATSlocal(ats_ptr_type, tmp288) ;
ATSlocal(ats_ptr_type, tmp289) ;
ATSlocal_void(tmp290) ;
ATSlocal(ats_ref_type, tmp291) ;
ATSlocal(ats_ptr_type, tmp292) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__instrlst_tmpvarmap_add:
do {
__ats_lab_55:
if (arg1 == (ats_sum_ptr_type)0) { goto __ats_lab_56 ; }
tmp288 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_0*)arg1)->atslab_0 ;
tmp289 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_0*)arg1)->atslab_1 ;
/* tmp290 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__instr_tmpvarmap_add (arg0, tmp288) ;
tmp291 = arg0 ;
tmp292 = tmp289 ;
arg0 = tmp291 ;
arg1 = tmp292 ;
goto __ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__instrlst_tmpvarmap_add ;
break ;

__ats_lab_56:
break ;

} while (0) ;
return ;
} /* fun */

ats_int_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__emit_tmpvarmap_dec_local (ats_ref_type arg0, ats_ptr_type arg1) {
ATSlocal(ats_int_type, tmp294) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__emit_tmpvarmap_dec_local:
tmp294 = _emit_tmpvarmap_dec_9 (arg0, 0, arg1) ;
return tmp294 ;
} /* fun */

ats_int_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__emit_tmpvarmap_dec_static (ats_ref_type arg0, ats_ptr_type arg1) {
ATSlocal(ats_int_type, tmp295) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__emit_tmpvarmap_dec_static:
tmp295 = _emit_tmpvarmap_dec_9 (arg0, 1, arg1) ;
return tmp295 ;
} /* fun */

ats_int_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__emit_tmpvarmap_markroot (ats_ref_type arg0, ats_ptr_type arg1) {
ATSlocal(ats_int_type, tmp296) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__emit_tmpvarmap_markroot:
tmp296 = _emit_tmpvarmap_markroot_13 (arg0, arg1) ;
return tmp296 ;
} /* fun */

ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__funentry_tmpvarmap_add (ats_ref_type arg0, ats_ptr_type arg1) {
ATSlocal_void(tmp297) ;
ATSlocal_void(tmp298) ;
ATSlocal(ats_ptr_type, tmp299) ;
ATSlocal(ats_ptr_type, tmp300) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__funentry_tmpvarmap_add:
tmp299 = _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_env_2esats__funentry_get_body (arg1) ;
/* tmp298 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__instrlst_tmpvarmap_add (arg0, tmp299) ;
tmp300 = _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_env_2esats__funentry_get_ret (arg1) ;
/* tmp297 = */ tmpvarmap_add_root_7 (arg0, tmp300) ;
return ;
} /* fun */

ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__tailjoinlst_tmpvarmap_add (ats_ref_type arg0, ats_ptr_type arg1) {
ATSlocal_void(tmp301) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__tailjoinlst_tmpvarmap_add:
/* tmp301 = */ loop_27 (arg0, arg1) ;
return ;
} /* fun */

ats_void_type
loop_27 (ats_ref_type arg0, ats_ptr_type arg1) {
ATSlocal_void(tmp302) ;
ATSlocal(ats_ptr_type, tmp304) ;
ATSlocal(ats_ptr_type, tmp305) ;
ATSlocal_void(tmp306) ;
ATSlocal(ats_ref_type, tmp307) ;
ATSlocal(ats_ptr_type, tmp308) ;
__ats_lab_loop_27:
do {
__ats_lab_57:
if (arg1 == (ats_sum_ptr_type)0) { goto __ats_lab_58 ; }
tmp304 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_15*)arg1)->atslab_2 ;
tmp305 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats_sum_15*)arg1)->atslab_3 ;
/* tmp306 = */ tmpvarmap_addlst_8 (arg0, tmp304) ;
tmp307 = arg0 ;
tmp308 = tmp305 ;
arg0 = tmp307 ;
arg1 = tmp308 ;
goto __ats_lab_loop_27 ;
break ;

__ats_lab_58:
break ;

} while (0) ;
return ;
} /* fun */

/* static load function */

extern ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_map_lin_2esats__staload () ;
extern ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_hiexp_2esats__staload () ;
extern ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__staload () ;
extern ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_env_2esats__staload () ;
extern ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_map_lin_2edats__staload () ;
static int _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats__staload_flag = 0 ;
ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats__staload () {
if (_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats__staload_flag) return ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats__staload_flag = 1 ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_map_lin_2esats__staload () ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_hiexp_2esats__staload () ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_2esats__staload () ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_env_2esats__staload () ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_map_lin_2edats__staload () ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats__ENVcon.tag = 0 ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats__ENVcon.tag = 0 ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_lexing_2esats__LexingErrorException.tag = ats_exception_con_tag_new () ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_lexing_2esats__LexingErrorException.name = "_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_lexing_2esats__LexingErrorException" ;
}

/* dynamic load function */

extern int _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats__dynload_flag ;
ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats__dynload () {
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats__dynload_flag = 1 ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_ccomp_util_2edats__staload () ;
}

/* external types */

/* external codes at mid */

/* external codes at bot */

