/*
 *
 * This C code is generated by ATS/Geizella
 * The compilation time is: 2012-5-27: 21:24
 *
 */

#define _ATS_GEIZELLA 1

#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"

/* include some .cats files */

#include "prelude/CATS/array.cats"
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/string.cats"

/* external codes at top */

/* type definitions */

typedef struct {
ats_ptr_type atslab_stbefitem_var ;
ats_int_type atslab_stbefitem_lin ;
ats_ptr_type atslab_stbefitem_typ ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_0 ;

typedef struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_2 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_3 ;

typedef struct {
ats_ptr_type atslab_sascstr_loc ;
ats_ptr_type atslab_sascstr_met ;
ats_ptr_type atslab_sascstr_sub ;
ats_ptr_type atslab_sascstr_ref ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_4 ;

typedef struct {
ats_ptr_type atslab_staftitem_var ;
ats_int_type atslab_staftitem_lin ;
ats_ptr_type atslab_staftitem_typ ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_5 ;

typedef struct {
ats_ptr_type atslab_staftscstr_met ;
ats_ptr_type atslab_staftscstr_res ;
ats_ptr_type atslab_staftscstr_sais ;
ats_ptr_type atslab_staftscstr_cstr ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_6 ;

typedef struct {
ats_ptr_type atslab_0 ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_7 ;

typedef struct {
ats_ptr_type atslab_i2nvresstate_svs ;
ats_ptr_type atslab_i2nvresstate_gua ;
ats_ptr_type atslab_i2nvresstate_arg ;
ats_ptr_type atslab_i2nvresstate_met ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_8 ;

typedef struct {
ats_ptr_type atslab_i2nvarg_var ;
ats_ptr_type atslab_i2nvarg_typ ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_9 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_10 ;

/* external dynamic constructor declarations */

ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fprelude_2fGEIZELLA_2fbasics_sta_2esats__list_cons) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fprelude_2fGEIZELLA_2fbasics_sta_2esats__list_nil) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fprelude_2fGEIZELLA_2fbasics_sta_2esats__None) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fprelude_2fGEIZELLA_2fbasics_sta_2esats__Some) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fprelude_2fGEIZELLA_2fbasics_sta_2esats__None_vt) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fprelude_2fGEIZELLA_2fbasics_sta_2esats__Some_vt) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_dynexp2_2esats__D2VARFINdone) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__C3STRKINDmain) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__C3STRKINDvarfin) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats__SAITYPsome) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats__SAITYPnone) ;

/* external dynamic constant declarations */

extern ats_void_type atspre_assert(ats_bool_type) ;
extern ats_void_type atspre_prerr_newline() ;
extern ats_int_type atspre_add_int_int(ats_int_type, ats_int_type) ;
extern ats_int_type atspre_sub_int_int(ats_int_type, ats_int_type) ;
extern ats_bool_type atspre_gt_int_int(ats_int_type, ats_int_type) ;
extern ats_bool_type atspre_ieq(ats_int_type, ats_int_type) ;
extern ats_bool_type atspre_ineq(ats_int_type, ats_int_type) ;
extern ats_void_type atspre_print_string(ats_ptr_type) ;
extern ats_void_type atspre_prerr_string(ats_ptr_type) ;
extern ats_bool_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_location_2esats__lte_location_location(ats_ptr_type, ats_ptr_type) ;
extern ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_location_2esats__prerr_location(ats_ptr_type) ;
extern ats_var_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_error_2esats__abort() ;
extern ats_int_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_list_2esats__list_length_compare(ats_ptr_type, ats_ptr_type) ;
extern ats_ptr_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_list_2esats__list_vt_reverse_list(ats_ptr_type) ;
extern ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_staexp2_2esats__print_s2exp(ats_ptr_type) ;
extern ats_ptr_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_staexp2_2esats__s2exp_subst(ats_ptr_type, ats_ptr_type) ;
extern ats_ptr_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_staexp2_2esats__s2explst_subst(ats_ptr_type, ats_ptr_type) ;
extern ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_staexp2_solve_2esats__s2exp_tyleq_solve(ats_ptr_type, ats_ptr_type, ats_ptr_type) ;
extern ats_int_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_dynexp2_2esats__d2var_get_lin(ats_ptr_type) ;
extern ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_dynexp2_2esats__d2var_set_lin(ats_ptr_type, ats_int_type) ;
extern ats_ptr_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_dynexp2_2esats__d2var_get_fin(ats_ptr_type) ;
extern ats_ptr_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_dynexp2_2esats__d2var_get_typ(ats_ptr_type) ;
extern ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_dynexp2_2esats__d2var_set_typ(ats_ptr_type, ats_ptr_type) ;
extern ats_ptr_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_dynexp2_2esats__d2var_get_mastyp(ats_ptr_type) ;
extern ats_bool_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_dynexp2_2esats__eq_d2var_d2var(ats_ptr_type, ats_ptr_type) ;
extern ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_dynexp2_2esats__prerr_d2var(ats_ptr_type) ;
extern ats_ptr_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__c3str_itmlst(ats_ptr_type, ats_ptr_type, ats_ptr_type) ;
extern ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__trans3_env_add_svarlst(ats_ptr_type) ;
extern ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__trans3_env_add_cstr_ref(ats_ptr_type) ;
extern ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__trans3_env_hypo_add_proplst(ats_ptr_type, ats_ptr_type) ;
extern ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__trans3_env_add_metric_dec(ats_ptr_type, ats_ptr_type, ats_ptr_type) ;
extern ats_ptr_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__s2qua_instantiate_and_add(ats_ptr_type, ats_ptr_type, ats_ptr_type) ;
extern ats_ptr_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__s2expopt_opnexi_and_add(ats_ptr_type, ats_ptr_type) ;
extern ats_ptr_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__trans3_env_pop_sta() ;
extern ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__trans3_env_pop_sta_and_add(ats_ptr_type, ats_ptr_type) ;
extern ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__trans3_env_push_sta() ;
extern ats_ptr_type atspre_ref_make_elt_tsz(ats_ref_type, ats_size_type) ;
extern ats_void_type atsopt_state_staftitem_set_lin(ats_ptr_type, ats_int_type) ;
extern ats_void_type atsopt_state_staftitem_set_typ(ats_ptr_type, ats_ptr_type) ;
extern ats_void_type atsopt_state_staftscstr_cstr_set(ats_ptr_type, ats_ptr_type) ;

/* internal function declarations */

static ats_void_type prerr_interror_0 () ;

static ats_void_type loop_3 (ats_ptr_type arg0) ;

static ats_void_type loop_5 (ats_ptr_type arg0) ;

static ats_ptr_type saityp_get_loc_6 (ats_ptr_type arg0) ;

static ats_void_type print_saityp_7 (ats_ptr_type arg0) ;

static ats_void_type print_saityplst_8 (ats_ptr_type arg0) ;

static ats_void_type loop_9 (ats_ptr_type arg0, ats_int_type arg1) ;

static ats_int_type saityplst_check_10 (ats_ptr_type arg0, ats_ptr_type arg1) ;

static ats_void_type errmsg_11 (ats_ptr_type arg0, ats_ptr_type arg1) ;

static ats_void_type aux_12 (ats_ptr_type arg0, ats_ref_type arg1, ats_ref_type arg2) ;

static ats_ptr_type sascstr_make_13 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_ptr_type arg3) ;

static ats_ptr_type aux_15 (ats_ptr_type arg0) ;

static ats_void_type staftscstr_stbefitemlst_merge_ifmetck_16 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_bool_type arg3) ;

static ats_void_type aux_17 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) ;

static ats_void_type auxlst_18 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) ;

static ats_ptr_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_reference_2esats__ref_make_elt__ats_ptr_type (ats_ptr_type arg0) ;

static ats_ptr_type i2nvarglst_find_d2var_22 (ats_ptr_type arg0, ats_ptr_type arg1) ;

static ats_bool_type d2var_is_done_23 (ats_ptr_type arg0) ;

static ats_ptr_type aux_find_24 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) ;

static ats_ptr_type aux_item_errmsg1_25 (ats_ptr_type arg0, ats_ptr_type arg1) ;

static ats_void_type aux_item_errmsg2_26 (ats_ptr_type arg0, ats_ptr_type arg1) ;

static ats_void_type aux_saityp_27 (ats_int_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_ptr_type arg3, ats_ptr_type arg4) ;

static ats_void_type aux_item_one_28 (ats_int_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_ptr_type arg3, ats_ptr_type arg4) ;

static ats_void_type aux_item_all_29 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_ptr_type arg3) ;

static ats_void_type aux_term_check_30 (ats_ptr_type arg0, ats_ptr_type arg1) ;

static ats_void_type aux_itemlst_all_31 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_ptr_type arg3, ats_ptr_type arg4) ;

static ats_ptr_type aux_find_33 (ats_ptr_type arg0, ats_ptr_type arg1) ;

static ats_void_type aux_iter_34 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_ptr_type arg3) ;

/* sum constructor declarations */

ATSglobal(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats__SAITYPsome) ;
ATSglobal(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats__SAITYPnone) ;

/* exception constructor declarations */

ATSglobal(ats_exn_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_lexing_2esats__LexingErrorException) ;
ATSglobal(ats_exn_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_error_2esats__FatalErrorException) ;
ATSglobal(ats_exn_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_error_2esats__DeadCodeException) ;

/* global dynamic constant declarations */

/* static temporary variable declarations */

/* function implementations */

ats_void_type
prerr_interror_0 () {
ATSlocal_void(tmp0) ;
__ats_lab_prerr_interror_0:
/* tmp0 = */ atspre_prerr_string ("INTERNAL ERROR (ats_trans3_env_state)") ;
return ;
} /* fun */

ats_ptr_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__stbefitem_make (ats_ptr_type arg0, ats_int_type arg1) {
ATSlocal(ats_ptr_type, tmp1) ;
ATSlocal(ats_ptr_type, tmp2) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__stbefitem_make:
tmp2 = _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_dynexp2_2esats__d2var_get_typ (arg0) ;
tmp1 = ATS_MALLOC(sizeof(_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_0)) ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_0*)tmp1)->atslab_stbefitem_var = arg0 ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_0*)tmp1)->atslab_stbefitem_lin = arg1 ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_0*)tmp1)->atslab_stbefitem_typ = tmp2 ;

return tmp1 ;
} /* fun */

ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__stbefitemlst_restore_typ (ats_ptr_type arg0) {
ATSlocal_void(tmp3) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__stbefitemlst_restore_typ:
/* tmp3 = */ loop_3 (arg0) ;
return ;
} /* fun */

ats_void_type
loop_3 (ats_ptr_type arg0) {
ATSlocal_void(tmp4) ;
ATSlocal(ats_ptr_type, tmp6) ;
ATSlocal(ats_ptr_type, tmp7) ;
ATSlocal(ats_ptr_type, tmp8) ;
ATSlocal_void(tmp9) ;
ATSlocal(ats_ptr_type, tmp10) ;
ATSlocal(ats_ptr_type, tmp11) ;
__ats_lab_loop_3:
do {
__ats_lab_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_1 ; }
tmp6 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1*)arg0)->atslab_0 ;
tmp7 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1*)arg0)->atslab_1 ;
tmp8 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_0*)tmp6)->atslab_stbefitem_var ;
tmp10 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_0*)tmp6)->atslab_stbefitem_typ ;
/* tmp9 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_dynexp2_2esats__d2var_set_typ (tmp8, tmp10) ;
tmp11 = tmp7 ;
arg0 = tmp11 ;
goto __ats_lab_loop_3 ;
break ;

__ats_lab_1:
break ;

} while (0) ;
return ;
} /* fun */

ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__stbefitemlst_restore_lin_typ (ats_ptr_type arg0) {
ATSlocal_void(tmp13) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__stbefitemlst_restore_lin_typ:
/* tmp13 = */ loop_5 (arg0) ;
return ;
} /* fun */

ats_void_type
loop_5 (ats_ptr_type arg0) {
ATSlocal_void(tmp14) ;
ATSlocal(ats_ptr_type, tmp16) ;
ATSlocal(ats_ptr_type, tmp17) ;
ATSlocal(ats_ptr_type, tmp18) ;
ATSlocal_void(tmp19) ;
ATSlocal(ats_int_type, tmp20) ;
ATSlocal_void(tmp21) ;
ATSlocal(ats_ptr_type, tmp22) ;
ATSlocal(ats_ptr_type, tmp23) ;
__ats_lab_loop_5:
do {
__ats_lab_2:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_3 ; }
tmp16 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1*)arg0)->atslab_0 ;
tmp17 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1*)arg0)->atslab_1 ;
tmp18 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_0*)tmp16)->atslab_stbefitem_var ;
tmp20 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_0*)tmp16)->atslab_stbefitem_lin ;
/* tmp19 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_dynexp2_2esats__d2var_set_lin (tmp18, tmp20) ;
tmp22 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_0*)tmp16)->atslab_stbefitem_typ ;
/* tmp21 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_dynexp2_2esats__d2var_set_typ (tmp18, tmp22) ;
tmp23 = tmp17 ;
arg0 = tmp23 ;
goto __ats_lab_loop_5 ;
break ;

__ats_lab_3:
break ;

} while (0) ;
return ;
} /* fun */

ats_ptr_type
saityp_get_loc_6 (ats_ptr_type arg0) {
ATSlocal(ats_ptr_type, tmp25) ;
ATSlocal(ats_ptr_type, tmp27) ;
ATSlocal(ats_ptr_type, tmp29) ;
__ats_lab_saityp_get_loc_6:
do {
__ats_lab_4:
if (((ats_sum_ptr_type)arg0)->tag != 0) { goto __ats_lab_5 ; }
tmp27 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_2*)arg0)->atslab_0 ;
tmp25 = tmp27 ;
break ;

__ats_lab_5:
tmp29 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_3*)arg0)->atslab_0 ;
tmp25 = tmp29 ;
break ;

} while (0) ;
return tmp25 ;
} /* fun */

ats_void_type
print_saityp_7 (ats_ptr_type arg0) {
ATSlocal_void(tmp30) ;
ATSlocal(ats_ptr_type, tmp32) ;
ATSlocal_void(tmp33) ;
ATSlocal_void(tmp34) ;
__ats_lab_print_saityp_7:
do {
__ats_lab_6:
if (((ats_sum_ptr_type)arg0)->tag != 0) { goto __ats_lab_7 ; }
tmp32 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_2*)arg0)->atslab_1 ;
/* tmp33 = */ atspre_print_string ("SAITYPsome(") ;
/* tmp34 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_staexp2_2esats__print_s2exp (tmp32) ;
/* tmp30 = */ atspre_print_string (")") ;
break ;

__ats_lab_7:
/* tmp30 = */ atspre_print_string ("SAITYPnone()") ;
break ;

} while (0) ;
return ;
} /* fun */

ats_void_type
print_saityplst_8 (ats_ptr_type arg0) {
ATSlocal_void(tmp36) ;
__ats_lab_print_saityplst_8:
/* tmp36 = */ loop_9 (arg0, 0) ;
return ;
} /* fun */

ats_void_type
loop_9 (ats_ptr_type arg0, ats_int_type arg1) {
ATSlocal_void(tmp37) ;
ATSlocal(ats_ptr_type, tmp39) ;
ATSlocal(ats_ptr_type, tmp40) ;
ATSlocal_void(tmp41) ;
ATSlocal(ats_bool_type, tmp42) ;
ATSlocal_void(tmp45) ;
ATSlocal(ats_ptr_type, tmp46) ;
ATSlocal(ats_int_type, tmp47) ;
__ats_lab_loop_9:
do {
__ats_lab_8:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_9 ; }
tmp39 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1*)arg0)->atslab_0 ;
tmp40 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1*)arg0)->atslab_1 ;
tmp42 = atspre_gt_int_int (arg1, 0) ;
if (tmp42) {
/* tmp41 = */ atspre_print_string (", ") ;
} else {
} /* if */
/* tmp45 = */ print_saityp_7 (tmp39) ;
tmp46 = tmp40 ;
tmp47 = atspre_add_int_int (arg1, 1) ;
arg0 = tmp46 ;
arg1 = tmp47 ;
goto __ats_lab_loop_9 ;
break ;

__ats_lab_9:
break ;

} while (0) ;
return ;
} /* fun */

ats_int_type
saityplst_check_10 (ats_ptr_type arg0, ats_ptr_type arg1) {
ATSlocal(ats_int_type, tmp49) ;
ATSlocal(ats_ptr_type, tmp71) ;
ATSlocal(ats_ptr_type, tmp72) ;
ATSlocal_void(tmp73) ;
ATSlocal(ats_ptr_type, tmp77) ;
ATSlocal(ats_ptr_type, tmp78) ;
ATSlocal(ats_ptr_type, tmp79) ;
ATSlocal(ats_ptr_type, tmp80) ;
ATSlocal(ats_bool_type, tmp81) ;
ATSlocal_void(tmp83) ;
ATSlocal_void(tmp84) ;
ATSlocal_void(tmp86) ;
ATSlocal_void(tmp87) ;
__ats_lab_saityplst_check_10:
tmp71 = (ats_sum_ptr_type)0 ;

tmp72 = (ats_sum_ptr_type)0 ;

/* tmp73 = */ aux_12 (arg1, (&tmp71), (&tmp72)) ;
do {
__ats_lab_16:
if (tmp71 != (ats_sum_ptr_type)0) { goto __ats_lab_17 ; }
tmp49 = 0 ;
break ;

__ats_lab_17:
if (tmp72 != (ats_sum_ptr_type)0) { goto __ats_lab_18 ; }
tmp49 = 1 ;
break ;

__ats_lab_18:
tmp77 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1*)tmp71)->atslab_0 ;
tmp78 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1*)tmp72)->atslab_0 ;
tmp79 = saityp_get_loc_6 (tmp77) ;
tmp80 = saityp_get_loc_6 (tmp78) ;
tmp81 = _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_location_2esats__lte_location_location (tmp79, tmp80) ;
if (tmp81) {
/* tmp83 = */ errmsg_11 (arg0, tmp77) ;
/* tmp84 = */ errmsg_11 (arg0, tmp78) ;
/* tmp49 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_error_2esats__abort () ;
} else {
/* tmp86 = */ errmsg_11 (arg0, tmp78) ;
/* tmp87 = */ errmsg_11 (arg0, tmp77) ;
/* tmp49 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_error_2esats__abort () ;
} /* if */
break ;

} while (0) ;
return tmp49 ;
} /* fun */

ats_void_type
errmsg_11 (ats_ptr_type arg0, ats_ptr_type arg1) {
ATSlocal_void(tmp50) ;
ATSlocal(ats_ptr_type, tmp52) ;
ATSlocal_void(tmp53) ;
ATSlocal_void(tmp54) ;
ATSlocal_void(tmp55) ;
ATSlocal_void(tmp56) ;
ATSlocal(ats_ptr_type, tmp58) ;
ATSlocal_void(tmp59) ;
ATSlocal_void(tmp60) ;
ATSlocal_void(tmp61) ;
ATSlocal_void(tmp62) ;
__ats_lab_errmsg_11:
do {
__ats_lab_10:
if (((ats_sum_ptr_type)arg1)->tag != 0) { goto __ats_lab_11 ; }
tmp52 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_2*)arg1)->atslab_0 ;
/* tmp53 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_location_2esats__prerr_location (tmp52) ;
/* tmp54 = */ atspre_prerr_string (": the dynamic variable [") ;
/* tmp55 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_dynexp2_2esats__prerr_d2var (arg0) ;
/* tmp56 = */ atspre_prerr_string ("] is not consumed in this branch.") ;
/* tmp50 = */ atspre_prerr_newline () ;
break ;

__ats_lab_11:
tmp58 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_3*)arg1)->atslab_0 ;
/* tmp59 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_location_2esats__prerr_location (tmp58) ;
/* tmp60 = */ atspre_prerr_string (": the dynamic variable [") ;
/* tmp61 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_dynexp2_2esats__prerr_d2var (arg0) ;
/* tmp62 = */ atspre_prerr_string ("] is consumed in this branch.") ;
/* tmp50 = */ atspre_prerr_newline () ;
break ;

} while (0) ;
return ;
} /* fun */

ats_void_type
aux_12 (ats_ptr_type arg0, ats_ref_type arg1, ats_ref_type arg2) {
ATSlocal_void(tmp63) ;
ATSlocal(ats_ptr_type, tmp65) ;
ATSlocal(ats_ptr_type, tmp67) ;
ATSlocal(ats_ptr_type, tmp69) ;
__ats_lab_aux_12:
do {
__ats_lab_12:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_13 ; }
tmp65 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1*)arg0)->atslab_0 ;
do {
__ats_lab_14:
if (((ats_sum_ptr_type)tmp65)->tag != 0) { goto __ats_lab_15 ; }
tmp67 = ATS_MALLOC(sizeof(_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1)) ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1*)tmp67)->atslab_0 = tmp65 ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1*)tmp67)->atslab_1 = *((ats_ptr_type*)arg1) ;

*((ats_ptr_type*)arg1) = tmp67 ;
break ;

__ats_lab_15:
tmp69 = ATS_MALLOC(sizeof(_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1)) ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1*)tmp69)->atslab_0 = tmp65 ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1*)tmp69)->atslab_1 = *((ats_ptr_type*)arg2) ;

*((ats_ptr_type*)arg2) = tmp69 ;
break ;

} while (0) ;
break ;

__ats_lab_13:
break ;

} while (0) ;
return ;
} /* fun */

ats_ptr_type
sascstr_make_13 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_ptr_type arg3) {
ATSlocal(ats_ptr_type, tmp88) ;
__ats_lab_sascstr_make_13:
tmp88 = ATS_MALLOC(sizeof(_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_4)) ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_4*)tmp88)->atslab_sascstr_loc = arg0 ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_4*)tmp88)->atslab_sascstr_met = arg1 ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_4*)tmp88)->atslab_sascstr_sub = arg2 ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_4*)tmp88)->atslab_sascstr_ref = arg3 ;

return tmp88 ;
} /* fun */

ats_ptr_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__staftscstr_initialize (ats_ptr_type arg0, ats_ptr_type arg1) {
ATSlocal(ats_ptr_type, tmp89) ;
ATSlocal(ats_ptr_type, tmp90) ;
ATSlocal(ats_ptr_type, tmp101) ;
ATSlocal(ats_ptr_type, tmp102) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__staftscstr_initialize:
tmp90 = aux_15 (arg1) ;
tmp101 = (ats_sum_ptr_type)0 ;

tmp102 = (ats_sum_ptr_type)0 ;

tmp89 = ATS_MALLOC(sizeof(_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_6)) ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_6*)tmp89)->atslab_staftscstr_met = tmp101 ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_6*)tmp89)->atslab_staftscstr_res = arg0 ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_6*)tmp89)->atslab_staftscstr_sais = tmp90 ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_6*)tmp89)->atslab_staftscstr_cstr = tmp102 ;

return tmp89 ;
} /* fun */

ats_ptr_type
aux_15 (ats_ptr_type arg0) {
ATSlocal(ats_ptr_type, tmp91) ;
ATSlocal(ats_ptr_type, tmp93) ;
ATSlocal(ats_ptr_type, tmp94) ;
ATSlocal(ats_ptr_type, tmp95) ;
ATSlocal(ats_int_type, tmp96) ;
ATSlocal(ats_ptr_type, tmp97) ;
ATSlocal(ats_ptr_type, tmp98) ;
ATSlocal(ats_ptr_type, tmp99) ;
__ats_lab_aux_15:
do {
__ats_lab_19:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_20 ; }
tmp93 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1*)arg0)->atslab_0 ;
tmp94 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1*)arg0)->atslab_1 ;
tmp95 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_0*)tmp93)->atslab_stbefitem_var ;
tmp96 = _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_dynexp2_2esats__d2var_get_lin (tmp95) ;
tmp98 = (ats_sum_ptr_type)0 ;

tmp97 = ATS_MALLOC(sizeof(_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_5)) ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_5*)tmp97)->atslab_staftitem_var = tmp95 ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_5*)tmp97)->atslab_staftitem_lin = tmp96 ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_5*)tmp97)->atslab_staftitem_typ = tmp98 ;

tmp99 = aux_15 (tmp94) ;
tmp91 = ATS_MALLOC(sizeof(_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1)) ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1*)tmp91)->atslab_0 = tmp97 ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1*)tmp91)->atslab_1 = tmp99 ;

break ;

__ats_lab_20:
tmp91 = (ats_sum_ptr_type)0 ;

break ;

} while (0) ;
return tmp91 ;
} /* fun */

ats_void_type
staftscstr_stbefitemlst_merge_ifmetck_16 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_bool_type arg3) {
ATSlocal_void(tmp103) ;
ATSlocal(ats_ptr_type, tmp154) ;
ATSlocal(ats_ptr_type, tmp155) ;
ATSlocal(ats_ptr_type, tmp156) ;
ATSlocal(ats_ptr_type, tmp157) ;
ATSlocal(ats_ptr_type, tmp158) ;
ATSlocal(ats_ptr_type, tmp160) ;
ATSlocal(ats_ptr_type, tmp162) ;
ATSlocal(ats_ptr_type, tmp163) ;
ATSlocal(ats_ptr_type, tmp166) ;
ATSlocal(ats_ptr_type, tmp169) ;
ATSlocal(ats_ptr_type, tmp170) ;
ATSlocal_void(tmp171) ;
ATSlocal_void(tmp172) ;
ATSlocal(ats_ptr_type, tmp173) ;
ATSlocal(ats_ptr_type, tmp174) ;
ATSlocal(ats_ptr_type, tmp175) ;
__ats_lab_staftscstr_stbefitemlst_merge_ifmetck_16:
tmp154 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_6*)arg1)->atslab_staftscstr_res ;
tmp156 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_8*)tmp154)->atslab_i2nvresstate_svs ;
tmp157 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_8*)tmp154)->atslab_i2nvresstate_gua ;
tmp155 = _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__s2qua_instantiate_and_add (arg0, tmp156, tmp157) ;
if (arg3) {
tmp160 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_8*)tmp154)->atslab_i2nvresstate_met ;
do {
__ats_lab_30:
if (tmp160 == (ats_sum_ptr_type)0) { goto __ats_lab_31 ; }
tmp162 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_7*)tmp160)->atslab_0 ;
tmp163 = _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_staexp2_2esats__s2explst_subst (tmp155, tmp162) ;
tmp158 = ATS_MALLOC(sizeof(_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_7)) ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_7*)tmp158)->atslab_0 = tmp163 ;

break ;

__ats_lab_31:
tmp158 = (ats_sum_ptr_type)0 ;

break ;

} while (0) ;
} else {
tmp158 = (ats_sum_ptr_type)0 ;

} /* if */
tmp169 = (ats_sum_ptr_type)0 ;

tmp166 = _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_reference_2esats__ref_make_elt__ats_ptr_type (tmp169) ;
tmp170 = sascstr_make_13 (arg0, tmp158, tmp155, tmp166) ;
/* tmp171 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__trans3_env_add_cstr_ref (tmp166) ;
tmp174 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_6*)arg1)->atslab_staftscstr_cstr ;
tmp173 = ATS_MALLOC(sizeof(_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1)) ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1*)tmp173)->atslab_0 = tmp170 ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1*)tmp173)->atslab_1 = tmp174 ;

/* tmp172 = */ atsopt_state_staftscstr_cstr_set (arg1, tmp173) ;
tmp175 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_6*)arg1)->atslab_staftscstr_sais ;
/* tmp103 = */ auxlst_18 (arg0, tmp175, arg2) ;
return ;
} /* fun */

ats_void_type
aux_17 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
ATSlocal_void(tmp104) ;
ATSlocal(ats_int_type, tmp105) ;
ATSlocal(ats_ptr_type, tmp106) ;
ATSlocal(ats_int_type, tmp107) ;
ATSlocal(ats_int_type, tmp108) ;
ATSlocal(ats_ptr_type, tmp109) ;
ATSlocal(ats_ptr_type, tmp110) ;
ATSlocal(ats_ptr_type, tmp112) ;
ATSlocal_void(tmp114) ;
ATSlocal(ats_bool_type, tmp115) ;
ATSlocal(ats_int_type, tmp117) ;
ATSlocal(ats_int_type, tmp118) ;
ATSlocal(ats_ptr_type, tmp120) ;
ATSlocal_void(tmp121) ;
ATSlocal(ats_ptr_type, tmp123) ;
ATSlocal(ats_ptr_type, tmp125) ;
ATSlocal_void(tmp126) ;
ATSlocal_void(tmp127) ;
ATSlocal_void(tmp128) ;
ATSlocal_void(tmp129) ;
ATSlocal_void(tmp130) ;
ATSlocal_void(tmp131) ;
ATSlocal(ats_ptr_type, tmp133) ;
ATSlocal_void(tmp134) ;
ATSlocal_void(tmp135) ;
ATSlocal_void(tmp136) ;
ATSlocal_void(tmp137) ;
ATSlocal_void(tmp138) ;
ATSlocal_void(tmp139) ;
ATSlocal(ats_ptr_type, tmp142) ;
__ats_lab_aux_17:
tmp105 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_0*)arg2)->atslab_stbefitem_lin ;
tmp106 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_0*)arg2)->atslab_stbefitem_var ;
tmp107 = _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_dynexp2_2esats__d2var_get_lin (tmp106) ;
tmp108 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_5*)arg1)->atslab_staftitem_lin ;
tmp110 = _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_dynexp2_2esats__d2var_get_typ (tmp106) ;
do {
__ats_lab_21:
if (tmp110 == (ats_sum_ptr_type)0) { goto __ats_lab_22 ; }
tmp112 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_7*)tmp110)->atslab_0 ;
tmp109 = ATS_MALLOC(sizeof(_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_2)) ;
((ats_sum_ptr_type)tmp109)->tag = 0 ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_2*)tmp109)->atslab_0 = arg0 ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_2*)tmp109)->atslab_1 = tmp112 ;

break ;

__ats_lab_22:
tmp109 = ATS_MALLOC(sizeof(_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_3)) ;
((ats_sum_ptr_type)tmp109)->tag = 1 ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_3*)tmp109)->atslab_0 = arg0 ;

break ;

} while (0) ;
tmp115 = atspre_gt_int_int (tmp107, tmp105) ;
if (tmp115) {
tmp118 = atspre_add_int_int (tmp108, tmp107) ;
tmp117 = atspre_sub_int_int (tmp118, tmp105) ;
/* tmp114 = */ atsopt_state_staftitem_set_lin (arg1, tmp117) ;
} else {
} /* if */
tmp120 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_5*)arg1)->atslab_staftitem_typ ;
do {
__ats_lab_23:
if (tmp120 == (ats_sum_ptr_type)0) { goto __ats_lab_24 ; }
tmp123 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1*)tmp120)->atslab_0 ;
do {
__ats_lab_25:
if (((ats_sum_ptr_type)tmp109)->tag != 0) { goto __ats_lab_26 ; }
tmp125 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_2*)tmp109)->atslab_0 ;
if (((ats_sum_ptr_type)tmp123)->tag != 1) { goto __ats_lab_26 ; }
/* tmp126 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_location_2esats__prerr_location (tmp125) ;
/* tmp127 = */ atspre_prerr_string (": error(3)") ;
/* tmp128 = */ atspre_prerr_string (": the dynamic variable [") ;
/* tmp129 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_dynexp2_2esats__prerr_d2var (tmp106) ;
/* tmp130 = */ atspre_prerr_string ("] is expected to be consumed but it is preserved instead.") ;
/* tmp131 = */ atspre_prerr_newline () ;
/* tmp121 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_error_2esats__abort () ;
break ;

__ats_lab_26:
if (((ats_sum_ptr_type)tmp109)->tag != 1) { goto __ats_lab_27 ; }
tmp133 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_3*)tmp109)->atslab_0 ;
if (((ats_sum_ptr_type)tmp123)->tag != 0) { goto __ats_lab_27 ; }
/* tmp134 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_location_2esats__prerr_location (tmp133) ;
/* tmp135 = */ atspre_prerr_string (": error(3)") ;
/* tmp136 = */ atspre_prerr_string (": the dynamic variable [") ;
/* tmp137 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_dynexp2_2esats__prerr_d2var (tmp106) ;
/* tmp138 = */ atspre_prerr_string ("] is expected to be preserved but it is consumed instead.") ;
/* tmp139 = */ atspre_prerr_newline () ;
/* tmp121 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_error_2esats__abort () ;
break ;

__ats_lab_27:
break ;

} while (0) ;
break ;

__ats_lab_24:
break ;

} while (0) ;
tmp142 = ATS_MALLOC(sizeof(_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1)) ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1*)tmp142)->atslab_0 = tmp109 ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1*)tmp142)->atslab_1 = tmp120 ;

/* tmp104 = */ atsopt_state_staftitem_set_typ (arg1, tmp142) ;
return ;
} /* fun */

ats_void_type
auxlst_18 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
ATSlocal_void(tmp143) ;
ATSlocal(ats_ptr_type, tmp145) ;
ATSlocal(ats_ptr_type, tmp146) ;
ATSlocal(ats_ptr_type, tmp147) ;
ATSlocal(ats_ptr_type, tmp148) ;
ATSlocal_void(tmp149) ;
ATSlocal(ats_ptr_type, tmp150) ;
ATSlocal(ats_ptr_type, tmp151) ;
ATSlocal(ats_ptr_type, tmp152) ;
__ats_lab_auxlst_18:
do {
__ats_lab_28:
if (arg1 == (ats_sum_ptr_type)0) { goto __ats_lab_29 ; }
tmp145 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1*)arg1)->atslab_0 ;
tmp146 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1*)arg1)->atslab_1 ;
tmp147 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1*)arg2)->atslab_0 ;
tmp148 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1*)arg2)->atslab_1 ;
/* tmp149 = */ aux_17 (arg0, tmp145, tmp147) ;
tmp150 = arg0 ;
tmp151 = tmp146 ;
tmp152 = tmp148 ;
arg0 = tmp150 ;
arg1 = tmp151 ;
arg2 = tmp152 ;
goto __ats_lab_auxlst_18 ;
break ;

__ats_lab_29:
break ;

} while (0) ;
return ;
} /* fun */

ats_ptr_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_reference_2esats__ref_make_elt__ats_ptr_type (ats_ptr_type arg0) {
ATSlocal(ats_ptr_type, tmp167) ;
ATSlocal(ats_ptr_type, tmp168) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_reference_2esats__ref_make_elt__ats_ptr_type:
tmp168 = arg0 ;
tmp167 = atspre_ref_make_elt_tsz ((&tmp168), sizeof(ats_ptr_type)) ;
return tmp167 ;
} /* fun */

ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__staftscstr_stbefitemlst_merge (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
ATSlocal_void(tmp176) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__staftscstr_stbefitemlst_merge:
/* tmp176 = */ staftscstr_stbefitemlst_merge_ifmetck_16 (arg0, arg1, arg2, ats_true_bool) ;
return ;
} /* fun */

ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__staftscstr_stbefitemlst_merge_skipmetck (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
ATSlocal_void(tmp177) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__staftscstr_stbefitemlst_merge_skipmetck:
/* tmp177 = */ staftscstr_stbefitemlst_merge_ifmetck_16 (arg0, arg1, arg2, ats_false_bool) ;
return ;
} /* fun */

ats_ptr_type
i2nvarglst_find_d2var_22 (ats_ptr_type arg0, ats_ptr_type arg1) {
ATSlocal(ats_ptr_type, tmp178) ;
ATSlocal(ats_ptr_type, tmp180) ;
ATSlocal(ats_ptr_type, tmp181) ;
ATSlocal(ats_bool_type, tmp182) ;
ATSlocal(ats_ptr_type, tmp183) ;
ATSlocal(ats_ptr_type, tmp186) ;
ATSlocal(ats_ptr_type, tmp187) ;
__ats_lab_i2nvarglst_find_d2var_22:
do {
__ats_lab_32:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_33 ; }
tmp180 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1*)arg0)->atslab_0 ;
tmp181 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1*)arg0)->atslab_1 ;
tmp183 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_9*)tmp180)->atslab_i2nvarg_var ;
tmp182 = _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_dynexp2_2esats__eq_d2var_d2var (tmp183, arg1) ;
if (tmp182) {
tmp178 = ATS_MALLOC(sizeof(_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_7)) ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_7*)tmp178)->atslab_0 = tmp180 ;

} else {
tmp186 = tmp181 ;
tmp187 = arg1 ;
arg0 = tmp186 ;
arg1 = tmp187 ;
goto __ats_lab_i2nvarglst_find_d2var_22 ;
} /* if */
break ;

__ats_lab_33:
tmp178 = (ats_sum_ptr_type)0 ;

break ;

} while (0) ;
return tmp178 ;
} /* fun */

ats_bool_type
d2var_is_done_23 (ats_ptr_type arg0) {
ATSlocal(ats_bool_type, tmp189) ;
ATSlocal(ats_ptr_type, tmp190) ;
__ats_lab_d2var_is_done_23:
tmp190 = _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_dynexp2_2esats__d2var_get_fin (arg0) ;
do {
__ats_lab_34:
if (tmp190 != &_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_dynexp2_2esats__D2VARFINdone) { goto __ats_lab_35 ; }
tmp189 = ats_true_bool ;
break ;

__ats_lab_35:
tmp189 = ats_false_bool ;
break ;

} while (0) ;
return tmp189 ;
} /* fun */

ats_ptr_type
aux_find_24 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
ATSlocal(ats_ptr_type, tmp193) ;
ATSlocal(ats_ptr_type, tmp194) ;
ATSlocal(ats_ptr_type, tmp196) ;
ATSlocal(ats_ptr_type, tmp197) ;
ATSlocal(ats_ptr_type, tmp198) ;
ATSlocal(ats_ptr_type, tmp200) ;
ATSlocal(ats_ptr_type, tmp201) ;
__ats_lab_aux_find_24:
tmp194 = i2nvarglst_find_d2var_22 (arg1, arg2) ;
do {
__ats_lab_36:
if (tmp194 == (ats_sum_ptr_type)0) { goto __ats_lab_37 ; }
tmp196 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_7*)tmp194)->atslab_0 ;
ATS_FREE(tmp194) ;
tmp198 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_9*)tmp196)->atslab_i2nvarg_typ ;
do {
__ats_lab_38:
if (tmp198 == (ats_sum_ptr_type)0) { goto __ats_lab_39 ; }
tmp200 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_7*)tmp198)->atslab_0 ;
tmp201 = _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_staexp2_2esats__s2exp_subst (arg0, tmp200) ;
tmp197 = ATS_MALLOC(sizeof(_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_7)) ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_7*)tmp197)->atslab_0 = tmp201 ;

break ;

__ats_lab_39:
tmp197 = (ats_sum_ptr_type)0 ;

break ;

} while (0) ;
tmp193 = ATS_MALLOC(sizeof(_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_7)) ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_7*)tmp193)->atslab_0 = tmp197 ;

break ;

__ats_lab_37:
tmp193 = (ats_sum_ptr_type)0 ;

break ;

} while (0) ;
return tmp193 ;
} /* fun */

ats_ptr_type
aux_item_errmsg1_25 (ats_ptr_type arg0, ats_ptr_type arg1) {
ATSlocal(ats_ptr_type, tmp204) ;
ATSlocal_void(tmp205) ;
ATSlocal_void(tmp206) ;
ATSlocal_void(tmp207) ;
ATSlocal_void(tmp208) ;
ATSlocal_void(tmp209) ;
ATSlocal_void(tmp210) ;
__ats_lab_aux_item_errmsg1_25:
/* tmp205 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_location_2esats__prerr_location (arg0) ;
/* tmp206 = */ atspre_prerr_string (": error(3)") ;
/* tmp207 = */ atspre_prerr_string (": the dynamic variable [") ;
/* tmp208 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_dynexp2_2esats__prerr_d2var (arg1) ;
/* tmp209 = */ atspre_prerr_string ("] is expected to be consumed but it is not.") ;
/* tmp210 = */ atspre_prerr_newline () ;
/* tmp204 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_error_2esats__abort () ;
return tmp204 ;
} /* fun */

ats_void_type
aux_item_errmsg2_26 (ats_ptr_type arg0, ats_ptr_type arg1) {
ATSlocal_void(tmp211) ;
ATSlocal_void(tmp212) ;
ATSlocal_void(tmp213) ;
ATSlocal_void(tmp214) ;
ATSlocal_void(tmp215) ;
ATSlocal_void(tmp216) ;
ATSlocal_void(tmp217) ;
__ats_lab_aux_item_errmsg2_26:
/* tmp212 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_location_2esats__prerr_location (arg0) ;
/* tmp213 = */ atspre_prerr_string (": error(3)") ;
/* tmp214 = */ atspre_prerr_string (": the dynamic variable [") ;
/* tmp215 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_dynexp2_2esats__prerr_d2var (arg1) ;
/* tmp216 = */ atspre_prerr_string ("] is expected to be preserved but it is not.") ;
/* tmp217 = */ atspre_prerr_newline () ;
/* tmp211 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_error_2esats__abort () ;
return ;
} /* fun */

ats_void_type
aux_saityp_27 (ats_int_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_ptr_type arg3, ats_ptr_type arg4) {
ATSlocal_void(tmp218) ;
ATSlocal(ats_ptr_type, tmp220) ;
ATSlocal(ats_ptr_type, tmp221) ;
ATSlocal(ats_int_type, tmp222) ;
ATSlocal(ats_ptr_type, tmp223) ;
ATSlocal(ats_ptr_type, tmp224) ;
ATSlocal(ats_ptr_type, tmp226) ;
ATSlocal(ats_int_type, tmp227) ;
ATSlocal(ats_ptr_type, tmp229) ;
ATSlocal(ats_ptr_type, tmp232) ;
ATSlocal(ats_ptr_type, tmp234) ;
ATSlocal(ats_bool_type, tmp236) ;
ATSlocal_void(tmp238) ;
ATSlocal_void(tmp239) ;
ATSlocal(ats_ptr_type, tmp240) ;
ATSlocal(ats_ptr_type, tmp243) ;
ATSlocal(ats_ptr_type, tmp244) ;
ATSlocal(ats_ptr_type, tmp246) ;
__ats_lab_aux_saityp_27:
do {
__ats_lab_40:
if (((ats_sum_ptr_type)arg4)->tag != 0) { goto __ats_lab_41 ; }
tmp220 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_2*)arg4)->atslab_0 ;
tmp221 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_2*)arg4)->atslab_1 ;
tmp222 = arg0 ;
tmp224 = aux_find_24 (arg1, arg2, arg3) ;
do {
__ats_lab_42:
if (tmp224 == (ats_sum_ptr_type)0) { goto __ats_lab_43 ; }
tmp226 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_7*)tmp224)->atslab_0 ;
ATS_FREE(tmp224) ;
tmp227 = atspre_add_int_int (tmp222, 1) ;
tmp222 = tmp227 ;
do {
__ats_lab_44:
if (tmp226 == (ats_sum_ptr_type)0) { goto __ats_lab_45 ; }
tmp229 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_7*)tmp226)->atslab_0 ;
tmp223 = tmp229 ;
break ;

__ats_lab_45:
tmp223 = aux_item_errmsg1_25 (tmp220, arg3) ;
break ;

} while (0) ;
break ;

__ats_lab_43:
tmp232 = _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_dynexp2_2esats__d2var_get_mastyp (arg3) ;
do {
__ats_lab_46:
if (tmp232 == (ats_sum_ptr_type)0) { goto __ats_lab_47 ; }
tmp234 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_7*)tmp232)->atslab_0 ;
tmp223 = tmp234 ;
break ;

__ats_lab_47:
tmp223 = aux_item_errmsg1_25 (tmp220, arg3) ;
break ;

} while (0) ;
break ;

} while (0) ;
tmp236 = atspre_gt_int_int (tmp222, 0) ;
if (tmp236) {
/* tmp238 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__trans3_env_push_sta () ;
/* tmp239 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_staexp2_solve_2esats__s2exp_tyleq_solve (tmp220, tmp221, tmp223) ;
tmp240 = ATS_MALLOC(sizeof(_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_10)) ;
((ats_sum_ptr_type)tmp240)->tag = 4 ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_10*)tmp240)->atslab_0 = arg3 ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_10*)tmp240)->atslab_1 = tmp221 ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_10*)tmp240)->atslab_2 = tmp223 ;

/* tmp218 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__trans3_env_pop_sta_and_add (tmp220, tmp240) ;
} else {
} /* if */
break ;

__ats_lab_41:
tmp243 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_3*)arg4)->atslab_0 ;
tmp244 = aux_find_24 (arg1, arg2, arg3) ;
do {
__ats_lab_48:
if (tmp244 == (ats_sum_ptr_type)0) { goto __ats_lab_49 ; }
tmp246 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_7*)tmp244)->atslab_0 ;
ATS_FREE(tmp244) ;
do {
__ats_lab_50:
if (tmp246 == (ats_sum_ptr_type)0) { goto __ats_lab_51 ; }
/* tmp218 = */ aux_item_errmsg2_26 (tmp243, arg3) ;
break ;

__ats_lab_51:
break ;

} while (0) ;
break ;

__ats_lab_49:
break ;

} while (0) ;
break ;

} while (0) ;
return ;
} /* fun */

ats_void_type
aux_item_one_28 (ats_int_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_ptr_type arg3, ats_ptr_type arg4) {
ATSlocal_void(tmp250) ;
ATSlocal(ats_ptr_type, tmp251) ;
ATSlocal(ats_ptr_type, tmp253) ;
ATSlocal(ats_ptr_type, tmp254) ;
ATSlocal(ats_ptr_type, tmp255) ;
ATSlocal_void(tmp256) ;
ATSlocal(ats_ptr_type, tmp257) ;
__ats_lab_aux_item_one_28:
tmp251 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_5*)arg3)->atslab_staftitem_typ ;
do {
__ats_lab_52:
if (tmp251 == (ats_sum_ptr_type)0) { goto __ats_lab_53 ; }
tmp253 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1*)tmp251)->atslab_0 ;
tmp254 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1*)tmp251)->atslab_1 ;
tmp255 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_8*)arg2)->atslab_i2nvresstate_arg ;
/* tmp256 = */ atsopt_state_staftitem_set_typ (arg3, tmp254) ;
tmp257 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_8*)arg2)->atslab_i2nvresstate_arg ;
/* tmp250 = */ aux_saityp_27 (arg0, arg1, tmp257, arg4, tmp253) ;
break ;

__ats_lab_53:
break ;

} while (0) ;
return ;
} /* fun */

ats_void_type
aux_item_all_29 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_ptr_type arg3) {
ATSlocal_void(tmp259) ;
ATSlocal(ats_ptr_type, tmp261) ;
ATSlocal(ats_ptr_type, tmp262) ;
ATSlocal(ats_ptr_type, tmp263) ;
ATSlocal(ats_ptr_type, tmp264) ;
ATSlocal(ats_ptr_type, tmp265) ;
ATSlocal(ats_int_type, tmp266) ;
ATSlocal(ats_int_type, tmp267) ;
ATSlocal_void(tmp268) ;
ATSlocal(ats_bool_type, tmp270) ;
ATSlocal(ats_int_type, tmp272) ;
ATSlocal(ats_ptr_type, tmp273) ;
ATSlocal(ats_ptr_type, tmp274) ;
ATSlocal(ats_ptr_type, tmp275) ;
ATSlocal(ats_ptr_type, tmp276) ;
__ats_lab_aux_item_all_29:
do {
__ats_lab_54:
if (arg2 == (ats_sum_ptr_type)0) { goto __ats_lab_55 ; }
tmp261 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1*)arg2)->atslab_0 ;
tmp262 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1*)arg2)->atslab_1 ;
tmp263 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1*)arg3)->atslab_0 ;
tmp264 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1*)arg3)->atslab_1 ;
tmp265 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_0*)tmp263)->atslab_stbefitem_var ;
tmp266 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_5*)tmp261)->atslab_staftitem_lin ;
tmp267 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_0*)tmp263)->atslab_stbefitem_lin ;
do {
__ats_lab_56:
tmp270 = d2var_is_done_23 (tmp265) ;
if (!tmp270) { goto __ats_lab_57 ; }
break ;

__ats_lab_57:
tmp272 = atspre_sub_int_int (tmp266, tmp267) ;
/* tmp268 = */ aux_item_one_28 (tmp272, arg0, arg1, tmp261, tmp265) ;
break ;

} while (0) ;
tmp273 = arg0 ;
tmp274 = arg1 ;
tmp275 = tmp262 ;
tmp276 = tmp264 ;
arg0 = tmp273 ;
arg1 = tmp274 ;
arg2 = tmp275 ;
arg3 = tmp276 ;
goto __ats_lab_aux_item_all_29 ;
break ;

__ats_lab_55:
break ;

} while (0) ;
return ;
} /* fun */

ats_void_type
aux_term_check_30 (ats_ptr_type arg0, ats_ptr_type arg1) {
ATSlocal_void(tmp278) ;
ATSlocal(ats_ptr_type, tmp280) ;
ATSlocal(ats_ptr_type, tmp281) ;
ATSlocal(ats_ptr_type, tmp283) ;
ATSlocal(ats_int_type, tmp284) ;
ATSlocal_void(tmp285) ;
ATSlocal(ats_bool_type, tmp286) ;
ATSlocal_void(tmp288) ;
ATSlocal_void(tmp289) ;
ATSlocal_void(tmp290) ;
ATSlocal_void(tmp291) ;
ATSlocal(ats_bool_type, tmp292) ;
ATSlocal(ats_ptr_type, tmp294) ;
__ats_lab_aux_term_check_30:
do {
__ats_lab_58:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_59 ; }
tmp280 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_7*)arg0)->atslab_0 ;
tmp281 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_4*)arg1)->atslab_sascstr_met ;
do {
__ats_lab_60:
if (tmp281 == (ats_sum_ptr_type)0) { goto __ats_lab_61 ; }
tmp283 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_7*)tmp281)->atslab_0 ;
tmp284 = _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_list_2esats__list_length_compare (tmp283, tmp280) ;
tmp286 = atspre_ineq (tmp284, 0) ;
if (tmp286) {
/* tmp288 = */ prerr_interror_0 () ;
/* tmp289 = */ atspre_prerr_string (": aux_term_check: Some: Some") ;
/* tmp290 = */ atspre_prerr_newline () ;
/* tmp291 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_error_2esats__abort () ;
tmp292 = atspre_ieq (tmp284, 0) ;
/* tmp285 = */ atspre_assert (tmp292) ;
} else {
} /* if */
tmp294 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_4*)arg1)->atslab_sascstr_loc ;
/* tmp278 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__trans3_env_add_metric_dec (tmp294, tmp283, tmp280) ;
break ;

__ats_lab_61:
break ;

} while (0) ;
break ;

__ats_lab_59:
break ;

} while (0) ;
return ;
} /* fun */

ats_void_type
aux_itemlst_all_31 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_ptr_type arg3, ats_ptr_type arg4) {
ATSlocal_void(tmp297) ;
ATSlocal(ats_ptr_type, tmp299) ;
ATSlocal(ats_ptr_type, tmp300) ;
ATSlocal_void(tmp301) ;
ATSlocal_void(tmp302) ;
ATSlocal_void(tmp303) ;
ATSlocal(ats_ptr_type, tmp304) ;
ATSlocal(ats_ptr_type, tmp305) ;
ATSlocal(ats_ptr_type, tmp306) ;
ATSlocal(ats_ptr_type, tmp307) ;
ATSlocal(ats_ptr_type, tmp308) ;
ATSlocal(ats_ptr_type, tmp309) ;
ATSlocal(ats_ptr_type, tmp310) ;
ATSlocal(ats_ptr_type, tmp311) ;
ATSlocal(ats_ptr_type, tmp312) ;
ATSlocal(ats_ptr_type, tmp313) ;
ATSlocal(ats_ptr_type, tmp314) ;
ATSlocal(ats_ptr_type, tmp315) ;
ATSlocal(ats_ptr_type, tmp316) ;
__ats_lab_aux_itemlst_all_31:
do {
__ats_lab_62:
if (arg4 == (ats_sum_ptr_type)0) { goto __ats_lab_63 ; }
tmp299 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1*)arg4)->atslab_0 ;
tmp300 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1*)arg4)->atslab_1 ;
/* tmp301 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__trans3_env_push_sta () ;
/* tmp302 = */ aux_term_check_30 (arg0, tmp299) ;
tmp304 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_4*)tmp299)->atslab_sascstr_sub ;
/* tmp303 = */ aux_item_all_29 (tmp304, arg1, arg2, arg3) ;
tmp305 = _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__trans3_env_pop_sta () ;
tmp306 = _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_list_2esats__list_vt_reverse_list (tmp305) ;
tmp308 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_4*)tmp299)->atslab_sascstr_loc ;
tmp309 = (ats_sum_ptr_type)(&_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__C3STRKINDmain) ;

tmp307 = _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__c3str_itmlst (tmp308, tmp309, tmp306) ;
tmp310 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_4*)tmp299)->atslab_sascstr_ref ;
tmp311 = ATS_MALLOC(sizeof(_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_7)) ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_7*)tmp311)->atslab_0 = tmp307 ;

*((ats_ptr_type*)tmp310) = tmp311 ;
tmp312 = arg0 ;
tmp313 = arg1 ;
tmp314 = arg2 ;
tmp315 = arg3 ;
tmp316 = tmp300 ;
arg0 = tmp312 ;
arg1 = tmp313 ;
arg2 = tmp314 ;
arg3 = tmp315 ;
arg4 = tmp316 ;
goto __ats_lab_aux_itemlst_all_31 ;
break ;

__ats_lab_63:
break ;

} while (0) ;
return ;
} /* fun */

ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__staftscstr_stbefitemlst_check (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
ATSlocal_void(tmp318) ;
ATSlocal(ats_ptr_type, tmp319) ;
ATSlocal(ats_ptr_type, tmp320) ;
ATSlocal(ats_ptr_type, tmp321) ;
ATSlocal(ats_ptr_type, tmp322) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__staftscstr_stbefitemlst_check:
tmp319 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_6*)arg1)->atslab_staftscstr_met ;
tmp320 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_6*)arg1)->atslab_staftscstr_res ;
tmp321 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_6*)arg1)->atslab_staftscstr_sais ;
tmp322 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_6*)arg1)->atslab_staftscstr_cstr ;
/* tmp318 = */ aux_itemlst_all_31 (tmp319, tmp320, tmp321, arg2, tmp322) ;
return ;
} /* fun */

ats_ptr_type
aux_find_33 (ats_ptr_type arg0, ats_ptr_type arg1) {
ATSlocal(ats_ptr_type, tmp323) ;
ATSlocal(ats_ptr_type, tmp324) ;
ATSlocal(ats_ptr_type, tmp326) ;
ATSlocal(ats_ptr_type, tmp327) ;
__ats_lab_aux_find_33:
tmp324 = i2nvarglst_find_d2var_22 (arg0, arg1) ;
do {
__ats_lab_64:
if (tmp324 == (ats_sum_ptr_type)0) { goto __ats_lab_65 ; }
tmp326 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_7*)tmp324)->atslab_0 ;
ATS_FREE(tmp324) ;
tmp327 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_9*)tmp326)->atslab_i2nvarg_typ ;
tmp323 = ATS_MALLOC(sizeof(_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_7)) ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_7*)tmp323)->atslab_0 = tmp327 ;

break ;

__ats_lab_65:
tmp323 = (ats_sum_ptr_type)0 ;

break ;

} while (0) ;
return tmp323 ;
} /* fun */

ats_void_type
aux_iter_34 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2, ats_ptr_type arg3) {
ATSlocal_void(tmp329) ;
ATSlocal(ats_ptr_type, tmp331) ;
ATSlocal(ats_ptr_type, tmp332) ;
ATSlocal(ats_ptr_type, tmp333) ;
ATSlocal(ats_ptr_type, tmp334) ;
ATSlocal(ats_ptr_type, tmp335) ;
ATSlocal(ats_int_type, tmp336) ;
ATSlocal(ats_int_type, tmp337) ;
ATSlocal_void(tmp338) ;
ATSlocal(ats_bool_type, tmp339) ;
ATSlocal_void(tmp342) ;
ATSlocal(ats_ptr_type, tmp343) ;
ATSlocal(ats_ptr_type, tmp345) ;
ATSlocal(ats_ptr_type, tmp346) ;
ATSlocal(ats_bool_type, tmp349) ;
ATSlocal(ats_ptr_type, tmp350) ;
ATSlocal(ats_ptr_type, tmp352) ;
ATSlocal(ats_ptr_type, tmp353) ;
ATSlocal(ats_ptr_type, tmp356) ;
ATSlocal(ats_ptr_type, tmp357) ;
ATSlocal(ats_ptr_type, tmp358) ;
ATSlocal(ats_ptr_type, tmp359) ;
__ats_lab_aux_iter_34:
do {
__ats_lab_66:
if (arg2 == (ats_sum_ptr_type)0) { goto __ats_lab_67 ; }
tmp331 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1*)arg2)->atslab_0 ;
tmp332 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1*)arg2)->atslab_1 ;
tmp333 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1*)arg3)->atslab_0 ;
tmp334 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_1*)arg3)->atslab_1 ;
tmp335 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_0*)tmp333)->atslab_stbefitem_var ;
tmp336 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_5*)tmp331)->atslab_staftitem_lin ;
tmp337 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_0*)tmp333)->atslab_stbefitem_lin ;
tmp339 = atspre_gt_int_int (tmp336, tmp337) ;
if (tmp339) {
/* tmp338 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_dynexp2_2esats__d2var_set_lin (tmp335, tmp336) ;
} else {
} /* if */
tmp343 = aux_find_33 (arg1, tmp335) ;
do {
__ats_lab_68:
if (tmp343 == (ats_sum_ptr_type)0) { goto __ats_lab_69 ; }
tmp345 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_sum_7*)tmp343)->atslab_0 ;
ATS_FREE(tmp343) ;
tmp346 = _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__s2expopt_opnexi_and_add (arg0, tmp345) ;
/* tmp342 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_dynexp2_2esats__d2var_set_typ (tmp335, tmp346) ;
break ;

__ats_lab_69:
do {
__ats_lab_70:
tmp349 = atspre_gt_int_int (tmp336, tmp337) ;
if (!tmp349) { goto __ats_lab_71 ; }
tmp350 = _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_dynexp2_2esats__d2var_get_typ (tmp335) ;
do {
__ats_lab_72:
if (tmp350 == (ats_sum_ptr_type)0) { goto __ats_lab_73 ; }
tmp352 = _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_dynexp2_2esats__d2var_get_mastyp (tmp335) ;
tmp353 = _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__s2expopt_opnexi_and_add (arg0, tmp352) ;
/* tmp342 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_dynexp2_2esats__d2var_set_typ (tmp335, tmp353) ;
break ;

__ats_lab_73:
break ;

} while (0) ;
break ;

__ats_lab_71:
break ;

} while (0) ;
break ;

} while (0) ;
tmp356 = arg0 ;
tmp357 = arg1 ;
tmp358 = tmp332 ;
tmp359 = tmp334 ;
arg0 = tmp356 ;
arg1 = tmp357 ;
arg2 = tmp358 ;
arg3 = tmp359 ;
goto __ats_lab_aux_iter_34 ;
break ;

__ats_lab_67:
break ;

} while (0) ;
return ;
} /* fun */

ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__staftscstr_stbefitemlst_update (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
ATSlocal_void(tmp361) ;
ATSlocal(ats_ptr_type, tmp362) ;
ATSlocal(ats_ptr_type, tmp363) ;
ATSlocal_void(tmp364) ;
ATSlocal(ats_ptr_type, tmp365) ;
ATSlocal_void(tmp366) ;
ATSlocal(ats_ptr_type, tmp367) ;
ATSlocal(ats_ptr_type, tmp368) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__staftscstr_stbefitemlst_update:
tmp362 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_6*)arg1)->atslab_staftscstr_res ;
tmp363 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_6*)arg1)->atslab_staftscstr_sais ;
tmp365 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_8*)tmp362)->atslab_i2nvresstate_svs ;
/* tmp364 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__trans3_env_add_svarlst (tmp365) ;
tmp367 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_8*)tmp362)->atslab_i2nvresstate_gua ;
/* tmp366 = */ _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__trans3_env_hypo_add_proplst (arg0, tmp367) ;
tmp368 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_8*)tmp362)->atslab_i2nvresstate_arg ;
/* tmp361 = */ aux_iter_34 (arg0, tmp368, tmp363, arg2) ;
return ;
} /* fun */

/* static load function */

extern ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_effect_2esats__staload () ;
extern ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_error_2esats__staload () ;
extern ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_list_2esats__staload () ;
extern ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_staexp2_solve_2esats__staload () ;
extern ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_staexp2_2esats__staload () ;
extern ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_dynexp2_2esats__staload () ;
extern ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__staload () ;
extern ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_reference_2esats__staload () ;
extern ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_reference_2edats__staload () ;
static int _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats__staload_flag = 0 ;
ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats__staload () {
if (_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats__staload_flag) return ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats__staload_flag = 1 ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_effect_2esats__staload () ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_error_2esats__staload () ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_list_2esats__staload () ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_staexp2_solve_2esats__staload () ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_staexp2_2esats__staload () ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_dynexp2_2esats__staload () ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_2esats__staload () ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_reference_2esats__staload () ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_reference_2edats__staload () ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats__SAITYPsome.tag = 0 ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats__SAITYPnone.tag = 1 ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_lexing_2esats__LexingErrorException.tag = ats_exception_con_tag_new () ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_lexing_2esats__LexingErrorException.name = "_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_lexing_2esats__LexingErrorException" ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_error_2esats__FatalErrorException.tag = ats_exception_con_tag_new () ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_error_2esats__FatalErrorException.name = "_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_error_2esats__FatalErrorException" ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_error_2esats__DeadCodeException.tag = ats_exception_con_tag_new () ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_error_2esats__DeadCodeException.name = "_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_error_2esats__DeadCodeException" ;
}

/* dynamic load function */

extern int _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats__dynload_flag ;
ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats__dynload () {
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats__dynload_flag = 1 ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats__staload () ;
}

/* external types */

typedef _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_5* staftitem_t ;

typedef _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_trans3_env_state_2edats_rec_6* staftscstr_t ;

/* external codes at mid */

/* external codes at bot */



ats_void_type
atsopt_state_staftitem_set_lin
  (ats_ptr_type sai, ats_int_type lin) {
  ((staftitem_t)sai)->atslab_staftitem_lin = lin; return ;
} // end of [atsopt_state_staftitem_set_lin]

ats_void_type
atsopt_state_staftitem_set_typ
  (ats_ptr_type sai, ats_ptr_type os2es) {
  ((staftitem_t)sai)->atslab_staftitem_typ = os2es; return ;
} // end of [atsopt_state_staftitem_set_typ]




ats_void_type
atsopt_state_staftscstr_met_set
  (ats_ptr_type sac, ats_ptr_type met) {
  ((staftscstr_t)sac)->atslab_staftscstr_met = met ; return ;
} // end of [atsopt_state_staftscstr_met_set]

ats_void_type
atsopt_state_staftscstr_cstr_set
  (ats_ptr_type sac, ats_ptr_type cstr) {
  ((staftscstr_t)sac)->atslab_staftscstr_cstr = cstr ; return ;
} // end of [atsopt_state_staftscstr_cstr_set]


