/*
 *
 * This C code is generated by ATS/Geizella
 * The compilation time is: 2012-5-27: 21:23
 *
 */

#define _ATS_GEIZELLA 1

#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"

/* include some .cats files */

#include "prelude/CATS/array.cats"
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/string.cats"

/* external codes at top */

/* type definitions */

typedef struct {
ats_int_type atslab_0 ;
ats_ptr_type atslab_1 ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_comarg_2edats_sum_0 ;

typedef struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_comarg_2edats_sum_1 ;

/* external dynamic constructor declarations */

ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fprelude_2fGEIZELLA_2fbasics_sta_2esats__list_vt_cons) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fprelude_2fGEIZELLA_2fbasics_sta_2esats__list_vt_nil) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_comarg_2esats__COMARGkey) ;

/* external dynamic constant declarations */

extern ats_bool_type atspre_neq_char_char(ats_char_type, ats_char_type) ;
extern ats_int_type atspre_iadd(ats_int_type, ats_int_type) ;
extern ats_bool_type atspre_ilt(ats_int_type, ats_int_type) ;
extern ats_int_type atspre_int1_of_size1(ats_size_type) ;
extern ats_ptr_type atspre_castfn_ptr(ats_ptr_type) ;
extern ats_char_type atspre_string_get_char_at__intsz(ats_ptr_type, ats_int_type) ;
extern ats_size_type atspre_string_length(ats_ptr_type) ;
extern ats_ptr_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_comarg_2esats__comarg_parse(ats_ptr_type) ;

/* internal function declarations */

static ats_ptr_type loop_1 (ats_ptr_type arg0, ats_int_type arg1, ats_int_type arg2) ;

static ats_void_type loop_3 (ats_int_type env0, ats_ref_type arg0, ats_int_type arg1, ats_ptr_type arg2) ;
static ats_void_type loop_3_clofun (ats_clo_ptr_type clo, ats_ref_type arg0, ats_int_type arg1, ats_ptr_type arg2) ;
static ats_clo_ptr_type loop_3_clo_make (ats_int_type env0) ;

/* sum constructor declarations */

/* exception constructor declarations */

/* global dynamic constant declarations */

/* static temporary variable declarations */

/* function implementations */

ats_ptr_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_comarg_2esats__comarg_parse (ats_ptr_type arg0) {
ATSlocal(ats_ptr_type, tmp0) ;
ATSlocal(ats_ptr_type, tmp12) ;
ATSlocal(ats_size_type, tmp13) ;
ATSlocal(ats_int_type, tmp14) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_comarg_2esats__comarg_parse:
tmp12 = atspre_castfn_ptr (arg0) ;
tmp13 = atspre_string_length (tmp12) ;
tmp14 = atspre_int1_of_size1 (tmp13) ;
tmp0 = loop_1 (tmp12, tmp14, 0) ;
return tmp0 ;
} /* fun */

ats_ptr_type
loop_1 (ats_ptr_type arg0, ats_int_type arg1, ats_int_type arg2) {
ATSlocal(ats_ptr_type, tmp1) ;
ATSlocal(ats_bool_type, tmp2) ;
ATSlocal(ats_bool_type, tmp4) ;
ATSlocal(ats_char_type, tmp5) ;
ATSlocal(ats_ptr_type, tmp8) ;
ATSlocal(ats_int_type, tmp9) ;
ATSlocal(ats_int_type, tmp10) ;
__ats_lab_loop_1:
tmp2 = atspre_ilt (arg2, arg1) ;
if (tmp2) {
tmp5 = atspre_string_get_char_at__intsz (arg0, arg2) ;
tmp4 = atspre_neq_char_char (tmp5, '-') ;
if (tmp4) {
tmp1 = ATS_MALLOC(sizeof(_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_comarg_2edats_sum_0)) ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_comarg_2edats_sum_0*)tmp1)->atslab_0 = arg2 ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_comarg_2edats_sum_0*)tmp1)->atslab_1 = arg0 ;

} else {
tmp8 = arg0 ;
tmp9 = arg1 ;
tmp10 = atspre_iadd (arg2, 1) ;
arg0 = tmp8 ;
arg1 = tmp9 ;
arg2 = tmp10 ;
goto __ats_lab_loop_1 ;
} /* if */
} else {
tmp1 = ATS_MALLOC(sizeof(_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_comarg_2edats_sum_0)) ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_comarg_2edats_sum_0*)tmp1)->atslab_0 = arg1 ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_comarg_2edats_sum_0*)tmp1)->atslab_1 = arg0 ;

} /* if */
return tmp1 ;
} /* fun */

ats_ptr_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_comarg_2esats__comarglst_parse (ats_int_type arg0, ats_ref_type arg1) {
ATSlocal(ats_ptr_type, tmp15) ;
ATSlocal(ats_ptr_type, tmp30) ;
ATSlocal_void(tmp31) ;
ATSlocal_void(tmp32) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_comarg_2esats__comarglst_parse:
tmp30 = (ats_sum_ptr_type)0 ;

/* tmp31 = */ loop_3 (arg0, arg1, 0, (&tmp30)) ;
/* tmp32 = (tmp31) */;
tmp15 = tmp30 ;
return tmp15 ;
} /* fun */

ats_void_type
loop_3 (ats_int_type env0, ats_ref_type arg0, ats_int_type arg1, ats_ptr_type arg2) {
ATSlocal_void(tmp16) ;
ATSlocal(ats_bool_type, tmp17) ;
ATSlocal(ats_ptr_type, tmp19) ;
ATSlocal(ats_ptr_type, tmp20) ;
ATSlocal(ats_ptr_type, tmp21) ;
ATSlocal(ats_ptr_type, tmp22) ;
ATSlocal(ats_ptr_type, tmp23) ;
ATSlocal(ats_ptr_type, tmp24) ;
ATSlocal_void(tmp25) ;
ATSlocal(ats_int_type, tmp26) ;
ATSlocal_void(tmp27) ;
__ats_lab_loop_3:
tmp17 = atspre_ilt (arg1, env0) ;
if (tmp17) {
tmp19 = *((ats_ptr_type*)arg2) ;
tmp21 = (((ats_ptr_type*)arg0)[arg1]) ;
tmp20 = _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_comarg_2esats__comarg_parse (tmp21) ;
tmp23 = (ats_sum_ptr_type)0 ;

tmp22 = ATS_MALLOC(sizeof(_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_comarg_2edats_sum_1)) ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_comarg_2edats_sum_1*)tmp22)->atslab_0 = tmp20 ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_comarg_2edats_sum_1*)tmp22)->atslab_1 = tmp23 ;

tmp24 = &(((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_comarg_2edats_sum_1*)tmp22)->atslab_1) ;
tmp26 = atspre_iadd (arg1, 1) ;
/* tmp25 = */ loop_3 (env0, arg0, tmp26, tmp24) ;
/* tmp27 = (tmp25) */;
*((ats_ptr_type*)arg2) = tmp22 ;
/* tmp16 = ?void */ ;
} else {
/* tmp16 = ?void */ ;
} /* if */
return ;
} /* fun */

typedef struct {
ats_fun_ptr_type closure_fun ;
ats_int_type closure_env_0 ;
} loop_3_clo_type ;

ats_clo_ptr_type
loop_3_clo_make (ats_int_type env0) {
loop_3_clo_type *p = ATS_MALLOC(sizeof(loop_3_clo_type)) ;
p->closure_fun = (ats_fun_ptr_type)&loop_3_clofun ;
p->closure_env_0 = env0 ;
return (ats_clo_ptr_type)p ;
}

ats_void_type
loop_3_clofun (ats_clo_ptr_type clo, ats_ref_type arg0, ats_int_type arg1, ats_ptr_type arg2) {
loop_3 (((loop_3_clo_type *)clo)->closure_env_0, arg0, arg1, arg2) ; return ;
}

/* static load function */

extern ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_comarg_2esats__staload () ;
static int _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_comarg_2edats__staload_flag = 0 ;
ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_comarg_2edats__staload () {
if (_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_comarg_2edats__staload_flag) return ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_comarg_2edats__staload_flag = 1 ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_comarg_2esats__staload () ;
}

/* dynamic load function */

extern int _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_comarg_2edats__dynload_flag ;
ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_comarg_2edats__dynload () {
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_comarg_2edats__dynload_flag = 1 ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_comarg_2edats__staload () ;
}

/* external types */

/* external codes at mid */

/* external codes at bot */

