/*
 *
 * This C code is generated by ATS/Geizella
 * The compilation time is: 2012-5-27: 21:23
 *
 */

#define _ATS_GEIZELLA 1

#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"

/* include some .cats files */

#include "prelude/CATS/array.cats"
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/string.cats"

/* external codes at top */


//
extern void free (void*) ;
//
ATSinline()
ats_void_type
table_ptr_free (ats_ptr_type p) { free (p) ; return ; }


ATSinline()
ats_int_type
ats_int_of_int16 (ats_int16_type i) { return i ; }

/* type definitions */

typedef struct {
ats_ptr_type atslab_0 ;
ats_int_type atslab_1 ;
} _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_tables_2edats_sum_0 ;

/* external dynamic constructor declarations */

ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_tables_2edats__tblopt_some) ;
ATSextern(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_tables_2edats__tblopt_none) ;

/* external dynamic constant declarations */

extern ats_var_type ats_exit_errmsg(ats_int_type, ats_ptr_type) ;
extern ats_int_type atspre_add_int_int(ats_int_type, ats_int_type) ;
extern ats_int_type atspre_sub_int_int(ats_int_type, ats_int_type) ;
extern ats_int_type atspre_mul_int_int(ats_int_type, ats_int_type) ;
extern ats_bool_type atspre_lt_int_int(ats_int_type, ats_int_type) ;
extern ats_int_type atspre_asl_int_int1(ats_int_type, ats_int_type) ;
extern ats_bool_type atspre_ilt(ats_int_type, ats_int_type) ;
extern ats_bool_type atspre_igte(ats_int_type, ats_int_type) ;
extern ats_ptr_type atspre_ref_make_elt_tsz(ats_ref_type, ats_size_type) ;
extern ats_ptr_type atspre_ref_get_view_ptr(ats_ptr_type) ;
extern ats_ptr_type new_tbloptref_some(ats_ptr_type, ats_int_type) ;
extern ats_void_type table_ptr_free(ats_ptr_type) ;
extern ats_ptr_type __accept_table_make_fun(ats_int_type, ats_int_type, ats_ptr_type) ;
extern ats_int_type ats_int_of_int16(ats_int16_type) ;
extern ats_ptr_type __transition_table_make_fun(ats_int_type, ats_ptr_type) ;

/* internal function declarations */

static ats_ptr_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_reference_2esats__ref_make_elt__ats_ptr_type (ats_ptr_type arg0) ;

static ats_void_type tbloptref_free_2 (ats_ptr_type arg0) ;

static ats_ptr_type __ats_fun_4 (ats_int_type env0, ats_int_type arg0) ;
static ats_ptr_type __ats_fun_4_clofun (ats_clo_ptr_type clo, ats_int_type arg0) ;
static ats_clo_ptr_type __ats_fun_4_clo_make (ats_int_type env0) ;

static ats_ptr_type __ats_fun_5 (ats_int_type env0, ats_int_type env1, ats_ptr_type arg0) ;
static ats_ptr_type __ats_fun_5_clofun (ats_clo_ptr_type clo, ats_ptr_type arg0) ;
static ats_clo_ptr_type __ats_fun_5_clo_make (ats_int_type env0, ats_int_type env1) ;

static ats_ptr_type __ats_fun_9 (ats_int_type env0, ats_ptr_type arg0) ;
static ats_ptr_type __ats_fun_9_clofun (ats_clo_ptr_type clo, ats_ptr_type arg0) ;
static ats_clo_ptr_type __ats_fun_9_clo_make (ats_int_type env0) ;

/* sum constructor declarations */

ATSglobal(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_tables_2edats__tblopt_some) ;
ATSglobal(ats_sum_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_tables_2edats__tblopt_none) ;

/* exception constructor declarations */

ATSglobal(ats_exn_type, _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_lexing_2esats__LexingErrorException) ;

/* global dynamic constant declarations */

/* static temporary variable declarations */

/* function implementations */

ats_ptr_type
new_tbloptref_some (ats_ptr_type arg0, ats_int_type arg1) {
ATSlocal(ats_ptr_type, tmp0) ;
ATSlocal(ats_ptr_type, tmp1) ;
__ats_lab_new_tbloptref_some:
tmp1 = ATS_MALLOC(sizeof(_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_tables_2edats_sum_0)) ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_tables_2edats_sum_0*)tmp1)->atslab_0 = arg0 ;
((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_tables_2edats_sum_0*)tmp1)->atslab_1 = arg1 ;

tmp0 = _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_reference_2esats__ref_make_elt__ats_ptr_type (tmp1) ;
return tmp0 ;
} /* fun */

ats_ptr_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_reference_2esats__ref_make_elt__ats_ptr_type (ats_ptr_type arg0) {
ATSlocal(ats_ptr_type, tmp2) ;
ATSlocal(ats_ptr_type, tmp3) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_reference_2esats__ref_make_elt__ats_ptr_type:
tmp3 = arg0 ;
tmp2 = atspre_ref_make_elt_tsz ((&tmp3), sizeof(ats_ptr_type)) ;
return tmp2 ;
} /* fun */

ats_void_type
tbloptref_free_2 (ats_ptr_type arg0) {
ATSlocal_void(tmp4) ;
ATSlocal(ats_ptr_type, tmp5) ;
ATSlocal(ats_ptr_type, tmp6) ;
ATSlocal(ats_ptr_type, tmp7) ;
ATSlocal(ats_ptr_type, tmp9) ;
ATSlocal_void(tmp10) ;
ATSlocal(ats_ptr_type, tmp11) ;
__ats_lab_tbloptref_free_2:
tmp5 = atspre_ref_get_view_ptr (arg0) ;
tmp6 = (tmp5) ;
tmp7 = *((ats_ptr_type*)tmp6) ;
do {
__ats_lab_0:
if (tmp7 == (ats_sum_ptr_type)0) { goto __ats_lab_1 ; }
tmp9 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_tables_2edats_sum_0*)tmp7)->atslab_0 ;
ATS_FREE(tmp7) ;
/* tmp10 = */ table_ptr_free (tmp9) ;
tmp11 = (ats_sum_ptr_type)0 ;

*((ats_ptr_type*)tmp6) = tmp11 ;
break ;

__ats_lab_1:
break ;

} while (0) ;
return ;
} /* fun */

ats_ptr_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_lexing_2esats____accept_table_make (ats_int_type arg0) {
ATSlocal(ats_ptr_type, tmp13) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_lexing_2esats____accept_table_make:
tmp13 = (__ats_fun_4_clo_make (arg0)) ;
return tmp13 ;
} /* fun */

ats_ptr_type
__ats_fun_4 (ats_int_type env0, ats_int_type arg0) {
ATSlocal(ats_ptr_type, tmp14) ;
__ats_lab___ats_fun_4:
tmp14 = (__ats_fun_5_clo_make (env0, arg0)) ;
return tmp14 ;
} /* fun */

typedef struct {
ats_fun_ptr_type closure_fun ;
ats_int_type closure_env_0 ;
} __ats_fun_4_clo_type ;

ats_clo_ptr_type
__ats_fun_4_clo_make (ats_int_type env0) {
__ats_fun_4_clo_type *p = ATS_MALLOC(sizeof(__ats_fun_4_clo_type)) ;
p->closure_fun = (ats_fun_ptr_type)&__ats_fun_4_clofun ;
p->closure_env_0 = env0 ;
return (ats_clo_ptr_type)p ;
}

ats_ptr_type
__ats_fun_4_clofun (ats_clo_ptr_type clo, ats_int_type arg0) {
return __ats_fun_4 (((__ats_fun_4_clo_type *)clo)->closure_env_0, arg0) ;
}

ats_ptr_type
__ats_fun_5 (ats_int_type env0, ats_int_type env1, ats_ptr_type arg0) {
ATSlocal(ats_ptr_type, tmp15) ;
__ats_lab___ats_fun_5:
tmp15 = __accept_table_make_fun (env0, env1, arg0) ;
return tmp15 ;
} /* fun */

typedef struct {
ats_fun_ptr_type closure_fun ;
ats_int_type closure_env_0 ;
ats_int_type closure_env_1 ;
} __ats_fun_5_clo_type ;

ats_clo_ptr_type
__ats_fun_5_clo_make (ats_int_type env0, ats_int_type env1) {
__ats_fun_5_clo_type *p = ATS_MALLOC(sizeof(__ats_fun_5_clo_type)) ;
p->closure_fun = (ats_fun_ptr_type)&__ats_fun_5_clofun ;
p->closure_env_0 = env0 ;
p->closure_env_1 = env1 ;
return (ats_clo_ptr_type)p ;
}

ats_ptr_type
__ats_fun_5_clofun (ats_clo_ptr_type clo, ats_ptr_type arg0) {
return __ats_fun_5 (((__ats_fun_5_clo_type *)clo)->closure_env_0, ((__ats_fun_5_clo_type *)clo)->closure_env_1, arg0) ;
}

ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_lexing_2esats____accept_table_free (ats_ptr_type arg0) {
ATSlocal_void(tmp16) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_lexing_2esats____accept_table_free:
/* tmp16 = */ tbloptref_free_2 (arg0) ;
return ;
} /* fun */

ats_int_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_lexing_2esats__accept_table_get (ats_ptr_type arg0, ats_int_type arg1) {
ATSlocal(ats_int_type, tmp17) ;
ATSlocal(ats_int_type, tmp18) ;
ATSlocal(ats_int_type, tmp19) ;
ATSlocal(ats_ptr_type, tmp21) ;
ATSlocal(ats_ptr_type, tmp22) ;
ATSlocal(ats_ptr_type, tmp23) ;
ATSlocal(ats_ptr_type, tmp27) ;
ATSlocal(ats_int_type, tmp28) ;
ATSlocal(ats_bool_type, tmp29) ;
ATSlocal(ats_bool_type, tmp33) ;
ATSlocal(ats_int_type, tmp38) ;
ATSlocal(ats_int16_type, tmp39) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_lexing_2esats__accept_table_get:
tmp18 = 0 ;
tmp19 = 0 ;
tmp21 = atspre_ref_get_view_ptr (arg0) ;
tmp22 = (tmp21) ;
tmp23 = *((ats_ptr_type*)tmp22) ;
do {
__ats_lab_2:
if (tmp23 != (ats_sum_ptr_type)0) { goto __ats_lab_3 ; }
tmp19 = 1 ;
break ;

__ats_lab_3:
tmp27 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_tables_2edats_sum_0*)tmp23)->atslab_0 ;
tmp28 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_tables_2edats_sum_0*)tmp23)->atslab_1 ;
tmp29 = atspre_ilt (ats_castfn_mac(ats_int_type, arg1), 0) ;
if (tmp29) {
tmp19 = 2 ;
} else {
tmp33 = atspre_igte (ats_castfn_mac(ats_int_type, arg1), tmp28) ;
if (tmp33) {
tmp19 = 3 ;
} else {
tmp39 = (((ats_int16_type*)tmp27)[ats_castfn_mac(ats_int_type, arg1)]) ;
tmp38 = ats_int_of_int16 (tmp39) ;
tmp18 = tmp38 ;
} /* if */
} /* if */
break ;

} while (0) ;
do {
__ats_lab_4:
if (tmp19 != 1) { goto __ats_lab_5 ; }
/* tmp17 = */ ats_exit_errmsg (1, "lexing: accept_table_get: table is not available\n") ;
break ;

__ats_lab_5:
if (tmp19 != 2) { goto __ats_lab_6 ; }
/* tmp17 = */ ats_exit_errmsg (1, "lexing: accept_table_get: state number is illegal\n") ;
break ;

__ats_lab_6:
if (tmp19 != 3) { goto __ats_lab_7 ; }
/* tmp17 = */ ats_exit_errmsg (1, "lexing: accept_table_get: state number is illegal\n") ;
break ;

__ats_lab_7:
tmp17 = tmp18 ;
break ;

} while (0) ;
return tmp17 ;
} /* fun */

ats_ptr_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_lexing_2esats____transition_table_make (ats_int_type arg0) {
ATSlocal(ats_ptr_type, tmp44) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_lexing_2esats____transition_table_make:
tmp44 = (__ats_fun_9_clo_make (arg0)) ;
return tmp44 ;
} /* fun */

ats_ptr_type
__ats_fun_9 (ats_int_type env0, ats_ptr_type arg0) {
ATSlocal(ats_ptr_type, tmp45) ;
__ats_lab___ats_fun_9:
tmp45 = __transition_table_make_fun (env0, arg0) ;
return tmp45 ;
} /* fun */

typedef struct {
ats_fun_ptr_type closure_fun ;
ats_int_type closure_env_0 ;
} __ats_fun_9_clo_type ;

ats_clo_ptr_type
__ats_fun_9_clo_make (ats_int_type env0) {
__ats_fun_9_clo_type *p = ATS_MALLOC(sizeof(__ats_fun_9_clo_type)) ;
p->closure_fun = (ats_fun_ptr_type)&__ats_fun_9_clofun ;
p->closure_env_0 = env0 ;
return (ats_clo_ptr_type)p ;
}

ats_ptr_type
__ats_fun_9_clofun (ats_clo_ptr_type clo, ats_ptr_type arg0) {
return __ats_fun_9 (((__ats_fun_9_clo_type *)clo)->closure_env_0, arg0) ;
}

ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_lexing_2esats____transition_table_free (ats_ptr_type arg0) {
ATSlocal_void(tmp46) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_lexing_2esats____transition_table_free:
/* tmp46 = */ tbloptref_free_2 (arg0) ;
return ;
} /* fun */

ats_int_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_lexing_2esats__transition_table_get (ats_ptr_type arg0, ats_int_type arg1, ats_int_type arg2) {
ATSlocal(ats_int_type, tmp47) ;
ATSlocal(ats_int_type, tmp48) ;
ATSlocal(ats_int_type, tmp49) ;
ATSlocal(ats_ptr_type, tmp51) ;
ATSlocal(ats_ptr_type, tmp52) ;
ATSlocal(ats_ptr_type, tmp53) ;
ATSlocal(ats_ptr_type, tmp55) ;
ATSlocal(ats_int_type, tmp56) ;
ATSlocal(ats_int_type, tmp57) ;
ATSlocal(ats_bool_type, tmp58) ;
ATSlocal(ats_int_type, tmp59) ;
ATSlocal(ats_int_type, tmp62) ;
ATSlocal(ats_int_type, tmp63) ;
ATSlocal(ats_int_type, tmp64) ;
ATSlocal(ats_int_type, tmp65) ;
ATSlocal(ats_int_type, tmp66) ;
ATSlocal(ats_int_type, tmp67) ;
ATSlocal(ats_bool_type, tmp68) ;
ATSlocal(ats_bool_type, tmp72) ;
ATSlocal(ats_int_type, tmp77) ;
ATSlocal(ats_int16_type, tmp78) ;
__ats_lab__2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_lexing_2esats__transition_table_get:
tmp48 = 0 ;
tmp49 = 0 ;
tmp51 = atspre_ref_get_view_ptr (arg0) ;
tmp52 = (tmp51) ;
tmp53 = *((ats_ptr_type*)tmp52) ;
do {
__ats_lab_8:
if (tmp53 == (ats_sum_ptr_type)0) { goto __ats_lab_9 ; }
tmp55 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_tables_2edats_sum_0*)tmp53)->atslab_0 ;
tmp56 = ((_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_tables_2edats_sum_0*)tmp53)->atslab_1 ;
tmp59 = atspre_asl_int_int1 (1, 7) ;
tmp58 = atspre_lt_int_int (arg2, tmp59) ;
if (tmp58) {
tmp57 = arg2 ;
} else {
tmp57 = 0 ;
} /* if */
tmp62 = atspre_add_int_int (tmp57, 1) ;
tmp65 = atspre_sub_int_int (arg1, 1) ;
tmp67 = atspre_asl_int_int1 (1, 7) ;
tmp66 = atspre_add_int_int (tmp67, 1) ;
tmp64 = atspre_mul_int_int (tmp65, tmp66) ;
tmp63 = atspre_add_int_int (tmp64, tmp62) ;
tmp68 = atspre_ilt (ats_castfn_mac(ats_int_type, tmp63), 0) ;
if (tmp68) {
tmp49 = 2 ;
} else {
tmp72 = atspre_igte (ats_castfn_mac(ats_int_type, tmp63), tmp56) ;
if (tmp72) {
tmp49 = 3 ;
} else {
tmp78 = (((ats_int16_type*)tmp55)[ats_castfn_mac(ats_int_type, tmp63)]) ;
tmp77 = ats_int_of_int16 (tmp78) ;
tmp48 = tmp77 ;
} /* if */
} /* if */
break ;

__ats_lab_9:
tmp49 = 1 ;
break ;

} while (0) ;
do {
__ats_lab_10:
if (tmp49 != 1) { goto __ats_lab_11 ; }
/* tmp47 = */ ats_exit_errmsg (1, "lexing: transition_table_get: table is not available\n") ;
break ;

__ats_lab_11:
if (tmp49 != 2) { goto __ats_lab_12 ; }
/* tmp47 = */ ats_exit_errmsg (1, "lexing: transition_table_get: state number is illegal\n") ;
break ;

__ats_lab_12:
if (tmp49 != 3) { goto __ats_lab_13 ; }
/* tmp47 = */ ats_exit_errmsg (1, "lexing: transition_table_get: state number is illegal\n") ;
break ;

__ats_lab_13:
tmp47 = tmp48 ;
break ;

} while (0) ;
return tmp47 ;
} /* fun */

/* static load function */

extern ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_lexing_2esats__staload () ;
extern ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_reference_2esats__staload () ;
extern ats_void_type
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_reference_2edats__staload () ;
static int _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_tables_2edats__staload_flag = 0 ;
ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_tables_2edats__staload () {
if (_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_tables_2edats__staload_flag) return ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_tables_2edats__staload_flag = 1 ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_lexing_2esats__staload () ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_reference_2esats__staload () ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fats_reference_2edats__staload () ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_lexing_2esats__LexingErrorException.tag = ats_exception_con_tag_new () ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_lexing_2esats__LexingErrorException.name = "_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_lexing_2esats__LexingErrorException" ;
}

/* dynamic load function */

ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_tables_2edats__dynload () {
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2flibats_lex_tables_2edats__staload () ;
}

/* external types */

/* external codes at mid */

/* external codes at bot */



#define NBITS_PER_BYTE 8
/*
** NUMBER_OF_CHARS = 128 + 1
*/
#define NUMBER_OF_CHARS ((1 << (NBITS_PER_BYTE - 1)) + 1)

ats_ptr_type
__accept_table_make_fun
  (ats_int_type ntot, ats_int_type nfin, ats_ptr_type s0) {
  int i, nstate, irule, sz ;
  ats_int16_type *p0 ; ats_uchar_type *s ; ats_ptr_type res ;

  s = (ats_uchar_type*)s0;

  // [calloc] is used as only integers are to be stored; thus,
  // there is no need to scan the allocated memory during GC;
  // the allocated memory is freed by a call to [free]
  sz = ntot + 1 ; p0 = calloc (sz, sizeof(ats_int16_type)) ;  

  for (i = 0 ; i < nfin ; ++i) {
    nstate = (s[0] << NBITS_PER_BYTE) + s[1] ;
    s += 2 ;
    p0[nstate] = (s[0] << NBITS_PER_BYTE) + s[1] ;
    s += 2 ; 
/*
    fprintf (stdout, "%i -> %i\n", nstate, p0[nstate]) ;
*/
  } /* end of [for] */

  res = new_tbloptref_some (p0, sz) ;
/*
  fprintf (stdout, "__accept_table_make_fun: sz = %i\n", sz);
  fprintf (stdout, "__accept_table_make_fun: ptr = %p\n", p0);
  fprintf (stdout, "__accept_table_make_fun: res = %p\n", res);
*/
  return res ;
} /* end of [__accept_table_make_fun] */

ats_ptr_type
__transition_table_make_fun (ats_int_type n, ats_ptr_type s0) {
  int i, j, sz;
  ats_int16_type *p0, *p ; ats_uchar_type *s ;
  ats_ptr_type res ;

  sz = n * NUMBER_OF_CHARS ;

  // [malloc] is used as only integers are to be stored; thus,
  // there is no need to scan the allocated memory during GC;
  // the allocated memory is freed by a call to [free]
  p0 = malloc (sz*sizeof(ats_int16_type)) ; p = p0 ;
  s = (ats_uchar_type*)s0;
  for (i = 0 ; i < n ; ++i) {
    for (j = 0 ; j < NUMBER_OF_CHARS ; ++j) {
      *p = (s[0] << NBITS_PER_BYTE) + s[1] ;
/*
      fprintf (stdout, "__transition_table_make_fun: %i: *p = %i\n", j, *p);
*/
      s += 2 ; ++p ;
    } /* end of [for] */
  } /* end of [for] */

  res = new_tbloptref_some (p0, sz) ;
/*
  fprintf (stdout, "__transition_table_make_fun: sz = %i\n", sz);
  fprintf (stdout, "__transition_table_make_fun: ptr = %p\n", p0);
  fprintf (stdout, "__transition_table_make_fun: res = %p\n", res);
*/
  return res ;
} /* end of [__transition_table_make_fun] */


