/*
 *
 * This C code is generated by ATS/Geizella
 * The compilation time is: 2012-5-27: 21:23
 *
 */

#define _ATS_GEIZELLA 1

#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"

/* include some .cats files */

#include "prelude/CATS/array.cats"
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/string.cats"

/* external codes at top */



/* functions for exits */

ats_void_type // external
ats_exit(const ats_int_type n) { exit(n) ; return ; }

ats_void_type // external
ats_exit_errmsg
  (const ats_int_type n, const ats_ptr_type errmsg)
{
  fprintf(stderr, "%s", (char *)errmsg) ; exit(n) ; return ;
}




/* functions for asserts */

ats_void_type
atspre_assert (
  const ats_bool_type assertion
) {
  if (!assertion) {
    ats_exit_errmsg (1, "[Exit: atspre_assert] failed\n") ;
  }
  return ;
} // end of [atspre_assert]

ats_void_type
atspre_assert_errmsg (
  const ats_bool_type assertion, const ats_ptr_type errmsg
) {
  if (!assertion) {
    fprintf (stderr, "%s", (char *)errmsg) ;
    ats_exit_errmsg (1, "[Exit: atspre_assert_errmsg] failed\n") ;
  }
  return ;
} // end of [atspre_assert_errmsg]


/* type definitions */

/* external dynamic constructor declarations */

/* external dynamic constant declarations */

/* internal function declarations */

/* sum constructor declarations */

/* exception constructor declarations */

/* global dynamic constant declarations */

/* static temporary variable declarations */

/* function implementations */

/* static load function */

static int _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fprelude_dats_basics_2edats__staload_flag = 0 ;
ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fprelude_dats_basics_2edats__staload () {
if (_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fprelude_dats_basics_2edats__staload_flag) return ;
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fprelude_dats_basics_2edats__staload_flag = 1 ;
}

/* dynamic load function */

ats_void_type _2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fprelude_dats_basics_2edats__dynload () {
_2fhome_2ffac2_2fhwxi_2fresearch_2fATS_2fIMPLEMENT_2fGeizella_2fAnairiats_2fsvn_2fats_2dlang_2fsrc_2fprelude_dats_basics_2edats__staload () ;
}

/* external types */

/* external codes at mid */

/* external codes at bot */

