/*
**
** The C code is generated by ATS/Postiats
** The compilation time is: 2014-4-2:  0h:12m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_EXCEPTION_NONE
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_EXCEPTION_NONE]
#endif /* _ATS_CCOMP_HEADER_NONE */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE */

/*
staload-prologues(beg)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_print_string) ;
ATSdyncst_mac(atspre_print_newline) ;
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_EXCEPTION_NONE
extern void the_atsexncon_initize (atstype_exncon *d2c, char *exnmsg) ;
#endif // end of [_ATS_EXCEPTION_NONE]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
#if(0)
ATSglobaldec()
atsvoid_t0ype
mainats_void_0() ;
#endif // end of [QUALIFIED]

/*
/home/hwxi/research/Postiats/git/doc/EXAMPLE/INTRO/hello.dats: 66(line=8, offs=7) -- 701(line=21, offs=2)
*/
/*
local: 
global: mainats_void_0$0$0(level=0)
local: 
global: 
*/
ATSglobaldec()
atsvoid_t0ype
mainats_void_0()
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmpret0, atsvoid_t0ype) ;
ATStmpdec_void(tmp1, atsvoid_t0ype) ;
ATStmpdec_void(tmp2, atsvoid_t0ype) ;
ATStmpdec_void(tmp3, atsvoid_t0ype) ;
ATStmpdec_void(tmp4, atsvoid_t0ype) ;
ATStmpdec_void(tmp5, atsvoid_t0ype) ;
ATStmpdec_void(tmp6, atsvoid_t0ype) ;
ATStmpdec_void(tmp7, atsvoid_t0ype) ;
ATStmpdec_void(tmp8, atsvoid_t0ype) ;
ATStmpdec_void(tmp9, atsvoid_t0ype) ;
ATStmpdec_void(tmp10, atsvoid_t0ype) ;
ATStmpdec_void(tmp11, atsvoid_t0ype) ;
ATStmpdec_void(tmp12, atsvoid_t0ype) ;
ATStmpdec_void(tmp13, atsvoid_t0ype) ;
ATStmpdec_void(tmp14, atsvoid_t0ype) ;
ATStmpdec_void(tmp15, atsvoid_t0ype) ;
ATStmpdec_void(tmp16, atsvoid_t0ype) ;
ATStmpdec_void(tmp17, atsvoid_t0ype) ;
ATStmpdec_void(tmp18, atsvoid_t0ype) ;
ATStmpdec_void(tmp19, atsvoid_t0ype) ;
ATStmpdec_void(tmp20, atsvoid_t0ype) ;
ATStmpdec_void(tmp21, atsvoid_t0ype) ;
ATStmpdec_void(tmp22, atsvoid_t0ype) ;
ATStmpdec_void(tmp23, atsvoid_t0ype) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /home/hwxi/research/Postiats/git/doc/EXAMPLE/INTRO/hello.dats: 60(line=8, offs=1) -- 701(line=21, offs=2)
*/
__patsflab_main_void_0:
/*
emit_instr: loc0 = /home/hwxi/research/Postiats/git/doc/EXAMPLE/INTRO/hello.dats: 71(line=8, offs=12) -- 701(line=21, offs=2)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/hwxi/research/Postiats/git/doc/EXAMPLE/INTRO/hello.dats: 84(line=9, offs=12) -- 110(line=9, offs=38)
*/
ATSINSmove_void(tmp1, atspre_print_string(ATSPMVstring("\344\275\240\345\245\275\344\270\226\347\225\214!"))) ;

/*
emit_instr: loc0 = /home/hwxi/research/Postiats/git/doc/EXAMPLE/INTRO/hello.dats: 84(line=9, offs=12) -- 110(line=9, offs=38)
*/
ATSINSmove_void(tmp2, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/hwxi/research/Postiats/git/doc/EXAMPLE/INTRO/hello.dats: 133(line=10, offs=12) -- 158(line=10, offs=37)
*/
ATSINSmove_void(tmp3, atspre_print_string(ATSPMVstring("Hello world!"))) ;

/*
emit_instr: loc0 = /home/hwxi/research/Postiats/git/doc/EXAMPLE/INTRO/hello.dats: 133(line=10, offs=12) -- 158(line=10, offs=37)
*/
ATSINSmove_void(tmp4, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/hwxi/research/Postiats/git/doc/EXAMPLE/INTRO/hello.dats: 181(line=11, offs=12) -- 206(line=11, offs=37)
*/
ATSINSmove_void(tmp5, atspre_print_string(ATSPMVstring("Hello wereld"))) ;

/*
emit_instr: loc0 = /home/hwxi/research/Postiats/git/doc/EXAMPLE/INTRO/hello.dats: 181(line=11, offs=12) -- 206(line=11, offs=37)
*/
ATSINSmove_void(tmp6, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/hwxi/research/Postiats/git/doc/EXAMPLE/INTRO/hello.dats: 227(line=12, offs=12) -- 254(line=12, offs=39)
*/
ATSINSmove_void(tmp7, atspre_print_string(ATSPMVstring("Bonjour monde!"))) ;

/*
emit_instr: loc0 = /home/hwxi/research/Postiats/git/doc/EXAMPLE/INTRO/hello.dats: 227(line=12, offs=12) -- 254(line=12, offs=39)
*/
ATSINSmove_void(tmp8, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/hwxi/research/Postiats/git/doc/EXAMPLE/INTRO/hello.dats: 276(line=13, offs=12) -- 300(line=13, offs=36)
*/
ATSINSmove_void(tmp9, atspre_print_string(ATSPMVstring("Hallo Welt!"))) ;

/*
emit_instr: loc0 = /home/hwxi/research/Postiats/git/doc/EXAMPLE/INTRO/hello.dats: 276(line=13, offs=12) -- 300(line=13, offs=36)
*/
ATSINSmove_void(tmp10, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/hwxi/research/Postiats/git/doc/EXAMPLE/INTRO/hello.dats: 322(line=14, offs=12) -- 364(line=14, offs=54)
*/
ATSINSmove_void(tmp11, atspre_print_string(ATSPMVstring("\316\263\316\265\316\271\316\254 \317\203\316\277\317\205 \316\272\317\214\317\203\316\274\316\277\317\202!"))) ;

/*
emit_instr: loc0 = /home/hwxi/research/Postiats/git/doc/EXAMPLE/INTRO/hello.dats: 322(line=14, offs=12) -- 364(line=14, offs=54)
*/
ATSINSmove_void(tmp12, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/hwxi/research/Postiats/git/doc/EXAMPLE/INTRO/hello.dats: 385(line=15, offs=12) -- 409(line=15, offs=36)
*/
ATSINSmove_void(tmp13, atspre_print_string(ATSPMVstring("Ciao mondo!"))) ;

/*
emit_instr: loc0 = /home/hwxi/research/Postiats/git/doc/EXAMPLE/INTRO/hello.dats: 385(line=15, offs=12) -- 409(line=15, offs=36)
*/
ATSINSmove_void(tmp14, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/hwxi/research/Postiats/git/doc/EXAMPLE/INTRO/hello.dats: 432(line=16, offs=12) -- 467(line=16, offs=47)
*/
ATSINSmove_void(tmp15, atspre_print_string(ATSPMVstring("\343\201\223\343\202\223\343\201\253\343\201\241\343\201\257\344\270\226\347\225\214!"))) ;

/*
emit_instr: loc0 = /home/hwxi/research/Postiats/git/doc/EXAMPLE/INTRO/hello.dats: 432(line=16, offs=12) -- 467(line=16, offs=47)
*/
ATSINSmove_void(tmp16, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/hwxi/research/Postiats/git/doc/EXAMPLE/INTRO/hello.dats: 491(line=17, offs=12) -- 524(line=17, offs=45)
*/
ATSINSmove_void(tmp17, atspre_print_string(ATSPMVstring("\354\227\254\353\263\264\354\204\270\354\232\224 \354\204\270\352\263\204!"))) ;

/*
emit_instr: loc0 = /home/hwxi/research/Postiats/git/doc/EXAMPLE/INTRO/hello.dats: 491(line=17, offs=12) -- 524(line=17, offs=45)
*/
ATSINSmove_void(tmp18, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/hwxi/research/Postiats/git/doc/EXAMPLE/INTRO/hello.dats: 546(line=18, offs=12) -- 570(line=18, offs=36)
*/
ATSINSmove_void(tmp19, atspre_print_string(ATSPMVstring("Ol\303\241 mundo!"))) ;

/*
emit_instr: loc0 = /home/hwxi/research/Postiats/git/doc/EXAMPLE/INTRO/hello.dats: 546(line=18, offs=12) -- 570(line=18, offs=36)
*/
ATSINSmove_void(tmp20, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/hwxi/research/Postiats/git/doc/EXAMPLE/INTRO/hello.dats: 596(line=19, offs=12) -- 641(line=19, offs=57)
*/
ATSINSmove_void(tmp21, atspre_print_string(ATSPMVstring("\320\227\320\264\321\200\320\260\320\262\321\201\321\202\320\262\321\203\320\273\321\202\320\265 \320\274\320\270\321\200!"))) ;

/*
emit_instr: loc0 = /home/hwxi/research/Postiats/git/doc/EXAMPLE/INTRO/hello.dats: 596(line=19, offs=12) -- 641(line=19, offs=57)
*/
ATSINSmove_void(tmp22, atspre_print_newline()) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/hwxi/research/Postiats/git/doc/EXAMPLE/INTRO/hello.dats: 664(line=20, offs=12) -- 688(line=20, offs=36)
*/
ATSINSmove_void(tmp23, atspre_print_string(ATSPMVstring("Hola mundo!"))) ;

/*
emit_instr: loc0 = /home/hwxi/research/Postiats/git/doc/EXAMPLE/INTRO/hello.dats: 664(line=20, offs=12) -- 688(line=20, offs=36)
*/
ATSINSmove_void(tmpret0, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/hwxi/research/Postiats/git/doc/EXAMPLE/INTRO/hello.dats: 71(line=8, offs=12) -- 701(line=21, offs=2)
*/
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn_void(tmpret0) ;
} /* end of [mainats_void_0] */

/*
** for initialization(dynloading)
*/
atsvoid_t0ype
_057_home_057_hwxi_057_research_057_Postiats_057_git_057_doc_057_EXAMPLE_057_INTRO_057_hello_056_dats__dynload()
{
ATSdynload0(
_057_home_057_hwxi_057_research_057_Postiats_057_git_057_doc_057_EXAMPLE_057_INTRO_057_hello_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_home_057_hwxi_057_research_057_Postiats_057_git_057_doc_057_EXAMPLE_057_INTRO_057_hello_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_home_057_hwxi_057_research_057_Postiats_057_git_057_doc_057_EXAMPLE_057_INTRO_057_hello_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSreturn_void() ;
} /* end of [*_dynload] */

/*
** the ATS runtime
*/
#ifndef _ATS_CCOMP_RUNTIME_NONE
#include "pats_ccomp_runtime.c"
#include "pats_ccomp_runtime_memalloc.c"
#ifndef _ATS_EXCEPTION_NONE
#include "pats_ccomp_runtime2_dats.c"
#ifndef _ATS_CCOMP_RUNTIME_TRYWITH_NONE
#include "pats_ccomp_runtime_trywith.c"
#endif /* _ATS_CCOMP_RUNTIME_TRYWITH_NONE */
#endif // end of [_ATS_EXCEPTION_NONE]
#endif /* _ATS_CCOMP_RUNTIME_NONE */

/*
** the [main] implementation
*/
int
main
(
int argc, char **argv, char **envp
) {
int err = 0 ;
_057_home_057_hwxi_057_research_057_Postiats_057_git_057_doc_057_EXAMPLE_057_INTRO_057_hello_056_dats__dynload() ;
ATSmainats_void_0(err) ;
return (err) ;
} /* end of [main] */
